const cityOracleResults = {
    "oracle-smell-result": [
        "Cigarette Smoke",
        "Cheap Perfume",
        "expensive Cologne",
        "exhaust Fumes",
        "Stale refuse",
        "urine",
        "Vomit",
        "Burning Plastic",
        "Ash",
        "Acrid Chemicals",
        "Cordite",
        "Blood",
        "Wet hair",
        "Motor Oil",
        "Faeces",
        "Soda Pop Sweetness",
        "Noodles",
        "rubber",
        "Burnt Meat",
        "Dirty Sneakers",
        "Fried Food",
        "Beer",
        "Perfumed Bleach",
        "Body Odour",
        "Varnish",
        "Insecticide",
        "Soap",
        "Sulphur",
        "hairspray",
        "Printed Polyamides",
        "hydraulic Fluid",
        "Coffee",
        "resin",
        "Antiseptic",
        "Candy",
        "Mint",
        "Salt",
        "Tea",
        "Fresh Sweat",
        "Infected Tissue",
        "Paint",
        "Mold & Mildew",
        "Baby Powder",
        "Acid",
        "Feet",
        "Cinnamon",
        "leather",
        "lemon Zest",
        "Damp",
        "rot",
        "Overheated Circuit Board",
        "Cigars",
        "Floral Scent",
        "Pizza",
        "Spices",
        "lavender",
        "Sewage",
        "Pine",
        "Crack Cocaine",
        "Cat Piss",
        "Gas",
        "latex",
        "French Fries",
        "New Cyberlimb Smell",
        "Sex",
        "Menthol",
        "Cheese",
        "Wet Concrete",
        "Disinfectant",
        "Polythene",
        "Nail Varnish",
        "Whiskey",
        "Coconut Oil",
        "Vinyl",
        "Wine",
        "Acetone",
        "Cookies",
        "Ammonia",
        "Biodiesel",
        "Polish",
        "Printer Toner",
        "Dust",
        "Glass Cleaner",
        "Musty",
        "Opiates",
        "raw Meat",
        "laminate",
        "Weed/Skunk",
        "Drains",
        "Thinners",
        "Old Food",
        "Incense",
        "Fused Wiring",
        "lube",
        "Sour Milk",
        "Garlic",
        "Alcohol Sanitiser",
        "Cheap Aftershave",
        "Gun Oil",
    ],
    "oracle-sound-result": [
        "Building Alarm",
        "Barking Dogs",
        "Incoherent Shouting",
        "A Single Gunshot",
        "Ventilation System",
        "Car Doors Slamming",
        "loud Television",
        "Children",
        "Aerocar Overhead",
        "Catchy Corporate Jingle",
        "The Screech Of Tires",
        "Pedestrian Crosswalk",
        "rattle Cans In use",
        "heavy Gunfire",
        "Sobbing",
        "Channeled Winds",
        "hum Of A Cleaning ‘Bot",
        "Buzzing Of Flies",
        "rattle Of Chains",
        "Arcade Machines",
        "Breaking Glass",
        "Text Alert",
        "An rPG launching",
        "Sirens Inbound",
        "running",
        "Subway rumble",
        "A loud Argument",
        "Drill Or Power Saw",
        "road Traffic Accident",
        "hellfire Street Preacher",
        "loud energetic <a href=\"/oracles/misc-oracles#music-genre--subculture-style\">music</a>",
        "laughter",
        "hydraulics",
        "A reversing Vehicle",
        "An Annoying ringtone",
        "Sexual Activity",
        "Police radio Chatter",
        "loose Door Or Gate",
        "Group Chanting",
        "Popular Theme Tune",
        "Chesty Coughing",
        "Vehicle Alarm",
        "Steady Footsteps",
        "Automated Warning",
        "Beating Of heavy rain",
        "Garbled loudspeaker",
        "exchange Of Gunfire",
        "Background ‘Muzak’",
        "Gutteral Screaming",
        "A Call To Prayer",
        "loose Piping",
        "helicopter Overhead",
        "The Buzz Of Neon",
        "A revving engine",
        "An Impromptu rave",
        "Water Pump",
        "road Works",
        "right Wing Talk radio",
        "Foreign Busker",
        "Ice Cream Truck",
        "Distant explosion",
        "Car horn",
        "uAV/Drone Motor",
        "Tumbling Trash Cans",
        "evangelical Broadcast",
        "Very heavy Transport",
        "running Water",
        "Drunk Singing",
        "Skateboards",
        "Tattoo Gun",
        "rolling Cans",
        "Obvious Porno",
        "riot Or Demo",
        "Overhead Train",
        "Cats Fighting",
        "Shrill Whistling",
        "Bug Zapper",
        "Street hawker",
        "Car Chase",
        "Chilling War Cry",
        "Motorcycles",
        "Crackle Of Flames",
        "Door Buzzer",
        "An Anguished Cry",
        "Sneaker Squeak",
        "Scraping Metal",
        "Splashing",
        "Noisy Printer",
        "laser Fire",
        "Jingle Of Keys",
        "Quiet Conversation",
        "Sirens Outbound",
        "Aerocar landing",
        "Frying Food",
        "A Brawl",
        "Doors Slamming",
        "<a href=\"/oracles/city-oracles#advertainment\">Ads</a>",
        "Thunder",
        "hissing White Noise",
    ],
    "oracle-sight-result": [
        "Armoured cops bundle violently reluctant vagrant into ERA-plated squad car",
        "A bus shelter made entirely of screens showing <a href=\"/oracles/city-oracles#advertainment\">flashy commercials</a>",
        "Searchlights playing across the cloud cover and projecting ybranding</a>",
        "A brightly lit aerocab taking off in a cloud of exhaust fumes, rainwater and trash",
        "AC vents in the sidewalk emitting a thick cloud of vapour",
        "A heavy rainwater cascade falls from damaged guttering",
        "every underlit face on the street is concentrating solely on their phone",
        "An ancient looking geriatric lopes past strapped into a linear assistance frame",
        "A vid-blogger in full, wearable array, blatantly recording the scene",
        "The nearest building has an intermittently flickering security light",
        "Your view is blocked by a lumbering hi-vis recycling collection truck",
        "A cluster of kids vaping, leD-lit clouds from under designer pollution hoods",
        "A pair of bicycle couriers race one another through crawling traffic",
        "Gritty, chemical infused sediment sloughing off a nearby rooftop",
        "A large building-mounted flatscreen <a href=\"/oracles/city-oracles#screen-content\">showing something</a>",
        "unattended roadworks, the area coned off and lit for safety for no good reason",
        "An automated noodle vending truck, jingle playing, folds open and deploys nearby",
        "A flock of scabrous-looking pigeons suddenly taking flight",
        "A busy metro platform, full to capacity with disgruntled, rain-soaked commuters",
        "An abandoned cybernetic limb lies forlornly by the kerb",
        "Animated street art that twists and turns across two adjoining walls",
        "Frantic homeless people, washing vehicle windscreens before the lights change",
        "The flashing orange lights of a fat, dirty-yellow street sweeping remote",
        "A nearby dataterm is missing it’s screen and is stuffed with trash",
        "Your way is barred by a precarious heap of obsolete electronics",
        "The rainbow incandescence of oil on a large puddle of dirty water",
        "The substandard cheapcrete is pockmarked by years of corrosive rains",
        "A loaded pizza delivery drone hovering about three meters above the ground",
        "A wage-slave arguing with her phone’s onboard AI, before breaking down crying",
        "An orange, multi-limbed, window cleaning drone clambers up the building facade",
        "A long, silent queue for a blocky, exhaust stained, kerb-side euthanasia Booth™",
        "All the nearby street signs are <a href=\"/oracles/faction-oracles#street-gangs\">gang-tagged</a> over to the point of being useless",
        "Filthy red and white plastic Jersey barriers block most of the sidewalk",
        "An overpass or skywalk covered in colourful <a href=\"/oracles/city-oracles#advertainment\">advertising animatics</a>",
        "There are crowds of fast moving people swarming absolutely everywhere",
        "The scorched shell of a gutted vid-phone kiosk",
        "Pedestrians flooding across the nearest intersection, en masse, both ways",
        "A group of screeching street kids running along the overhead rail lines",
        "A thick pea soup fog rolling down the streets and alleyways",
        "All the street lights for this entire block just went out",
        "rivers of rain-borne trash race along in the choked gutters",
        "A small crowd of people gawping upwards at a potential jumper",
        "A tight formation of drones races down the street, just above head height",
        "A group of <a href=\"/oracles/character-oracles#street-walker\">sex workers</a> on a nearby street corner, approaching cars",
        "An out-of-order ATM threatens violent action to passers by who stray too close",
        "unnervingly, there is absolutely no-one about",
        "A <a href=\"/oracles/character-oracles#cabbie\">pedicab operator</a> struggling with heat exhaustion or dehydration",
        "A row of vendomats coated in layers of <a href=\"/oracles/faction-oracles#street-gangs\">gang</a> tags, going back many years",
        "A GEV <a href=\"/oracles/character-oracles#cabbie\">taxi</a> takes a corner hard, throwing up polluted water, trash and crud",
        "An energetic street preacher giving a digital presentation on Cybernetic Jesus®",
        "The sidewalk consists of slabs of flickering screens, showing <a href=\"/oracles/city-oracles#advertainment\">adverts</a>",
    ],
    "oracle-building-type-result": [
        "Pharmacy",
        "Consumer electronics",
        "Art Dealer or Gallery",
        "Auto or robotics repair",
        "Storage units or Warehousing",
        "legal Firm",
        "Religious temple",
        "Capsule hotel",
        "Data Storage",
        "low rent housing Project",
        "Grocery Store or hypermarket",
        "elevated rail or road Overpass",
        "Fast Food Franchise",
        "Police Precinct",
        "School or College",
        "Government Offices",
        "Garage or Parking Block",
        "Office Block",
        "Public Transport hub",
        "hospital or Clinic",
        "Department Store",
        "Body Augmentation Clinic",
        "luxury Apartments",
        "News Media Company",
        "Industrial",
        "Security Tech",
        "Vehicle Showroom",
        "Fashion Boutique",
        "Mall",
        "VRcade",
        "Gym",
        "leisureplex",
        "Apartment Block or hab Stack",
        "Nightclub",
        "Underpass",
        "Hotel",
        "Ripperdoc",
        "3D Print Fabrication",
        "Courier or Bulk Transport Company",
        "Bar",
        "restaurant",
        "Pop-up Market",
        "Coffee Shop",
        "Taxi Firm",
        "Pocket Park",
        "Suburban housing",
        "Movie Theatre",
        "Weapons Tech or Sales",
        "Multi-level Car Park",
        "Bank",
        "Antiques Shop",
        "Armory",
        "Consumer Tech Shop",
        "Robot repair shop",
        "Cyberware upgrades shop",
        "Foodstand Gallery",
        "Street Market",
    ],
    "oracle-building-feature-result": [
        "extreme Security Protocols",
        "Decrepit and rundown",
        "Graffitipocalypse/Street Art heavy",
        "Obvious <a href=\"/oracles/faction-oracles#street-gangs\">Gang</a> Turf",
        "Back room Brothel",
        "Newly renovated",
        "unusually Busy",
        "empty/Quiet",
        "Inadequate Security",
        "high Tech equipment",
        "Abandoned edifice",
        "Front For <a href=\"/oracles/character-oracles#corporate-aristocrat\">Corporate Activity</a>",
        "Front For Criminal Activity",
        "hidden Squatters",
        "Obscured By <a href=\"/oracles/city-oracles#advertainment\">Ad</a> Screens",
        "‘Grown’ By Nanites",
        "Incomplete",
        "Self Sufficient",
        "Crumbling Cheapcrete",
        "War Zone",
        "Fire Damage",
        "Not A Building, But Mobile",
        "elaborate Balconies",
        "Years Of Clumsy Modification",
        "For Sale/To-let",
        "Bright emoji Glyphs And Graphics",
        "reinforced for repair Work",
        "extremely leaky",
        "Gothic Style",
        "Chic And Minimalist",
        "Brutalist",
        "encased In Plastic Siding",
        "labyrinthine",
        "Skywalks To Other Buildings",
        "Industrial Style",
        "Anti-Drone System",
        "Nano Immune System",
        "People Queue To enter",
        "Well Guarded",
        "AI Guardian",
        "<a href=\"/oracles/misc-oracles#ar-display\">AR</a> heavy",
        "Selective Access",
        "<a href=\"/oracles/misc-oracles#bug-in-the-system\">Buggy</a> Security Net",
        "Taken Over By Junkies",
        "Foreign Ghetto",
        "Sweatshop Conditions",
        "utilised Solely For Storage",
        "Veiled Behind Polymer Sheeting",
        "All Windows Damaged",
        "external utilities",
        "extensive Solar Grid And Fog Catchers",
        "Bad epoxy repairs",
        "unpleasant Micro-Climate",
        "Infested With rogue remotes",
        "Self Aware",
        "Cellular Black hole",
        "Mainly Populated By hoarders",
        "Accumulated Trash heaps",
        "unusual <a href=\"/oracles/city-oracles#smell\">Smell</a>",
        "Very Few Working lights",
        "A riot Of Satellite Dishes",
        "Very Noisy utilities",
        "Catastrophically Polluted",
        "unfinished extension Or empty levels",
        "Permadamp",
        "<a href=\"/oracles/city-oracles#legacy-infrastructure\">legacy Infrastructure</a>",
        "Bad Wiring; high EMF; Blackouts",
        "Patrolled By hired <a href=\"/oracles/character-oracles#law-enforcement\">rent-A-Cops</a>",
        "Aggressively enforced No-Parking Zone",
        "Windows Boarded With Opaque Acrylic",
        "Main entrance Out Of Order",
        "Several Trashed Cars Out Front",
        "Being Audited By Fanatical City Inspectors",
        "Wind Tunnel",
        "Tinted Glass And Carbon Nano-Tubes",
        "homeless Magnet",
        "Shakes When Trucks Pass",
        "Completely Automated",
        "exotic/Foreign Architecture",
        "Obvious Corporate Sponsor",
        "endorsed By Celebutant",
        "Promotes religion",
        "Independent Nation State",
        "Family Owned",
        "Scheduled For Demolition",
        "rat or roach Problem",
        "Security Camera Overkill",
        "A Crime Scene",
        "Target Of Net Terrorism",
        "Malfunctioning Incessant Alarm",
        "Slowly Collapsing Or Subsiding",
        "under Surveillance",
        "enforced No Fly Zone",
        "Prone To Flooding",
        "ecologically Sound; No Carbon Footprint",
        "Popular With Particular Subculture",
        "Totally Sterile",
        "extensive Drone Docks",
        "Causes <a href=\"/oracles/city-oracles#strange-sickness\">Sickness</a>",
    ],
    "oracle-building-architecture-result": [
        "Gothic",
        "Brutalist",
        "Asian",
        "Japanese",
        "Chinese",
        "Russian",
        "Massive",
        "Towering",
        "Floating",
        "Modern",
        "Victorian",
        "Contemporary",
        "Art Deco",
        "Islamic",
        "Industrial",
        "Eclectic",
        "Reflective",
        "Orbital",
        "Clean",
        "Neon-filled",
        "Suburban",
    ],
    "oracle-building-interior-style-result": [
        "Minimalist",
        "Industrial",
        "Shabby-Chic",
        "(Bio)Organic",
        "Brushed Steel",
        "Polymer Baroque",
        "Gothic",
        "rustic",
        "Office Beige",
        "hexagonal Tiles",
        "Modern",
        "80's fashion",
        "Asian",
        "African",
        "Reflective",
        "Brutalist",
        "Cozy",
        "Japanese",
    ],
    "oracle-building-interior-state-result": [
        "untidy",
        "Pristine",
        "Sterile",
        "Cramped",
        "Lived in",
        "Spacious",
        "Cavernous",
        "Biohazard",
        "Organised",
        "Cluttered",
        "Feng Shui",
        "Seemingly abandoned",
        "Humid",
        "Foggy",
        "Well-decorated",
        "Dark",
        "Well-lit",
        "Dusty",
        "Reclaimed by nature",
    ],
    "oracle-building-interior-feature-result": [
        "Hydroponics",
        "Scavenged Furniture",
        "Holograms",
        "Monochromatic tones",
        "Artificial Plants",
        "Strange Acoustics",
        "Weird <a href=\"/oracles/city-oracles#smell\">Smell</a>",
        "remote Assistants",
        "legacy or outdated Tech",
        "exotic Pets",
        "Baroque decorations",
        "Hanging lamps",
        "Varying floor levels",
        "Modern robotics",
        "Wall-to-wall screens",
        "Wide windows",
        "Animated wallpapers",
        "big fish tanks",
        "Neon glow",
    ],
    "oracle-building-interior-secret-result": [
        "Cameras",
        "Microphone",
        "Privacy Screen",
        "Separate / Isolated LAN",
        "hidden room",
        "escape route",
        "Custodian AI",
        "Weapon Sensor",
        "Weapons Cache",
        "hidden Stash",
        "Silent alarm",
    ],
    "oracle-upcycled-stuff-result": [
        "Power plant from main battle tank, used as a generator for a squat or shanty",
        "hydroponics rig from scrapped research ship, used to breed modified food-algae",
        "Atmosphere recycling taken from orbital work shack, for a sealed environment",
        "Automotive industry robotic arms fitted with tasers, utilised for entrance security",
        "Chinese banking servers, used as a fixer’s offline data archive",
        "Shipping container homes, mounted on scaffolding with industrial adhesives",
        "Aircraft seating used as makeshift furniture, within parachute nylon shelters",
        "Downed corporate surveillance drone, reconfigured to enable secure phone calls",
        "Salvaged fast food friers and ovens, co-opted for mass drug production",
        "Outmoded clinical CAT scanner, jury-rigged into rudimentary security screen",
    ],
    "oracle-legacy-infrastructure-result": [
        "Decommissioned subway tunnel, accessible from building, and vice versa",
        "Off site telecoms junction box, once served the local neighborhood",
        "Condemned slum quarantined with concrete seal, or biohazard containment zone",
        "Interconnected basements and foundation voids, poorly secured",
        "Sealed sub-basement parking for previous building, with still functioning elevator",
        "Forgotten floor following remodelling work, accessible through crawl space",
        "Disused loading or maintenance bay, with hidden goods elevator",
        "undocumented Cold War bomb shelter or bunker network",
        "exposed air venting system, leading to moth-balled sub-basement laboratory",
        "unused utilities still feed into buildings, accessible from empty sewerage system",
    ],
    "oracle-bar-club-name-result": [
        "Below Zero",
        "Dubculture",
        "The Dancetería",
        "Club Synapse",
        "Atrocity",
        "Storm",
        "The Dispensary",
        "Ryumi’s",
        "The Black room",
        "The Flesh Café",
        "Va11-hall-a",
        "Donnegal",
        "Afterlife",
        "ARCAD3",
        "Riot",
        "Lizzie's Bar",
        "Yagami",
        "El Coyote Cojo",
        "Totentanz",
        "Red Dirt",
        "Konpeki",
        "Club Atlantis",
        "Wond3rL4nd",
        "Pandemonium",
        "Dante's Inferno",
        "Club Penumbra",
        "Cutting Edge",
        "Casey's",
        "Noctis",
        "Underworld",
        "The Pit",
        "Ivory Tower",
    ],
    "oracle-bar-club-status-result": [
        "New Owner(s)",
        "Closing Down",
        "Drug Problem",
        "Violence Problem",
        "Criminal Owned",
        "Bad reputation",
        "Student crowd",
        "under Surveillance",
        "War Zone",
        "Best Bands/DJs",
        "Frequented by hackers and techies",
        "Frequented by Mercs and Runners",
        "Good for networking with Corpos",
        "Known for its dancing floor",
        "Stripper shows",
        "Good jazz band gigs",
        "Rock shows",
        "Punk-rock crowd",
        "Sarariman crowd",
        "Exclusive / hard to get in",
        "Big rock show going on",
        "Frequented by celebrities",
        "low ambient music, good to talk",
        "<a href=\"/oracles/faction-oracles#street-gangs\">Gang</a> HQ",
        "Illegal fight ring",
        "A known <a href=\"/oracles/character-oracles#fixer\">Fixer</a> works here",
        "filled with old fashioned Arcades and other entertainment stations",
    ],
    "oracle-bar-club-security-result": [
        "None",
        "Cameras & Alarm",
        "Armed Owner",
        "local Gang",
        "Armed Bouncers",
        "24 hour Security",
        "hired Thugs",
        "Weapon Scanners",
        "Cyborg Bouncers",
        "State-of-the-Art",
    ],
    "oracle-bar-club-vibe-result": [
        "Total Dive",
        "Atmospheric",
        "Gang Turf",
        "Fashionable",
        "PermaParty",
        "Sleazy",
        "Quiet",
        "Franchise",
        "Popular",
        "exclusive",
    ],
    "oracle-screen-content-result": [
        "Video gaming event",
        "highlights from major sporting event",
        "System error message/connection failure",
        "The time and date",
        "The latest <a href=\"/oracles/misc-oracles#news-feed\">news headlines</a> and lottery result",
        "Infomercial/<a href=\"/oracles/city-oracles/#advertainment\">Advertainment</a>",
        "The weather forecast/air quality statistics",
        "Pornography (hacked and then squirtcast?)",
        "Music videos or movie trailers",
        "Traffic information",
        "Idoru or K-POP poster for upcoming gig",
        "Giant well-known brand logo",
        "breaking news of an extremely violent crime with graphic content",
        "VTuber or Kawaii Avatar interviewing a politician",
        "Known hacktivist group infiltrating the media feed and giving an ultimatum or manifesto",
        "A popular <a href=\"/oracles/misc-oracles#vid-show\">vidshow</a> is being cast",
        "A new music hit of a <a href=\"/oracles/misc-oracles#music-genre--subculture-style\">specific genre</a> is being promoted",
    ],
    "oracle-nightclub-encounter-result": [
        "A person spits in the face of one of you.",
        "Police officers enter and arrest a patron.",
        "A fight breaks out right next to you.",
        "A bartender smashes a bottle over the head of a patron.",
        "A man drops a credstick near you.",
        "Someone attempts to pickpocket one of you.",
        "An unconscious woman near the restrooms.",
        "A heavily-tattooed man says one of you pushed him.",
        "A woman crying in the corner.",
        "Police raid the club.",
        "An Ex spots one of you.",
        "An unconscious man in the corner.",
        "Someone tries to sell a gun to one of you.",
        "Someone approaches you and says you are wanted in a backroom.",
        "A gorgeous woman asks one of you to play pool.",
        "Several individuals wearing gang colors tell you that you are sitting at their table.",
        "A car crashes through the front of the club causing mayhem.",
        "Someone tries to slip something to your drink.",
        "Gang raids the club.",
        "Someone throws a drink into your face.",
        "Corporate mercenary unit raids the club.",
        "At a secluded table, a person types fanatically on a computer.",
        "A dog runs loose in the club.",
        "A person yells at one of you, then comes close and slips them a note before running out of the room.",
        "Someone offers one of you a cigarette.",
        "The power goes out and panic ensues.",
        "DJ’s pyrotechnics malfunction starting a fire.",
        "An older man desperately trying to look young attempts to talk to every female member in your group.",
        "A woman hands one of you a credstick and slips into the crowd.",
        "The DJ is having an off night. People begin to boo.",
        "The music stops as the DJ appears to be checking his email. The crowd starts becoming unruly.",
        "A man hands a microchip to one of you and slips away.",
        "A man crying in the corner.",
        "A fight breaks out in the ladies room",
        "When a man is bumped into he fumbles a container and the surrounding area is treated to a shower of green pills.",
        "The DJ walks out causing the crowd to get restless.",
        "A dude just standing in the middle of the dance floor.",
        "A fight breaks out in the men’s room",
        "A celebrity holding court at a corner table.",
        "Someone mistakes one of you for someone else and punches them.",
        "You witness a drug deal.",
        "Someone loudly complains about the DJ. The DJ pulls a gun.",
        "Bouncers get into a fight with some patrons.",
        "Several patrons begin to heckle the DJ.",
        "A drug deal goes bad and a gun is pulled. People panic.",
        "A bouncer asks to see your ID",
        "An illegal fight club is being held in a backroom.",
        "A person passed out at a table.",
        "Bouncers are keeping people out of a certain backroom.",
        "A light bar falls, hurting several people.",
        "Fight breaks out among rival gangs.",
        "You see someone slipping something into another’s drink.",
        "The DJ motions to you and hands you a jumpdrive.",
        "Small orange pills lie on the floor.",
        "As you sit down you notice a yellow pill on the chair.",
        "Someone mistakes you for someone else and begins screaming at you.",
        "A bartender throws a drink in the face of one you.",
        "The bartender tells you drinks are on the house.",
        "A person bumps into you hard.",
        "The selves of alcohol behind the bar collapse causing a huge mess and injuring some people.",
        "You are given someone else's drinks.",
        "Dueling DJs get into a fight.",
        "A drug dealer offers you a variety of pills.",
        "Illegal gambling is going on in a backroom.",
        "An older woman desperately trying to look young attempts to talk to every male in your group.",
        "The crowd starts throwing bottles at the DJ.",
        "A woman asks one of you to dance.",
        "A shadowy figure across the room buys you a round of drinks.",
        "A popular DJ is playing tonight and the place is packed.",
        "Bouncers tell one of you they have to get out.",
        "A small bomb explodes across the room from you.",
        "A man begins to flirt with one of you.",
        "A bouncer says one of you is not dressed appropriately and will have to leave.",
        "As one of you sit down they notice a credstick on the chair.",
        "Bouncers toss out a drunk patron.",
        "Someone on the dance floor pulls a gun.",
        "A bartender pulls a gun on a patron.",
        "A bouncer approaches you and tells you that you haven’t paid for your drinks.",
        "A bouncer says that they heard you are threatening other club-goers.",
        "A jumpdrive lying on the floor.",
        "A person bumps into one of you lightly.",
        "A woman hands a jumpdrive to one of you and runs away.",
        "A woman asks to buy her a drink.",
        "A person hands one of you a smartphone and runs away.",
        "A man asks to buy him a drink.",
        "A waitress tells you the owner would like to see you.",
        "A bouncer says other patrons think you are a group of pickpockets.",
        "One of you sees an ex.",
        "A man hands one of you a crisp one hundred US dollar bill then disappears into the crowd.",
        "A couple making out.",
        "The bartender asks you what you are drinking.",
        "A Man asks one of you to dance.",
        "A punk with a mohawk asks one of you to play pool.",
        "A woman begins to flirt with one of you.",
        "A smartphone lying on the floor.",
        "Someone mistakes one of you for someone else and begins kissing them.",
        "Someone in the crowd throws a bottle that hits one of you.",
        "The music stops abruptly and someone announces the club is closed.",
        "A fight breaks out on the dance floor.",
        "A couple screams at each other causing a scene.",
    ],
    "oracle-advertainment-brand-result": [
        "NoLogo",
        "Matsushira",
        "Al Emaar",
        "Horizon",
        "De Santo",
        "Ellis-Itami",
        "Osprey",
        "Numan-Lloyd",
        "Modus",
        "Cortex",
    ],
    "oracle-advertainment-product-name-result": [
        "Phoenix",
        "Omni",
        "AEX",
        "Luxuria",
        "Solaris",
        "Rapide",
        "Hydra",
        "Eco+",
        "Nexus",
        "Platina",
    ],
    "oracle-advertainment-product-line-result": [
        "Cyber/Bio/Nanoware",
        "Car/Motorcycle/AV",
        "Foodstuff/Drink",
        "Clothing/lifestyle",
        "Personal Service",
        "Computing/Comms",
        "Personal Defense",
        "Pharmaceuticals",
        "Cosmetics/Scent",
        "Travel/Vacation",
    ],
    "oracle-advertainment-marketing-style-result": [
        "loud hard Sell",
        "Cartoony/Manga",
        "Sexualised",
        "Sophisticated",
        "Abstract",
        "humorous",
        "Gender Specific",
        "Cheap",
        "exotic/Arty",
        "Aspirational",
    ],
    "oracle-strange-sickness-symptoms-result": [
        "Difficulty Breathing",
        "lesions/redness/lumps",
        "Immunodeficiency",
        "lethargy/Weight loss",
        "Flaky/Spots/Blisters",
        "hair loss/Discolouration",
        "unpleasant Odour",
        "Vomiting/Diarrhea",
        "Silvery Grey emissions",
        "red Watery eyes/Painful",
    ],
    "oracle-strange-sickness-cause-result": [
        "Bad Air/Pollutants/Smoking",
        "Jankey UV levels/Toxic rain",
        "Pollutants/Chemical Soup",
        "Vitamin Deficiency/Junkfood",
        "Junkfood/Toxins",
        "Nanite Infused Air/rejection",
        "Experimental virus released on purpose",
    ],
    "oracle-conflict-group-result": [
        "Street <a href=\"/oracles/faction-oracles#street-gangs\">Gang</a>",
        "Corporate <a href=\"/oracles/character-oracles#corporate-aristocrat\">Aristocrat(s)</a>",
        "<a href=\"/oracles/character-oracles#fixer\">Fixer</a> Network",
        "<a href=\"/oracles/character-oracles#hacker\">Netrunner</a> Collective",
        "<a href=\"/oracles/character-oracles#merc\">Solo Condotta/PMC</a>",
        "Criminal Syndicate",
        "Drug Dealers",
        "Transient Clan",
        "Indentured Workers",
        "Media Web",
    ],
    "oracle-conflict-source-result": [
        "Treachery",
        "Adultery",
        "Fraud Or Theft",
        "Addiction",
        "Ambition",
        "Madness",
        "love",
        "Folly",
        "Paranoia",
        "rivalry",
        "Vengeance",
    ],
    "oracle-conflict-adversary-group-result": [
        "Street <a href=\"/oracles/faction-oracles#street-gangs\">Gang</a>",
        "Corporate <a href=\"/oracles/character-oracles#corporate-aristocrat\">Aristocrat(s)</a>",
        "<a href=\"/oracles/character-oracles#fixer\">Fixer</a> Network",
        "<a href=\"/oracles/character-oracles#hacker\">Netrunner</a> Collective",
        "<a href=\"/oracles/character-oracles#merc\">Solo Condotta/PMC</a>",
        "Criminal Syndicate",
        "Drug Dealers",
        "Transient Clan",
        "Indentured Workers",
        "Media Web",
    ],
    "oracle-terrestrial-vehicle-type-result": [
        "Armoured Intercity Bus",
        "Carbon-Fibre <a href=\"/oracles/character-oracles#cabbie\">Pedicab</a>",
        "GeV <a href=\"/oracles/character-oracles#cabbie\">Taxi</a> (Air Cushion)",
        "Automated uber/AI Taxi Sedan",
        "Food Vending Truck",
        "Cyclist(s)",
        "Police Patrol Car",
        "Small City electric",
        "limousine",
        "Sports Car",
        "HMMWV (humvee)",
        "Suburban utility Vehicle (SUV)",
        "estate Car/Stationwagon",
        "Moped/Scooter",
        "4x4/MRAP",
        "Very heavy Goods Vehicle",
        "Armoured Truck",
        "Police Van",
        "Sports Motorcycle",
        "utility Van/Minivan",
        "refrigerated Transport",
        "Off road Motorcycle",
        "Flatbed/Pick-up",
        "Tram/Metro-Train",
        "hatchback",
        "Classic Car",
        "Aero using road Wheels",
        "luxury Sedan",
        "Monowheel",
        "hazardous Container Truck",
        "Three-Wheeler",
        "Waste Management Truck",
        "Automated road Sweeper",
        "Police Motorcycle",
        "Courier/Delivery Van",
        "Scrap Built <a href=\"/oracles/character-oracles#cabbie\">rickshaw</a>",
        "Standard Sedan",
        "Mobile home/RV/MoPad",
        "Muscle Car/roadster",
        "Construction Vehicle",
        "Fire Tender",
        "Buggy/ATV",
        "Powered Armour <a href=\"/oracles/character-oracles#cabbie\">rickshaw</a> (Cradle)",
        "EMT/Paramedic/Ambulance",
        "Armoured Personnel Carrier",
        "Quad Bike",
        "Tow Truck",
        "Car/Vehicle/PA Transporter",
        "regular City Bus (1-3 decks)",
        "Trike",
    ],
    "oracle-terrestrial-vehicle-car-result": [
        [
            "Archer Hella: Sedan type, 4 seats,",
            "Archer Quartz: Sports-car, 2 seats,",
            "Chevillon Thrax: Limousine, 6 seats,",
            "Chevillon Emperor: SUV, 4 seats,",
            "Villefort Delamain: Sedan type, 4 seats,",
            "Herrera Outlaw: Sports-car, 4 seats,",
            "Makigai MaiMai: urban-type, 1 seat,",
            "Mizutani Shion: Sports-car, 2 seats,",
            "Quadra Turbo-R: Sports-car, 2 seats,",
            "Quadra Type-66: Muscle-car, 4 seats,",
            "Rayfield Caliburn: Sports-car, 2 seats,",
            "Rayfield Aerondight: Sports-car, 4 seats,",
            "Rayfield Excalibur: Luxury-AV, 4 seats,",
            "Thorton Colby: urban-type, 4 seats,",
            "Thorton Galena: urban-type, 2 seats,",
            "Thorton Mackinaw: pickup, 2 seats,",
            "Villefort Alvarado: Sedan type, 4 seats,",
            "Villefort Cortes: Sedan type, 6 seats,",
            "Villefort Columbus: Van, 6 seats,",
            "Herrera Panther: Muscle-car, 2 seats,",
            "Mizutani Vorta: Muscle-car, 4 seats,",
            "Mahir Aegis: Sedan type, 4 seats,",
        ],
        [
            "All chrome",
            "Matte black",
            "Matte white",
            "Matte orange",
            "Metallic black",
            "Metallic blue",
            "Metallic red",
            "Metallic gold",
            "Metallic white",
            "Metallic grey",
            "Pearlescent black",
            "Pearlescent white",
            "Pearlescent red",
            "Pearlescent green",
            "Pearlescent blue",
            "Pearlescent yellow",
            "Neon green",
            "Neon pink",
            "Brushed metal and Carbon fiber",
            "Brushed metal",
        ],
    ],
    "oracle-terrestrial-vehicle-activity-result": [
        "Speeding",
        "Braking hard",
        "Parking",
        "Pulling Into Traffic",
        "Overtaking",
        "Break Down",
        "Crawling",
        "Collides With another vehicle",
        "u-Turn",
        "reversing",
    ],
    "oracle-terrestrial-vehicle-feature-result": [
        "extremely loud <a href=\"/oracles/misc-oracles#music-genre--subculture-style\">music</a>",
        "Biodiesel Conversion",
        "runs Silent",
        "religious Iconography",
        "Too Many Passengers",
        "Polymorphic Coating",
        "Overloaded With Cargo",
        "excessive Bumper Stickers",
        "low rider",
        "Off road Tires",
    ],
    "oracle-terrestrial-vehicle-condition-result": [
        "More Dirt Than Paint",
        "Factory Fresh",
        "rust Bucket",
        "held Together By epoxy",
        "Well Maintained",
        "Partial respray",
        "Mobile Trashcan",
        "Burned Out engine",
        "Dents And Scratches",
        "Overtly Armoured",
    ],
    "oracle-aerial-vehicle-type-result": [
        "luxury Aero/limo",
        "utility Aero Transport",
        "Aerobus/<a href=\"/oracles/character-oracles#cabbie\">Aerocab</a>",
        "helicopter/Tilt-rotor",
        "<a href=\"/oracles/city-oracles/#advertainment\">Ad</a> Blimp",
        "Gunship (aero or chopper)",
        "Drone Cluster/UAV",
        "Police Aero",
        "Aero Sedan",
        "EMT/Paramedic Aero",
    ],
    "oracle-aerial-vehicle-activity-result": [
        "Banking",
        "Descending",
        "Ascending",
        "hovering",
        "Circling",
        "Speeding or In Pursuit of another vehicle",
        "Cruising",
        "Weaving",
        "Overtaking",
        "Clipping another vehicle",
    ],
    "oracle-aquatic-vehicle-result": [
        "A long, thin, high-powered speedboat (‘cigarette’ boat) races past",
        "An air-cushion <a href=\"/oracles/character-oracles#cabbie\">taxi</a> GEV (Ground effect Vehicle), slips down to the water",
        "A garishly illuminated party boat, packed with revellers, loud <a href=\"/oracles/misc-oracles#music-genre--subculture-style\">music</a>",
        "A quiet and unassuming modern houseboat, moored to the embankment",
        "An improvised submersible surfaces, seemingly lost, crew appear to be armed",
        "An automated cargo transport barge, weaving through traffic using GPS",
        "Clusters of detritus, plastics and thick yellow foam float on the oily surface",
        "Clearly marked security hydrofoil, slowly patrolling, HMGs and searchlights",
        "rescue Service tug, hi-vis wearing crew dredging bloated bodies from the water",
        "A local go-gang has ‘upgraded’ to tricked-out jet-skis and are causing havoc",
    ],
    "oracle-atypical-weather-result": [
        "Corrosive Fog: Stinking acidic fog enshrouds city, poor visibility and air",
        "Creep Cloud: Chemically tainted mist triggers environment monitors",
        "Acidic Monsoon: Sheets of choking, corrosive rain creates vapour columns",
        "Glitter-twist: Dead nanites carried by air columns catch light like sparks",
        "extreme UV: Burns skin (need flare-paste) and causes visibility problems",
        "Wind Tunnel: extremely tall buildings channel aggressive, lashing winds",
        "Sweltering heat: Operating in armour causes heat fatigue and dehydration",
        "Cold Snap: heavy frosts and hail create hazardous city conditions",
        "Minor Flood: So much rain with nowhere left to go causes urban chaos",
        "Lightning Storm: Spectacular electrical storm, heavy ionisation with EMP effects",
    ],
};
export default cityOracleResults;