const coreOracleResults = {
"oracle-action-result": [
    "Abandon",
    "Acquire",
    "Advance",
    "Affect",
    "Aid",
    "Arrive",
    "Assault",
    "Attack",
    "Avenge",
    "Avoid",
    "Await",
    "Begin",
    "Betray",
    "Bolster",
    "Breach",
    "Break",
    "Capture",
    "Challenge",
    "Change",
    "Charge",
    "Clash",
    "Command",
    "Communicate",
    "Construct",
    "Control",
    "Coordinate",
    "Create",
    "Debate",
    "Defeat",
    "Defend",
    "Deflect",
    "Defy",
    "Deliver",
    "Demand",
    "Depart",
    "Destroy",
    "Distract",
    "Eliminate",
    "Endure",
    "Escalate",
    "Escort",
    "Evade",
    "Explore",
    "Falter",
    "Find",
    "Finish",
    "Focus",
    "Follow",
    "Fortify",
    "Gather",
    "Guard",
    "Hide",
    "Hold",
    "Hunt",
    "Impress",
    "Initiate",
    "Inspect",
    "Investigate",
    "Journey",
    "Learn",
    "Leave",
    "Locate",
    "Lose",
    "Manipulate",
    "Mourn",
    "Move",
    "Oppose",
    "Overwhelm",
    "Persevere",
    "Preserve",
    "Protect",
    "Raid",
    "Reduce",
    "Refuse",
    "Reject",
    "Release",
    "Remove",
    "Research",
    "Resist",
    "Restore",
    "Reveal",
    "Risk",
    "Scheme",
    "Search",
    "Secure",
    "Seize",
    "Serve",
    "Share",
    "Strengthen",
    "Summon",
    "Support",
    "Suppress",
    "Surrender",
    "Swear",
    "Threaten",
    "Transform",
    "Uncover",
    "Uphold",
    "Weaken",
    "Withdraw",
],
"oracle-theme-result": [
    "Ability",
    "Advantage",
    "Alliance",
    "Authority",
    "Balance",
    "Barrier",
    "Belief",
    "Blood",
    "Bond",
    "Burden",
    "Commerce",
    "Community",
    "Corruption",
    "Creation",
    "Crime",
    "Culture",
    "Cure",
    "Danger",
    "Death",
    "Debt",
    "Decay",
    "Deception",
    "Defense",
    "Destiny",
    "Disaster",
    "Discovery",
    "Disease",
    "Dominion",
    "Dream",
    "Duty",
    "Enemy",
    "Expedition",
    "Faction",
    "Fame",
    "Family",
    "Fear",
    "Fellowship",
    "Freedom",
    "Greed",
    "Hardship",
    "Hate",
    "Health",
    "History",
    "Home",
    "Honor",
    "Hope",
    "Humanity",
    "Innocence",
    "Knowledge",
    "Labor",
    "Language",
    "Law",
    "Legacy",
    "Life",
    "Love",
    "Memory",
    "Nature",
    "Opportunity",
    "Passage",
    "Peace",
    "Phenomenon",
    "Possession",
    "Power",
    "Price",
    "Pride",
    "Prize",
    "Protection",
    "Mission",
    "Relationship",
    "Religion",
    "Reputation",
    "Resource",
    "Revenge",
    "Rival",
    "Rumor",
    "Safety",
    "Sanctuary",
    "Secret",
    "Solution",
    "Spirit",
    "Stranger",
    "Strategy",
    "Strength",
    "Superstition",
    "Supply",
    "Survival",
    "Technology",
    "Time",
    "Tool",
    "Trade",
    "Truth",
    "Vengeance",
    "Vow",
    "War",
    "Warning",
    "Weakness",
    "Wealth",
    "Weapon",
    "World",
],
"oracle-descriptor-result": [
    "Abandoned",
    "Abundant",
    "Active",
    "Advanced",
    "Ancient",
    "Archaic",
    "Automated",
    "Barren",
    "Biological",
    "Blighted",
    "Blocked",
    "Breached",
    "Broken",
    "Captured",
    "Chaotic",
    "Civilized",
    "Collapsed",
    "Colossal",
    "Confined",
    "Conspicuous",
    "Constructed",
    "Contested",
    "Corrupted",
    "Created",
    "Damaged",
    "Dead",
    "Deadly",
    "Decaying",
    "Defended",
    "Depleted",
    "Desolate",
    "Destroyed",
    "Diverse",
    "Empty",
    "Engulfed",
    "Ensnaring",
    "Exotic",
    "Expansive",
    "Exposed",
    "Fiery",
    "Foreboding",
    "Forgotten",
    "Forsaken",
    "Fortified",
    "Foul",
    "Fragile",
    "Frozen",
    "Functional",
    "Grim",
    "Guarded",
    "Hidden",
    "Hoarded",
    "Hostile",
    "Immersed",
    "Inaccessible",
    "Infested",
    "Inhabited",
    "Isolated",
    "Living",
    "Lost",
    "Lush",
    "Makeshift",
    "Mechanical",
    "Misleading",
    "Moving",
    "Mysterious",
    "Natural",
    "New",
    "Obscured",
    "Open",
    "Peaceful",
    "Perilous",
    "Pillaged",
    "Powerful",
    "Preserved",
    "Preyed",
    "Prominent",
    "Protected",
    "Radiant",
    "Rare",
    "Remote",
    "Rich",
    "Ruined",
    "Sacred",
    "Safe",
    "Sealed",
    "Secret",
    "Settled",
    "Shrouded",
    "Stolen",
    "Strange",
    "Subsurface",
    "Toxic",
    "Trapped",
    "Undiscovered",
    "Unnatural",
    "Unstable",
    "Untamed",
    "Valuable",
    "Violent",
],
"oracle-focus-result": [
    "Alarm",
    "Anomaly",
    "Apparition",
    "Archive",
    "Art",
    "Artifact",
    "Battleground",
    "Being",
    "Blockade",
    "Boundary",
    "Cache",
    "Cargo",
    "Commodity",
    "Confinement",
    "Connection",
    "Container",
    "Creation",
    "Creature",
    "Crossing",
    "Data",
    "Debris",
    "Device",
    "Dimension",
    "Discovery",
    "Drone",
    "Ecosystem",
    "Enclosure",
    "Energy",
    "Environment",
    "Equipment",
    "Experiment",
    "Facility",
    "Faction",
    "Force",
    "Fortification",
    "Gas",
    "Grave",
    "Habitat",
    "Hazard",
    "Hideaway",
    "Home",
    "Illusion",
    "Industry",
    "Junk",
    "Intelligence",
    "Lair",
    "Lifeform",
    "Liquid",
    "Machine",
    "Material",
    "Mechanism",
    "Message",
    "Mineral",
    "Monument",
    "Obstacle",
    "Organism",
    "Outbreak",
    "Outpost",
    "Path",
    "People",
    "Person",
    "Plant",
    "Portal",
    "Reality",
    "Refuge",
    "Relic",
    "Remains",
    "Rendezvous",
    "Resource",
    "Route",
    "Ruins",
    "Salvage",
    "Settlement",
    "Shelter",
    "Homebase",
    "Shortcut",
    "Signal",
    "Sound",
    "Storage",
    "Storm",
    "Structure",
    "Supply",
    "Symbol",
    "Technology",
    "Terrain",
    "Territory",
    "Threshold",
    "Time",
    "Transport",
    "Trap",
    "Treasure",
    "Vault",
    "Vehicle",
    "Viewpoint",
    "Weapon",
    "World",
    "Wreckage",
],
    "oracle-story-complication-result": [
        "Crucial equipment or device fails",
        "Crucial equipment or device is sabotaged",
        "Debt or promise comes due",
        "Enemy reveals unexpected tech, powers, abilities, or influence",
        "Enemy reveals their true agenda or nature",
        "Enemy unexpectedly benefits from your actions",
        "Key location is made inaccessible",
        "Key location is threatened or made unsafe",
        "Natural disaster is imminent",
        "Needed item or resource is unavailable",
        "Object of a quest is not what you assumed",
        "Old enemy resurfaces",
        "Simultaneous problems force a hard choice",
        "Someone important betrays your trust",
        "Someone important is threatened or endangered",
        "Someone important reveals their problematic secret or history",
        "Something important goes missing",
        "Technology or device is shown to have unexpected effects",
        "Time pressure suddenly increases",
        "Trap is sprung",
        "True agenda of a connection or patron is revealed",
        "Trusted information is shown to be false",
        "Two seemingly unrelated problems are shown to be connected",
        "Undermined by self-doubt or vulnerabilities",
        "Unexpected enemies appear",
        "Urgent message distracts you from your mission",
        "You are tracked or followed",
        "You were diverted from the true crisis",
    ],
    "oracle-story-clue-result": [
        "Affirms a previously understood fact or clue",
        "Connects to a known rumor or scandal",
        "Connects to a previously unrelated mystery or objective",
        "Connects to your own expertise or interests",
        "Contradicts a previously understood fact or clue",
        "Evokes a personal memory",
        "Evokes a remarkable anomaly or phenomenon",
        "Involves a cultural touchstone",
        "Involves a hidden or mysterious faction",
        "Involves a hidden or mysterious person",
        "Involves a key or means of access",
        "Involves a machine or technology",
        "Involves a notable faction",
        "Involves a notable person",
        "Involves a person or faction from your background",
        "Involves a personal item",
        "Involves an enemy or rival",
        "Involves an organism or biological evidence",
        "Involves someone you trust",
        "Involves something rare, expensive, or precious",
        "Leads to a distant or unfamiliar place",
        "Leads to a hidden or forgotten place",
        "Leads to a nearby or familiar place",
        "Leads to a notable or central place",
        "Suggests a history of similar incidents",
        "Suggests a looming event or deadline",
        "Suggests an imposter or forgery",
        "<a href=\"/oracles/core-oracles#descriptor\">Descriptor</a> + <a href=\"/oracles/core-oracles#focus\">Focus</a>",
    ],
};
export default coreOracleResults;