const factionOracleResults = {
    "oracle-faction-type-result": [
        "<a href=\"/oracles/faction-oracles#faction-dominion\">Dominion</a>: A governing power over a sector, planet or other sphere of influence.",
        "<a href=\"/oracles/faction-oracles#faction-guild\">Guild</a>: An organization of specialists over a particular trade.",
        "<a href=\"/oracles/faction-oracles#faction-fringegroup\">Fringe Group</a>: A band of outlaws, outcasts or rogues.",
    ],

    "oracle-faction-dominion-result": [
        "Agriculture", 
        "Artistry", 
        "Commerce", 
        "Conquest", 
        "Construction", 
        "Diplomacy", 
        "Education", 
        "Environmentalism", 
        "Exploration", 
        "Faith", 
        "History", 
        "Honor", 
        "Industry", 
        "Isolationism", 
        "Law", 
        "Mysticism", 
        "Pacifism", 
        "Prophecy", 
        "Science", 
        "Secrecy", 
        "Technology", 
        "Treachery", 
        "Warfare", 
        "Wealth", 
    ],

    "oracle-faction-dominion-leadership-result": [
        "Anarchist", 
        "Disputed leadership", 
        "Authoritarian dictatorship", 
        "Oligarchical elite", 
        "Dynastic lineage", 
        "Fated or prophesied leader", 
        "Clan chiefs or elders", 
        "Elected representatives", 
        "Machine intelligence", 
        "Varied / decentralized", 
    ],

    "oracle-faction-guild-result": [
        "Assassins", 
        "Bounty Hunters", 
        "Couriers", 
        "Courtesans", 
        "Engineers", 
        "Healers", 
        "Industrialists", 
        "Mercenaries", 
        "Merchants", 
        "Mystics", 
        "Navigators", 
        "Peacekeepers", 
        "Researchers", 
        "Spies", 
    ],

    "oracle-faction-fringegroup-result": [
        "Cultists", 
        "Exiles", 
        "Gangsters", 
        "Hackers", 
        "Monster hunters", 
        "Pirates", 
        "Raiders", 
        "Rebels", 
        "Rogue AI", 
        "Scavengers", 
        "Smugglers", 
    ],

    "oracle-faction-name-result": {
        'template': [
            "{legacy} {affiliation}",
            "{legacy} {identity}",
            "{identity} of the {legacy} {affiliation}",
            "{affiliation} of the {legacy} {identity}",
        ],
        'tables': {
            'legacy': [
                "Ancient", 
                "Ashen", 
                "Awakened", 
                "Azure", 
                "Blessed", 
                "Bloody", 
                "Broken", 
                "Ceaseless", 
                "Crimson", 
                "Cursed", 
                "Dawning", 
                "Dissident", 
                "Ebon", 
                "Elder", 
                "Enduring", 
                "Enlightened", 
                "Exalted", 
                "Fallen", 
                "Fated", 
                "First", 
                "Forgotten", 
                "Forsaken", 
                "Gloaming", 
                "Golden", 
                "Hidden", 
                "Infernal", 
                "Infinite", 
                "Iron", 
                "Kindred", 
                "Obsidian", 
                "Radiant", 
                "Risen", 
                "Sacred", 
                "Sapphire", 
                "Scarlet", 
                "Serene", 
                "Shattered", 
                "Shining", 
                "Silent", 
                "Silver", 
                "Sovereign", 
                "Stellar", 
                "Sundered", 
                "Supreme", 
                "Undying", 
                "Unified", 
                "United", 
                "Universal", 
                "Veiled", 
                "Wandering", 
            ],
            'affiliation': [
                "Accord", 
                "Alliance", 
                "Ascendancy", 
                "Circle", 
                "Coalition", 
                "Collective", 
                "Commonwealth", 
                "Confederation", 
                "Consortium", 
                "Council", 
                "Court", 
                "Covenant", 
                "Dominion", 
                "Empire", 
                "Federation", 
                "Imperium", 
                "League", 
                "Legion", 
                "Order", 
                "Pact", 
                "Regiment", 
                "Republic", 
                "Sphere", 
                "Syndicate", 
                "Union", 
            ],
            'identity': [
                "Blades", 
                "Builders", 
                "Daggers", 
                "Defenders", 
                "Disciples", 
                "Domains", 
                "Drifters", 
                "Embers", 
                "Flames", 
                "Fleet", 
                "Guardians", 
                "Hammers", 
                "Harbingers", 
                "Heralds", 
                "Hounds", 
                "Hunters", 
                "Jackals", 
                "Keepers", 
                "Knights", 
                "Menders", 
                "Outcasts", 
                "Phantoms", 
                "Planets", 
                "Raiders", 
                "Ravens", 
                "Realms", 
                "Reavers", 
                "Relics", 
                "Seekers", 
                "Sentinels", 
                "Serpents", 
                "Servants", 
                "Shadows", 
                "Shards", 
                "Skulls", 
                "Souls", 
                "Specters", 
                "Stars", 
                "Suns", 
                "Swarm", 
                "Swords", 
                "Talons", 
                "Vanguards", 
                "Wardens", 
                "Watchers", 
                "Wolves", 
                "Worlds", 
                "Wraiths", 
                "Wreckers", 
                "Wrights", 

            ],
        }
    },

    "oracle-faction-influence-result": [
        "Forsaken", 
        "Isolated", 
        "Localized", 
        "Established", 
        "Notable", 
        "Dominant", 
        "Inescapable", 
    ],

    "oracle-faction-quirk-result": [
        "Ancient or coded language", 
        "Animal or creature motif used as a faction symbol", 
        "Banishes the disloyal", 
        "Body augmentations are respected and valued", 
        "Body ornamentations signify castes or roles", 
        "Conceals individual identity", 
        "Dependent on an addictive substance", 
        "Distinctive or elaborate clothing", 
        "Elite soldiers provide defense or serve as bodyguards", 
        "Favors a signature weapon", 
        "Guided by superstition or prophecy", 
        "Heavily stratified social structure", 
        "Hoards precursor artifacts", 
        "Honors the fallen through unusual death rites", 
        "Idolizes a long-dead founder or martyr", 
        "Keeps exhaustive records or archives", 
        "Lives off-planet in spaceborne fleets", 
        "Members take a new name when joining the faction", 
        "Nomadic people and mobile operations", 
        "Operates under strict codes or laws", 
        "Recognizes others through a distinctive greeting or gesture", 
        "Reliant on machine intelligence", 
        "Resolves disputes through formal duels", 
        "Rites of adulthood or ascension", 
        "Shuns or distrusts machine intelligence", 
        "Starships share a distinctive and recognizable profile", 
        "Suspicious of outsiders", 
        "Symbiotic relationship with a specific type of creature", 
        "Trades in a unique currency or commodity", 
        "Trains in a demanding physical discipline or martial art", 
        "Wields unnatural abilities or strange technologies", 
        "Work or environment causes mutations", 
    ],

    "oracle-faction-project-result": [
        "Broaden scope of the faction to include a new focus", 
        "Build or secure a powerful device", 
        "Consolidate control of a valuable commodity", 
        "Destroy or defeat a rival", 
        "Disrupt the operations of a rival", 
        "Escape the control of another faction or power", 
        "Establish a monument or memorial", 
        "Establish a safe refuge or headquarters", 
        "Expand operations to a new location or sector", 
        "Form an alliance", 
        "Fulfill a prophecy", 
        "Give aid to a faction", 
        "Harness unnatural or forbidden power", 
        "Hunt down a rogue asset", 
        "Incite conflict among rivals", 
        "Negotiate an agreement", 
        "Obtain a needed commodity", 
        "Obtain an important cultural artifact", 
        "Obtain crucial data or information", 
        "Obtain incriminating information about a rival", 
        "Prevent a prophecy", 
        "Put down an internal revolt or rebellion", 
        "Repay a debt", 
        "Rescue or recover a group or asset", 
        "Research an innovation", 
        "Resolve a conflict with another faction", 
        "Reunite splintered elements of the faction", 
        "Seize a powerful artifact or valuable treasure", 
        "Seize rival territory or operations", 
        "Subsume another faction", 
        "Transport a valued asset", 
        "Usurp leadership within a rival faction", 
    ],

    "oracle-faction-relationship-result": [
        "Antagonistic towards...", 
        "Apathetic or unaware of...", 
        "Betrayed by...", 
        "Broke faith with...", 
        "Distrustful of...", 
        "Does business with...", 
        "Extorted by...", 
        "Holds contempt for...", 
        "Holds leverage over...", 
        "In control of...", 
        "Maneuvering against...", 
        "Needs aid from...", 
        "Negotiating with...", 
        "Open alliance with...", 
        "Owes a debt to...", 
        "Shares a rivalry with...", 
        "Shares power with...", 
        "Shows respect for...", 
        "Splintered from...", 
        "Subordinate to...", 
        "Supplied with resources by...", 
        "Supplies resources to...", 
        "Temporary alliance with...", 
        "Tolerates...", 
        "Trades favors with...", 
        "Unjustly accused by...", 
        "Warring with...", 
    ],

    "oracle-faction-rumors-result": [
        "Caught in the crossfire of feuding factions", 
        "Colluding with a criminal enterprise", 
        "Corrupted by a dangerous power", 
        "Critical resource is in short supply", 
        "Defenses are overextended", 
        "Developing revolutionary technology", 
        "Digital systems are corrupted or infiltrated", 
        "Heavily in debt", 
        "Hit hard by a recent attack or calamity", 
        "Holds a powerful artifact", 
        "Holds incriminating information against a leader or faction", 
        "Hoarding a valuable commodity", 
        "Infiltrated by a rival faction", 
        "Knows the location of a fabled treasure or lost technology", 
        "Leaders are haunted by a dark prophecy", 
        "Leaders are incompetent", 
        "Leaders are puppets of another power or faction", 
        "Lesser members of the leadership are plotting a coup", 
        "New belief or religion is creating a schism among members", 
        "Operations are a false front for their true purpose", 
        "Overdependence on a failing or vulnerable technology", 
        "Plagued by infighting and low morale", 
        "Plotting to betray an allied faction", 
        "Preparing a major offensive or operation", 
        "Pulling the strings of a leader or faction", 
        "Recently acquired an unexpected fortune", 
        "Secretly supporting a reviled faction", 
        "Sheltering an infamous or dangerous fugitive", 
        "Suffered destructive sabotage from within", 
        "Suffering a shortage of key workers or personnel", 
        "Uprising or revolt is brewing from within", 
        "Vulnerable to attack or aggression", 
    ],

    
};
export default factionOracleResults;