const factionOracleResults = {
    "oracle-faction-type-result": [
        "<a href=\"/oracles/faction-oracles#faction-interstellarsociety\">Interstellar Society</a>: A huge culture or commonality spanning multiple star systems.",
        "<a href=\"/oracles/faction-oracles#faction-dominion\">Dominion</a>: A governing power over a sector, planet or other sphere of influence.",
        "<a href=\"/oracles/faction-oracles#faction-guild\">Guild</a>: An organization of specialists over a particular trade.",
        "<a href=\"/oracles/faction-oracles#faction-fringegroup\">Fringe Group</a>: A band of outlaws, outcasts or rogues.",
    ],

    "oracle-faction-interstellarsociety-result": [
        "<i>Corporate Conglomerate</i>. A business alliance that controls resources, trade, and tech.",
        "<i>Rebel Alliance</i>. A collection of dissident groups, freedom fighters, and insurgents who oppose oppressive regimes and seek to overthrow authoritarian rule.",
        "<i>Explorers' Guild</i>. A group of adventurers, explorers, and pioneers who chart uncharted territories, seek new worlds, and uncover ancient mysteries.",
        "<i>Research Consortium</i>. A group of scientific organizations and think tanks that push the boundaries of knowledge, often with their own agendas and ethical dilemmas.",
        "<i>Mercenary Coalition</i>. Bands of mercenaries, bounty hunters, and soldiers-for-hire, organized in their navigation of allegiances based on profit.",
        "<i>Religious Order</i>. An pervasive sect or cult that holds sway over beliefs, values, and cultural practices across star systems.",
        "<i>Rogue AI Network</i>. A sentient artificial intelligence that operates independently, seeking to advance its own goals while challenging human dominance.",
        "<i>Interstellar Syndicate</i>. A criminal organization of smuggling rings that controls the black market, illicit trade, and other shadowy operations.",
        "<i>Technocratic Council</i>. Scientists, engineers, and intellectuals who wield influence through their expertise, sometimes overshadowing traditional political power.",
        "<i>Interplanetary Alliance</i>. A group of neighboring planets or star systems that unite for mutual defense, trade, and resource sharing.",
        "<i>Alien Contingent</i>. A group of one or more alien species, cooperating toward mutually beneficial ends.",
        "<i>Nomadic Fleet</i>. A vagabond fleet that deals with scarce resources and internal politics.",
        "<i>Resistance Movement</i>. A subversive group that seeks to undermine authority.",
        "<i>Mercantile Union</i>. Traders, merchants, and independent traders' associations that form a network of economic influence.",
        "<i>Terraforming Guild</i>. Specialists in altering planetary environments, seeking to colonize or exploit uninhabitable worlds for resources.",
        "<i>Shadow Cabal</i>. An elusive, clandestine organization that manipulates events from behind the scenes, according to their own enigmatic motives.",
        "<i>Protectorate</i>. An order of guardians, knights, or defenders who pledge to safeguard weaker factions or civilizations from external threats, often at great personal sacrifice.",
        "<i>Navigators' Guild</i>. An organization wielding exclusive control over transpace navigation, shaping interstellar trade, power dynamics, and information flow.",
        "<i>Disruption Matrix</i>. A decentralized network that embraces chaos and entropy, seeking to disrupt order and reshape the galaxy according to their own enigmatic motives.",
        "<i>Psionic Alliance</i>. A federation of telepaths, empaths, and psionics who foster the growth of empathy, understanding, and cooperation across star systems.",
    ],

    "oracle-faction-dominion-result": [
        "Agriculture", 
        "Artistry", 
        "Commerce", 
        "Conquest", 
        "Construction", 
        "Diplomacy", 
        "Education", 
        "Environmentalism", 
        "Exploration", 
        "Faith", 
        "History", 
        "Honor", 
        "Industry", 
        "Isolationism", 
        "Law", 
        "Mysticism", 
        "Pacifism", 
        "Prophecy", 
        "Science", 
        "Secrecy", 
        "Technology", 
        "Treachery", 
        "Warfare", 
        "Wealth", 
    ],

    "oracle-faction-dominion-leadership-result": [
        "Anarchist", 
        "Disputed leadership", 
        "Authoritarian dictatorship", 
        "Oligarchical elite", 
        "Dynastic lineage", 
        "Fated or prophesied leader", 
        "Clan chiefs or elders", 
        "Elected representatives", 
        "Machine intelligence", 
        "Varied / decentralized", 
    ],

    "oracle-faction-guild-result": [
        "Assassins", 
        "Bounty Hunters", 
        "Couriers", 
        "Courtesans", 
        "Engineers", 
        "Healers", 
        "Industrialists", 
        "Mercenaries", 
        "Merchants", 
        "Mystics", 
        "Navigators", 
        "Peacekeepers", 
        "Researchers", 
        "Spies", 
    ],

    "oracle-faction-fringegroup-result": [
        "Cultists", 
        "Exiles", 
        "Gangsters", 
        "Hackers", 
        "Monster hunters", 
        "Pirates", 
        "Raiders", 
        "Rebels", 
        "Rogue AI", 
        "Scavengers", 
        "Smugglers", 
    ],

    "oracle-faction-name-result": {
        'template': [
            "{legacy} {affiliation}",
            "{legacy} {identity}",
            "{identity} of the {legacy} {affiliation}",
            "{affiliation} of the {legacy} {identity}",
        ],
        'tables': {
            'legacy': [
                "Ancient", 
                "Ashen", 
                "Awakened", 
                "Azure", 
                "Blessed", 
                "Bloody", 
                "Broken", 
                "Ceaseless", 
                "Crimson", 
                "Cursed", 
                "Dawning", 
                "Dissident", 
                "Ebon", 
                "Elder", 
                "Enduring", 
                "Enlightened", 
                "Exalted", 
                "Fallen", 
                "Fated", 
                "First", 
                "Forgotten", 
                "Forsaken", 
                "Gloaming", 
                "Golden", 
                "Hidden", 
                "Infernal", 
                "Infinite", 
                "Iron", 
                "Kindred", 
                "Obsidian", 
                "Radiant", 
                "Risen", 
                "Sacred", 
                "Sapphire", 
                "Scarlet", 
                "Serene", 
                "Shattered", 
                "Shining", 
                "Silent", 
                "Silver", 
                "Sovereign", 
                "Stellar", 
                "Sundered", 
                "Supreme", 
                "Undying", 
                "Unified", 
                "United", 
                "Universal", 
                "Veiled", 
                "Wandering", 
            ],
            'affiliation': [
                "Accord", 
                "Alliance", 
                "Ascendancy", 
                "Circle", 
                "Coalition", 
                "Collective", 
                "Commonwealth", 
                "Confederation", 
                "Consortium", 
                "Council", 
                "Court", 
                "Covenant", 
                "Dominion", 
                "Empire", 
                "Federation", 
                "Imperium", 
                "League", 
                "Legion", 
                "Order", 
                "Pact", 
                "Regiment", 
                "Republic", 
                "Sphere", 
                "Syndicate", 
                "Union", 
            ],
            'identity': [
                "Blades", 
                "Builders", 
                "Daggers", 
                "Defenders", 
                "Disciples", 
                "Domains", 
                "Drifters", 
                "Embers", 
                "Flames", 
                "Fleet", 
                "Guardians", 
                "Hammers", 
                "Harbingers", 
                "Heralds", 
                "Hounds", 
                "Hunters", 
                "Jackals", 
                "Keepers", 
                "Knights", 
                "Menders", 
                "Outcasts", 
                "Phantoms", 
                "Planets", 
                "Raiders", 
                "Ravens", 
                "Realms", 
                "Reavers", 
                "Relics", 
                "Seekers", 
                "Sentinels", 
                "Serpents", 
                "Servants", 
                "Shadows", 
                "Shards", 
                "Skulls", 
                "Souls", 
                "Specters", 
                "Stars", 
                "Suns", 
                "Swarm", 
                "Swords", 
                "Talons", 
                "Vanguards", 
                "Wardens", 
                "Watchers", 
                "Wolves", 
                "Worlds", 
                "Wraiths", 
                "Wreckers", 
                "Wrights", 

            ],
        }
    },

    "oracle-faction-influence-result": [
        "Forsaken", 
        "Isolated", 
        "Localized", 
        "Established", 
        "Notable", 
        "Dominant", 
        "Inescapable", 
    ],

    "oracle-faction-quirk-result": [
        "Ancient or coded language", 
        "Animal or creature motif used as a faction symbol", 
        "Banishes the disloyal", 
        "Body augmentations are respected and valued", 
        "Body ornamentations signify castes or roles", 
        "Conceals individual identity", 
        "Dependent on an addictive substance", 
        "Distinctive or elaborate clothing", 
        "Elite soldiers provide defense or serve as bodyguards", 
        "Favors a signature weapon", 
        "Guided by superstition or prophecy", 
        "Heavily stratified social structure", 
        "Hoards precursor artifacts", 
        "Honors the fallen through unusual death rites", 
        "Idolizes a long-dead founder or martyr", 
        "Keeps exhaustive records or archives", 
        "Lives off-planet in spaceborne fleets", 
        "Members take a new name when joining the faction", 
        "Nomadic people and mobile operations", 
        "Operates under strict codes or laws", 
        "Recognizes others through a distinctive greeting or gesture", 
        "Reliant on machine intelligence", 
        "Resolves disputes through formal duels", 
        "Rites of adulthood or ascension", 
        "Shuns or distrusts machine intelligence", 
        "Starships share a distinctive and recognizable profile", 
        "Suspicious of outsiders", 
        "Symbiotic relationship with a specific type of creature", 
        "Trades in a unique currency or commodity", 
        "Trains in a demanding physical discipline or martial art", 
        "Wields unnatural abilities or strange technologies", 
        "Work or environment causes mutations", 
    ],

    "oracle-faction-project-result": [
        "Broaden scope of the faction to include a new focus", 
        "Build or secure a powerful device", 
        "Consolidate control of a valuable commodity", 
        "Destroy or defeat a rival", 
        "Disrupt the operations of a rival", 
        "Escape the control of another faction or power", 
        "Establish a monument or memorial", 
        "Establish a safe refuge or headquarters", 
        "Expand operations to a new location or sector", 
        "Form an alliance", 
        "Fulfill a prophecy", 
        "Give aid to a faction", 
        "Harness unnatural or forbidden power", 
        "Hunt down a rogue asset", 
        "Incite conflict among rivals", 
        "Negotiate an agreement", 
        "Obtain a needed commodity", 
        "Obtain an important cultural artifact", 
        "Obtain crucial data or information", 
        "Obtain incriminating information about a rival", 
        "Prevent a prophecy", 
        "Put down an internal revolt or rebellion", 
        "Repay a debt", 
        "Rescue or recover a group or asset", 
        "Research an innovation", 
        "Resolve a conflict with another faction", 
        "Reunite splintered elements of the faction", 
        "Seize a powerful artifact or valuable treasure", 
        "Seize rival territory or operations", 
        "Subsume another faction", 
        "Transport a valued asset", 
        "Usurp leadership within a rival faction", 
    ],

    "oracle-faction-relationship-result": [
        "Antagonistic towards...", 
        "Apathetic or unaware of...", 
        "Betrayed by...", 
        "Broke faith with...", 
        "Distrustful of...", 
        "Does business with...", 
        "Extorted by...", 
        "Holds contempt for...", 
        "Holds leverage over...", 
        "In control of...", 
        "Maneuvering against...", 
        "Needs aid from...", 
        "Negotiating with...", 
        "Open alliance with...", 
        "Owes a debt to...", 
        "Shares a rivalry with...", 
        "Shares power with...", 
        "Shows respect for...", 
        "Splintered from...", 
        "Subordinate to...", 
        "Supplied with resources by...", 
        "Supplies resources to...", 
        "Temporary alliance with...", 
        "Tolerates...", 
        "Trades favors with...", 
        "Unjustly accused by...", 
        "Warring with...", 
    ],

    "oracle-faction-rumors-result": [
        "Caught in the crossfire of feuding factions", 
        "Colluding with a criminal enterprise", 
        "Corrupted by a dangerous power", 
        "Critical resource is in short supply", 
        "Defenses are overextended", 
        "Developing revolutionary technology", 
        "Digital systems are corrupted or infiltrated", 
        "Heavily in debt", 
        "Hit hard by a recent attack or calamity", 
        "Holds a powerful artifact", 
        "Holds incriminating information against a leader or faction", 
        "Hoarding a valuable commodity", 
        "Infiltrated by a rival faction", 
        "Knows the location of a fabled treasure or lost technology", 
        "Leaders are haunted by a dark prophecy", 
        "Leaders are incompetent", 
        "Leaders are puppets of another power or faction", 
        "Lesser members of the leadership are plotting a coup", 
        "New belief or religion is creating a schism among members", 
        "Operations are a false front for their true purpose", 
        "Overdependence on a failing or vulnerable technology", 
        "Plagued by infighting and low morale", 
        "Plotting to betray an allied faction", 
        "Preparing a major offensive or operation", 
        "Pulling the strings of a leader or faction", 
        "Recently acquired an unexpected fortune", 
        "Secretly supporting a reviled faction", 
        "Sheltering an infamous or dangerous fugitive", 
        "Suffered destructive sabotage from within", 
        "Suffering a shortage of key workers or personnel", 
        "Uprising or revolt is brewing from within", 
        "Vulnerable to attack or aggression", 
    ],

    "oracle-society-techlevel-result": [
        "<i>Primitive (TL0)</i>. Reliance on basic tools, agriculture, simple craftsmanship. Hunter-gatherer or farming communities, lacking advanced machinery or complex infrastructure.",
        "<i>Pre-Industrial (TL1)</i>. Has developed basic metallurgy, animal husbandry, simple mechanical devices. May have rudimentary transportation and simple structures.",
        "<i>Industrial (TL2)</i>. Has harnessed steam power, electricity, more advanced manufacturing techniques. Urban centers, improved transportation, communication systems.",
        "<i>Spacefaring (TL3)</i>. Has achieved space travel, colonized other planets, developed advanced energy sources. Travel, resource exploitation, and space stations within home system are commonplace.",
        "<i>Interstellar (TL4)</i>. Has achieved faster-than-light travel, advanced artificial intelligence, highly advanced energy sources and other technologies. Travel between star systems is commonplace.",
        "<i>Transcendent (TL5)</i>. Has developed near-limitless energy sources, some degree of space-time manipulation, and the ability to engineer complex systems on a cosmic scale. Post-scarcity, utopian societies are within reach.",
    ],

    "oracle-society-condition-result": [
        "<i>Abandoned</i>. A disaster or catastrophe has left the society in ruins, with only remnants of its former self remaining.",
        "<i>Nascent</i>. Only recently established; some occupied areas are still under development.",
        "<i>Nascent</i>. Only recently established; some occupied areas are still under development.",
        "<i>Nascent</i>. Only recently established; some occupied areas are still under development.",
        "<i>Nascent</i>. Only recently established; some occupied areas are still under development.",
        "<i>Struggling</i>. Some shortage is limiting growth and causing stress.", 
        "<i>Struggling</i>. Some shortage is limiting growth and causing stress.", 
        "<i>Threatened</i>. Some threat poses a hazard or obstacle to the society.", 
        "<i>Threatened</i>. Some threat poses a hazard or obstacle to the society.", 
        "<i>Threatened</i>. Some threat poses a hazard or obstacle to the society.", 
        "<i>Booming</i>. Members are thriving, and neighboring societies, communities, and/or factions have taken an interest.", 
        "<i>Booming</i>. Members are thriving, and neighboring societies, communities, and/or factions have taken an interest.", 
        "<i>Booming</i>. Members are thriving, and neighboring societies, communities, and/or factions have taken an interest.", 
        "<i>Booming</i>. Members are thriving, and neighboring societies, communities, and/or factions have taken an interest.", 
        "<i>Stable</i>. Functioning and maintaining balance.", 
        "<i>Stable</i>. Functioning and maintaining balance.", 
        "<i>Stable</i>. Functioning and maintaining balance.", 
        "<i>Stable</i>. Functioning and maintaining balance.", 
        "<i>Stable</i>. Functioning and maintaining balance.", 
        "<i>Stable</i>. Functioning and maintaining balance.", 
        "<i>Overtaxed</i>. Internal and/or external demands are pushing capabilities to the limit, putting stress on members and infrastructure. An impending shortage looms.", 
        "<i>Overtaxed</i>. Internal and/or external demands are pushing capabilities to the limit, putting stress on members and infrastructure. An impending shortage looms.", 
        "<i>Overtaxed</i>. Internal and/or external demands are pushing capabilities to the limit, putting stress on members and infrastructure. An impending shortage looms.", 
        "<i>Overtaxed</i>. Internal and/or external demands are pushing capabilities to the limit, putting stress on members and infrastructure. An impending shortage looms.", 
        "<i>Breaking</i>. Systemic breakdown caused by internal and/or external stressors has occurred.", 
        "<i>Collapsing</i>. Members struggle to survive amidst severe hardship, possibly breaking into opposing factions.", 
        "<i>Post-Collapse</i>. Survivors cling together in scattered groups, scavenging and fighting over whatever scraps remain.", 
    ],

    "oracle-society-politicalsystem-result": [
        "<i>AI Dominion</i>. AI has taken control, driving local population toward its own objectives.",
        "<i>Algorithmic Autocracy</i>. Artificial intelligence systems govern according to data analysis.",
        "<i>Communalism</i>. Decisions are made by consensus, prioritzing the community’s well-being.",
        "<i>Corporatocracy</i>. One or more corporations or megacorporations control and shape policies to benefit their interests.",
        "<i>Direct Democracy</i>. Members vote directly on laws and policies.",
        "<i>Eco-Commune</i>. Members work together toward environmental harmony and sustainability, making decisions by consensus.",
        "<i>Elder Council</i>. A group of elders makes decisions for the community based on life experience.",
        "<i>Feudalism</i>. Individuals or groups with resources and power provide support and protection to those in lower positions, in return for allegiance.",
        "<i>Genocracy</i>. Power is held by individuals or groups with particular genetic traits.",
        "<i>Guildocracy</i>. Organized around agricultural, mercantile, and/or industrial pursuits, with guilds governing territory use and resource distribution.",
        "<i>Gyno/Poly/Andrarchy</i>. Political power is held by a leader of a particular gender.",
        "<i>Isolationist Enclave</i>. A self-contained society averse to external influences.",
        "<i>Meritocracy</i>. Leadership positions are filled based on individual merit and achievement.",
        "<i>Nomadic Confederation</i>. A loose alliance of nomadic groups, each with its own leader or group of leaders, united in pursuit of shared goals.",
        "<i>Plutocracy</i>. Power is held by the wealthiest individuals or families.",
        "<i>Post-Scarcity Utopia</i>. Technology has eliminated scarcity, leading to abundance, equality, and freedom to pursue creative and philosophical ideals.",
        "<i>Representative Democracy</i>. Power is held by elected representatives.",
        "<i>Syndicalist Federation</i>. Collectively governed by workers’ unions and syndicates, with an emphasis on equality and cooperation.",
        "<i>Technocracy</i>. Governed by technical experts or scientists, where decision-making is based on expertise in various fields.",
        "<i>Theocracy</i>. Religious leaders or institutions hold power, governing according to holy strictures.",
        "<i>Totalitarian Regime</i>. A single party or leader exercises complete control over all aspects of government and society."
    ],
};
export default factionOracleResults;