const miscOracleResults = {
    "oracle-combat-action-result": [
        "Block a path or cut off an objective",
        "Cause reckless damage",
        "Change weapons or tactics",
        "Compel a surrender or concession",
        "Coordinate with allies",
        "Corner, trap, or entangle",
        "Counter or reflect an attack",
        "Create a distraction",
        "Destroy something or render it useless",
        "Fall back or stand off",
        "Hide or sneak",
        "Intimidate, taunt, or frighten",
        "Leverage the advantage of a weapon or ability",
        "Leverage the terrain or surroundings",
        "Lure into a vulnerable position",
        "Make a cautious or probing attack",
        "Make a ferocious or powerful attack",
        "Make a precise or careful attack",
        "Make a sacrificial attack",
        "Make an indirect attack",
        "Move in close or grapple",
        "Nullify a system, device, or weapon",
        "Overrun a position",
        "Perform a feint or trick",
        "Press an advantage",
        "Provoke a careless response",
        "Ready a decisive action",
        "Shift the fight to a new area",
        "Summon aid or reinforcements",
        "Take cover or bolster defenses",
        "Use an unexpected weapon or ability",
        "Weaken defenses",
    ],

    "oracle-technobabble-result": [
        [
            "Secondary",
            "Multisynaptic",
            "Gluon",
            "Intermix",
            "Inverted",
            "Ionic",
            "Negative",
            "Optical",
            "Cesium",
            "Mnemonic",
            "Oxidize",
            "Aluminosilicates",
            "Gamma",
            "Subsonic",
            "Gauss",
            "Commensalism",
            "Fusion",
            "Optimal",
            "Anomalous",
            "Stabilising",
            "Disharmonic",
            "Delta",
            "Deuterium",
            "Data",
            "Neutrino",
            "Gradient",
            "Synchronized",
            "Reciprocating",
            "Cotyledon",
            "Proton",
            "Nominal",
            "Modulated",
            "Positive",
            "Parametric",
            "Atmospheric",
            "Infrared",
            "Harmonic",
            "Magnetospheric",
            "Auxiliary",
            "Rapid",
            "Neodymium",
            "Environmental",
            "Diboridium",
            "Matrix",
            "Cosmic",
            "Multitronic",
            "Extended",
            "Sub‐harmonic",
            "Particle",
            "Magnetic",
            "Biotic",
            "Temporal",
            "Space‐time",
            "Interface",
            "Tetryon",
            "Mutation",
            "System",
            "Impulse",
            "Central",
            "Ion",
            "Biome",
            "Dampening",
            "Hydrogen",
            "Passive",
            "Gravimetric",
            "Static",
            "Modified",
            "Flux",
            "Frequency",
            "Electron",
        ],
        [
            "Continuum",
            "Baryon",
            "Ecosystem",
            "Discriminator",
            "Energy",
            "Effect",
            "Emulsion",
            "Recorder",
            "Electroplate",
            "Depolarizer",
            "Conditioner",
            "Phenomenon",
            "Cell",
            "Protector",
            "Inhibitor",
            "Enhancer",
            "Device",
            "Chamber",
            "Emission",
            "Collector",
            "Conduit",
            "Deflector",
            "Aligner",
            "Structure",
            "Databanks",
            "Network",
            "Resonator",
            "Diffusor",
            "Generator",
            "Sensor",
        ]
    ],

    "oracle-rumors-result": [
        "Increased pirate activity",
        "Plague on nearby planet",
        "Massive chunk of ice spotted in space",
        "Blockaded planet looking for pilots to run the blockade",
        "Ships disappearing",
        "New planet discovered",
        "Title dispute over lands",
        "Economic recession",
        "Celebrity found dead",
        "Rare metal discovered in nearby asteroid belt",
        "New station will be built",
        "Racial tensions in colony",
        "Rare cargo shipment in sector",
        "Meteor shower in sector",
        "Derelict ship found",
        "Large passenger liner disappeared",
        "Alien tomb discovered",
        "Business feud",
        "New cult sprang up",
        "The conflict of two warring planets is about to spill over",
        "New drug on the market",
        "Terraforming gone terribly wrong",
        "New crime boss in sector",
        "Broken alliance",
        "Team of scientists needs a good pilot to observe planetary rings",
        "A planet’s young prince has been kidnapped",
        "Colony’s water supply poisoned",
        "New colony founded nearby",
        "Trade negotiations collapsing",
        "Messages without clear source received in certain sector",
        "Experimental spacecraft tests",
        "Distress signal in uncharted space",
        "Exosuit going on market",
        "Asteroid going to hit populated planet",
        "Colony infested with strange insects",
        "Illegal gambling nearby",
        "Crime boss civil war",
        "Brokered alliance",
        "Comet coming back through",
        "Slave uprising on a certain planet",
        "Ghost ship spotted",
        "New ship model released",
        "Revolution on nearby world",
        "New company charter issued",
        "Slave traders in sector",
        "Increased spaceport security on popular planet",
        "A government looking for privateers",
        "Sentient droids need help",
        "Ancient ruins discovered",
        "Planet destroyed",
        "Mutiny on slave ship",
        "Company looking for exploration team",
        "Asteroid mining operation plagued by pirates",
        "Colony ship arrived",
        "Wedding of the century",
        "Supernova threatening population of a planet",
        "Team of scientists looking for transport to distant planet",
        "Political scandal on nearby planet",
        "Shipyard workers trying to unionize",
        "Black Hole cult threatening mass suicide",
        "Mercenary unit recruiting",
        "Odd space debris",
        "A government looking for smugglers",
        "New nebula dust harvesting technology invented",
        "Heist on nearby space station",
        "Large passenger liner stolen",
        "Abandoned space station found",
        "Trading fleet looking for escorts",
        "An old spacer is telling tales of a utopian planet",
        "Colony needs new water supply",
        "Title dispute over ship",
        "Riot on prison asteroid",
        "Space circus lost a most exotic animal",
        "Colony wiped out",
        "Pirates are guarding a planet with a large force",
        "New smuggler base in sector",
        "Imp‐like creature spotted on a space station",
        "Cartel blocking several trade routes",
        "High bounty on political leader’s head",
        "Plague ship spotted",
        "Kidnappings on certain planet",
        "Terrorist group issued manifesto",
        "Distant planet’s air gives immortality",
        "Large transport ship crippled by a computer virus",
        "Popular celebrity is missing",
        "Popular band on tour in sector",
        "Distant research station issued distress signal",
        "Team of scientists need help exploring a new planet",
        "Mutiny on large trade vessel",
        "Cartel looking for smugglers",
        "High bounty on a cartel boss’s head",
        "New species discovered",
        "Space circus coming to nearby planet",
        "Salesman selling “nebula dust” with special properties",
        "War between crime bosses",
        "At the edge of charted space an alien oracle offers prophecies",
    ],

    "oracle-illegalcargo-result": [
        "Stimsticks or other nacotics",
        "Proton torpedoes",
        "Tibanna gas",
        "Explosives",
        "Prototype weapons",
        "Antique weapons",
        "Military data / plans",
        "An item that blackmails an important figure",
        "Counterfeit credits",
        "Restricted military helmets and armor",
        "Blaster rifles",
        "Fine art",
        "Droids",
        "Medicine",
        "Food",
        "Spies",
        "Political prisoners",
        "Scientists or engineers",
        "Young of an exotic creature",
        "A dangerous beast",
        "Cattle",
        "An unknown, still living person frozen in carbonite",
        "Members of enslaved species",
        "A preserved corpse",
        "Artificial organs",
        "A group of rebels/revolutionaries",
    ],

};
export default miscOracleResults;