const miscOracleResults = {
    "oracle-combat-action-result": [
        "Block a path or cut off an objective",
        "Cause reckless damage",
        "Change weapons or tactics",
        "Compel a surrender or concession",
        "Coordinate with allies",
        "Corner, trap, or entangle",
        "Counter or reflect an attack",
        "Create a distraction",
        "Destroy something or render it useless",
        "Fall back or stand off",
        "Hide or sneak",
        "Intimidate, taunt, or frighten",
        "Leverage the advantage of a weapon or ability",
        "Leverage the terrain or surroundings",
        "Lure into a vulnerable position",
        "Make a cautious or probing attack",
        "Make a ferocious or powerful attack",
        "Make a precise or careful attack",
        "Make a sacrificial attack",
        "Make an indirect attack",
        "Move in close or grapple",
        "Nullify a system, device, or weapon",
        "Overrun a position",
        "Perform a feint or trick",
        "Press an advantage",
        "Provoke a careless response",
        "Ready a decisive action",
        "Shift the fight to a new area",
        "Summon aid or reinforcements",
        "Take cover or bolster defenses",
        "Use an unexpected weapon or ability",
        "Weaken defenses",
    ],

    "oracle-technobabble-result": [
        [
            "Secondary",
            "Multisynaptic",
            "Gluon",
            "Intermix",
            "Inverted",
            "Ionic",
            "Negative",
            "Optical",
            "Cesium",
            "Mnemonic",
            "Oxidize",
            "Aluminosilicates",
            "Gamma",
            "Subsonic",
            "Gauss",
            "Commensalism",
            "Fusion",
            "Optimal",
            "Anomalous",
            "Stabilising",
            "Disharmonic",
            "Delta",
            "Deuterium",
            "Data",
            "Neutrino",
            "Gradient",
            "Synchronized",
            "Reciprocating",
            "Cotyledon",
            "Proton",
            "Nominal",
            "Modulated",
            "Positive",
            "Parametric",
            "Atmospheric",
            "Infrared",
            "Harmonic",
            "Magnetospheric",
            "Auxiliary",
            "Rapid",
            "Neodymium",
            "Environmental",
            "Diboridium",
            "Matrix",
            "Cosmic",
            "Multitronic",
            "Extended",
            "Sub‐harmonic",
            "Particle",
            "Magnetic",
            "Biotic",
            "Temporal",
            "Space‐time",
            "Interface",
            "Tetryon",
            "Mutation",
            "System",
            "Impulse",
            "Central",
            "Ion",
            "Biome",
            "Dampening",
            "Hydrogen",
            "Passive",
            "Gravimetric",
            "Static",
            "Modified",
            "Flux",
            "Frequency",
            "Electron",
        ],
        [
            "Continuum",
            "Baryon",
            "Ecosystem",
            "Discriminator",
            "Energy",
            "Effect",
            "Emulsion",
            "Recorder",
            "Electroplate",
            "Depolarizer",
            "Conditioner",
            "Phenomenon",
            "Cell",
            "Protector",
            "Inhibitor",
            "Enhancer",
            "Device",
            "Chamber",
            "Emission",
            "Collector",
            "Conduit",
            "Deflector",
            "Aligner",
            "Structure",
            "Databanks",
            "Network",
            "Resonator",
            "Diffusor",
            "Generator",
            "Sensor",
        ]
    ],

    "oracle-rumors-result": [
        "Increased pirate activity",
        "Plague on nearby planet",
        "Massive chunk of ice spotted in space",
        "Blockaded planet looking for pilots to run the blockade",
        "Ships disappearing",
        "New planet discovered",
        "Title dispute over lands",
        "Economic recession",
        "Celebrity found dead",
        "Rare metal discovered in nearby asteroid belt",
        "New station will be built",
        "Racial tensions in colony",
        "Rare cargo shipment in sector",
        "Meteor shower in sector",
        "Derelict ship found",
        "Large passenger liner disappeared",
        "Alien tomb discovered",
        "Business feud",
        "New cult sprang up",
        "The conflict of two warring planets is about to spill over",
        "New drug on the market",
        "Terraforming gone terribly wrong",
        "New crime boss in sector",
        "Broken alliance",
        "Team of scientists needs a good pilot to observe planetary rings",
        "A planet’s young prince has been kidnapped",
        "Colony’s water supply poisoned",
        "New colony founded nearby",
        "Trade negotiations collapsing",
        "Messages without clear source received in certain sector",
        "Experimental spacecraft tests",
        "Distress signal in uncharted space",
        "Exosuit going on market",
        "Asteroid going to hit populated planet",
        "Colony infested with strange insects",
        "Illegal gambling nearby",
        "Crime boss civil war",
        "Brokered alliance",
        "Comet coming back through",
        "Slave uprising on a certain planet",
        "Ghost ship spotted",
        "New ship model released",
        "Revolution on nearby world",
        "New company charter issued",
        "Slave traders in sector",
        "Increased spaceport security on popular planet",
        "A government looking for privateers",
        "Sentient droids need help",
        "Ancient ruins discovered",
        "Planet destroyed",
        "Mutiny on slave ship",
        "Company looking for exploration team",
        "Asteroid mining operation plagued by pirates",
        "Colony ship arrived",
        "Wedding of the century",
        "Supernova threatening population of a planet",
        "Team of scientists looking for transport to distant planet",
        "Political scandal on nearby planet",
        "Shipyard workers trying to unionize",
        "Black Hole cult threatening mass suicide",
        "Mercenary unit recruiting",
        "Odd space debris",
        "A government looking for smugglers",
        "New nebula dust harvesting technology invented",
        "Heist on nearby space station",
        "Large passenger liner stolen",
        "Abandoned space station found",
        "Trading fleet looking for escorts",
        "An old spacer is telling tales of a utopian planet",
        "Colony needs new water supply",
        "Title dispute over ship",
        "Riot on prison asteroid",
        "Space circus lost a most exotic animal",
        "Colony wiped out",
        "Pirates are guarding a planet with a large force",
        "New smuggler base in sector",
        "Imp‐like creature spotted on a space station",
        "Cartel blocking several trade routes",
        "High bounty on political leader’s head",
        "Plague ship spotted",
        "Kidnappings on certain planet",
        "Terrorist group issued manifesto",
        "Distant planet’s air gives immortality",
        "Large transport ship crippled by a computer virus",
        "Popular celebrity is missing",
        "Popular band on tour in sector",
        "Distant research station issued distress signal",
        "Team of scientists need help exploring a new planet",
        "Mutiny on large trade vessel",
        "Cartel looking for smugglers",
        "High bounty on a cartel boss’s head",
        "New species discovered",
        "Space circus coming to nearby planet",
        "Salesman selling “nebula dust” with special properties",
        "War between crime bosses",
        "At the edge of charted space an alien oracle offers prophecies",
    ],

    "oracle-illegalcargo-result": [
        "Lots of crates of [<a href=\"/oracles/misc-oracles#resources\">Resource</a>].",
        "Huge shipment of [<a href=\"/oracles/misc-oracles#resources\">Resource</a>].",
        "Small crate full of [<a href=\"/oracles/misc-oracles#resources\">Resource</a>].",
        "Hidden stash of stolen [<a href=\"/oracles/misc-oracles#resources\">Resource</a>].",
        "Stimsticks or other nacotics",
        "Proton torpedoes",
        "Tibanna gas",
        "Explosives",
        "Prototype weapons",
        "Antique weapons",
        "Military data / plans",
        "An item that blackmails an important figure",
        "Counterfeit credits",
        "Restricted military helmets and armor",
        "Blaster rifles",
        "Fine art",
        "Droids",
        "Medicine",
        "Food",
        "Spies",
        "Political prisoners",
        "Scientists or engineers",
        "Young of an exotic creature",
        "A dangerous beast",
        "Cattle",
        "An unknown, still living person frozen/in stasis",
        "Members of enslaved species",
        "A preserved corpse",
        "Artificial organs",
        "A group of rebels/revolutionaries",
    ],

    "oracle-background-story-result": [
        "<i>Cosmic Cold War</i>. The balance of power between interstellar factions is delicate, setting the stage for political intrigue and espionage. PCs might be diplomats, spies, saboteurs.",
        "<i>Rebellion!</i> Discontent with interstellar authority has boiled over into uprisings across subjugated worlds. PCs might be resistance fighters, revolutionaries.",
        "<i>Trade War</i>. Mercantile conglomerates and megacorporations are vying for supremacy. PCs might be free traders, mercenaries hired for protection, or pirates on the hunt.",
        "<i>Age of Piracy</i>. Freebooters and raiders run rampant across insufficiently protected systems. PCs might be law enforcement, bounty hunters, or pirates themselves.",
        "<i>Space Plague</i>. A mysterious disease has broken out across multiple worlds, leaving devastation in its wake. PCs might be seeking the source and cure, or merely struggling to survive in the face of its destructive power.",
        "<i>Wild Frontier</i>. New colonies are being established on outlying worlds. PCs might be pioneers, frontier traders, or explorers using the frontier as a base of operations.",
        "<i>Unchecked AI</i>. Rogue artificial intelligence has taken control of a key world or installation and is expand its influence outward. PCs might be scientists or hackers tasked with neutralizing the threat.",
        "<i>Anomaly Swarm</i>. Inexplicable disruptions in the fabric of spacetime are on the rise, disrupting order across multiple systems. PCs might be scientists seeking to understand and solve the problem, or refugees escaping from it.",
        "<i>Alien Invasion!</i> A previously unknown species from beyond the known worlds has arrived in force. PCs might be soldiers, mercenaries, or people just trying to survive.",
        "<i>Galactic Conflict</i>. Two interstellar factions are at war. PCs might be soldiers or spies working for one side, or rogues and scoundrels looking to capitalize on the chaos.",
        "<i>Interstellar Cartel</i>. A coalition of criminal syndicates exerts control over trade routes and governments, forcing various star systems into dependency or opposition. PCs might be criminals themselves, fighting back against the cartel, or just trying to get by.",
        "<i>Age of Discovery</i>. A wormhole has opened near a populated system, creating a connection to a distant sector or even galaxy. PCs might be explorers or fortune hunters.",
        "<i>Gold Rush</i>. A huge, rich planet has been discovered at the edge of known space, and people are flocking to it. PCs might be explorers, surveyors, or corporate agents.",
        "<i>Dark Matter Disruption</i>. The presence of enigmatic dark matter anomalies disrupts space travel and communication, leading to isolated systems. PCs might be couriers, traders, or samaritans seeking to maintain intra-system connections.",
        "<i>First Contact</i>. Established interstellar factions have met a new culture for the first time, and the galaxy promises to never be the same. PCs might be scientists or diplomats.",
        "<i>Post-Apocalyptic Fragmentation</i>. Interstellar society has collapsed, resulting in isolated colonies and city-states vying for resources. PCs might be couriers, traders, mercenaries, drifters, or merely struggling to survive in a harsh galaxy.",
    ],

    "oracle-resources-result": [
        "<i>Helium-3</i>. Found in gas giants and the regolith of celestial bodies. Used in advanced fusion reactors for clean and efficient energy production. Extracted via advanced mining and processing techniques.",
        "<i>Hydrocarbons</i>. Found in underground reservoirs, porous rock formations, sedimentary seams. Used for fuel, electricity generation, and raw material for chemical synthesis. Extracted via drilling or mining. Examples: Crude oil, natural gas, coal.",
        "<i><a href=\"/oracles/misc-oracles#resources-mineralore\">Mineral Ores</a></i>. Found in the crust of rocky planets, moons, and asteroids, ranging from small veins to large subsurface formations. Used in construction and fabrication. Extracted via mining.",
        "<i><a href=\"/oracles/misc-oracles#resources-organiccompound\">Organic Compounds</a></i>. Found on planetary bodies where life is (or once was) present; in gaseous, liquid, or solid form; within extant lifeforms, sediments, or as fossilized organic matter. Used in the production of plastics, chemicals, and pharmaceuticals. Extracted via various means depending on form.",
        "<i><a href=\"/oracles/misc-oracles#resources-preciousmaterial\">Precious Materials</a></i>. Found in planetary regolith or crust. Used in currency, jewelry, and electronics. Extracted via mining and chemical processes.",
        "<i><a href=\"/oracles/misc-oracles#resources-rareelementsreal\">Rare Elements</a></i>. Found in trace amounts within ores and minerals in planetary crust. Used for advanced electronics, spacecraft components, energy production, and esoteric projects. Extracted via complex chemical processes.",
        "<i><a href=\"/oracles/misc-oracles#resources-rareelementsscifi\">Extra-rare Elements</a></i>. Found in trace amounts within ores and minerals in planetary crust. Used for advanced electronics, spacecraft components, energy production, and esoteric projects. Extracted via complex chemical processes.",
        "<i>Salt Deposits</i>. Found in salt flats, salt pans, and subsurface layers. Used for preserving food, water purification, and industrial chemical processes. Extracted via mining or evaporation. Examples: sodium chloride, halite.",
        "<i>Silicates</i>. Found as significant portion of planetary crust, often visible in rocky landscapes. Used as a component in glass, ceramics, construction, electronics, silicon chips. Extracted via mining. Examples: sand, quartz, feldspar.",
        "<i>Water Ice</i>. Found in polar ice caps, glaciers, frozen bodies of water, subsurface layers of permafrost. Used for hydration, agriculture, source of hydrogen for fusion reactors. Extracted via mining.",
    ],

    "oracle-resources-mineralore-result": [
        "Iron",
        "Bauxite",
        "Copper",
        "Lead",
        "Zinc",
        "Nickel",
        "Tin",
        "Titanium",
        "Uranium",
        "Chromium",
        "Manganese",
        "Cobalt",
        "Tungsten",
        "Molybdenum",
        "Antimony",
        "Vanadium",
    ],

    "oracle-resources-preciousmaterial-result": [
        "Silver",
        "Gold",
        "Platinum",
        "Palladium",
        "Iridium",
        "Garnet",
        "Opal",
        "Citrine",
        "Aquamarine",
        "Topaz",
        "Amethyst",
        "Ruby",
        "Emerald",
        "Sapphire",
        "Diamond",
    ],

    "oracle-resources-organiccompound-result": [
        "Chitin",
        "Terpenes",
        "Pigments",
        "Tannins",
        "Resins",
        "Flavonoids",
        "Volatile oils",
        "Steroids",
        "Glycosides",
        "Saponins",
        "Alkaloids",
        "Lignin",
        "Iridoids",
        "Mycotoxins",
        "Cytokines",
    ],

    "oracle-resources-rareelementsreal-result": [
        "Lanthanum (La)",
        "Cadmium (Cd)",
        "Samarium (Sm)",
        "Strontium (Sr)",
        "Indium (In)",
        "Tellurium (Te)",
        "Yttrium (Y)",
        "Neodymium (Nd)",
        "Thallium (Tl)",
        "Bismuth (Bi)",
        "Gallium (Ga)",
        "Hafnium (Hf)",
        "Rhenium (Re)",
        "Promethium (Pm)",
        "Tantalum (Ta)",
    ],
    
    "oracle-resources-rareelementsscifi-result": [
        "<i>Aquadium</i>. Ultra-hydrophobic.",
        "<i>Armisite</i>. Ultra-hard, used for armor plating.",
        "<i>Chronite</i>. Used in time manipulation tech.",
        "<i>Magnidite</i>. Used for magentic propulsion.",
        "<i>Echonite</i>. Amplifies telepathic energy.",
        "<i>Hadesium</i>. Superheat-absorbing.",
        "<i>Harmonium</i>. Harmonic/vibrational properties.",
        "<i>Matrixium</i>. Grows crystalline data storage matrices.",
        "<i>Nebulium</i>. Used for advanced cloaking technology.",
        "<i>Phasium</i>. Permits phase-shifting, matter disruption.",
        "<i>Fulgurite</i>. Hyperconductive.",
        "<i>Pyrothium</i>. Highly flammable, used for propellant.",
        "<i>Selenite</i>. Used in advanced medical technologies.",
        "<i>Serpentium</i>. Radiation-absorbing.",
        "<i>Thermagold</i>. Superheat-resistant.",
        "<i>Xenite</i>. Superdense, used for energy storage.",
    ],

    "oracle-episode-title-result": {
        'template': [
            "The {verb} of {name}",
            "The {verb} of the {adjective} {noun}",
            "The {adjective} {noun}",
            "The {noun} of {adjective} {name}",
            "The {noun} of {name}",

        ],
        'tables': {
            'verb': [
                "Return",
                "Revenge",
                "Rescue",
                "Fall",
                "Rise",
                "Search",
                "Escape",
                "Destruction",
                "Discovery",
                "Defeat",
                "Conquest",
            ],
            'name': [
                "Arrakeen",
                "Mardok",
                "Thalos",
                "Karnak",
                "Zarathos",
                "Vannan",
                "Gna-Tall",
                "Azenis",
                "Arcturus",
                "Wolf",
                "Kilrah",
                "Algol",
                "Barnhardt",
                "Altair",
                "Sirius",
                "Cinnibar",
                "Luyten",
                "Ishtar",
                "Ishar",
                "Alpha Centauri",
                "Proxima Centauri",
                "Betelgeuse",
                "Rigel",
                "Hyperion",
                "Aldebaran",
            ],
            'adjective': [
                "Lost",
                "Forgotten",
                "Hidden",
                "Ancient",
                "Mysterious",
                "Forbidden",
                "Legendary",
                "Epic",
                "Final",
                "Secret",
                "Dark",
                "Fateful",
                "Unseen",
                "Unknown",
                "Phantasmal",
                "Cosmic",
                "Vanishing",
                "Undersea",
                "Aquatic",
                "Scorching",
                "Frozen",
                "Molten",
                "Red",
                "Crimson",
                "Blue",
                "Green",
                "Black",
                "White",
                "Golden",
                "Silver",
                "Azure",
                "Emerald",
                "Obsidian",
                "Radiant",
                "Purple",
                "Invisible",
                "Floating",
                "Bright",
                "Shining",
                "Glowing",
            ],
            'noun': [
                "Discovery",
                "Revelation",
                "Destruction",
                "Rebirth",
                "Conquest",
                "Legacy",
                "Destiny",
                "Fate",
                "Quest",
                "Journey",
                "Battle",
                "Whispers",
                "Echoes",
                "Shadows",
                "Legends",
                "Tales",
                "Chronicles",
                "Fables",
                "Myths",
                "Stories",
                "Sagas",
                "City",
                "Planet",
                "World",
                "Star",
                "Galaxy",
                "Empire",
                "Shadow",
                "Sector",
                "Frontier",
                "Kingdom",
                "Realm",
                "Giants",
                "Titans",
                "Creature",
                "Creatures",
                "Monster",
                "Monsters",
                "Beast",
                "Beasts",
                "Universe",
                "Void",
                "Space",
                "Time",
                "Space-Time",
                "Skies",
                "Sky",
                "Ghost",
                "Ghosts",
                "Spectre",
                "King",
                "Queen",
                "Asteroid",
                "Comet",
                "Station",
                "Ship",
                "Fleet",
                "Starship",
                "Vessel",
                "Outpost",
                "Nebula",
                "Nebulae",
                "Base",
                "Men",
                "Women",
                "People",
                "Survivors",
                "Survivor",
                "Denizens",
                "Moon",
                "Atmosphere",
                "Girl",
                "Woman",

            ],
        }
    },

};
export default miscOracleResults;