const missionOracleResults = {
    "oracle-mission-type-result": [
        "Reconnaissance", 
        "Slice", 
        "Steal", 
        "Copy", 
        "Replace", 
        "Navigate", 
        "Destroy", 
        "Sabotage", 
        "Infiltrate", 
        "Impersonate", 
        "Assassinate", 
        "Defect", 
        "Protect", 
        "Escort", 
        "Defend", 
        "Fortify", 
        "Exfiltrate", 
        "Rescue", 
        "Raid", 
        "Falsify", 
        "Misdirect", 
        "Smuggle", 
        "Trailblaze", 
        "Coerce", 
        "Charm", 
        "Negotiate", 
        "Deceive", 
        "Deliver", 
        "Investigate", 
        "Kidnap", 
        "Blackmail", 
        "Persuade", 
        "Double-Cross", 
        "Counterfeit", 
        "Spy", 
        "Counter-spy", 
    ],

    "oracle-mission-objective-result": [
        "Plans", 
        "Blueprints", 
        "Navigation Records", 
        "Spice", 
        "Access Codes", 
        "Local Government Leader", 
        "Intelligence Officer", 
        "General/Admiral", 
        "Ancient Artifact", 
        "Local Hero", 
        "Credits", 
        "Weapons", 
        "Smuggler Baron", 
        "Business Leader", 
        "Holo Drama Actor", 
        "Experimental Ship", 
        "Experimental Weapon", 
        "City", 
        "Experimental Droid", 
        "Map", 
        "Senator", 
        "Depot", 
        "Base", 
        "Outpost", 
        "Legal Documents", 
        "Message", 
        "Valuable Artifact", 
        "Informant", 
        "Property Deed", 
        "Vehicle Deed", 
        "Hidden Location", 
        "Natural Resource", 
    ],

    "oracle-mission-client-result": [
        "Local Politician", 
        "Corporate (manufacturing)", 
        "Corporate (mining)", 
        "Corporate (technology)", 
        "Merchant or Trader", 
        "Oppressed Cult", 
        "Scholar or Academy", 
        "Criminal Syndicate", 
        "It’s Your Idea!", 
        "A Community in Need", 
        "Rebel Alliance or Revolutionary faction (local cell)", 
        "Rebel Alliance or Revolutionary faction (Command)", 
        "Old Friend or Loved One", 
        "Imperial/Republic/Federation Military", 
        "Pirates", 
        "Desperate Rival or Enemy", 
        "Planetary Governor", 
        "Imperial/Republic/Federation Intelligence", 
    ],

};
export default missionOracleResults;