const spaceOracleResults = {
  "oracle-space-sighting-result": [
    "<a href=\"/oracles/space-oracles#star\">Star</a>",
    "<a href=\"/oracles/space-oracles#celestial-phenomena\">Celestial Phenomena</a>",
    "<a href=\"/oracles/space-oracles#debris-field\">Debris Field</a>",
    "<a href=\"/oracles/planet-oracles\">Planet</a>",
    "<a href=\"/oracles/space-oracles#space-settlements\">Settlement</a>",
    "<a href=\"/oracles/space-oracles#starships\">Starship</a>",
    "<a href=\"/oracles/space-oracles#derelicts\">Derelict</a>",
    "<a href=\"/oracles/character-oracles#creatures\">Creature</a>",
    "<a href=\"/oracles/core-oracles#descriptor\">Descriptor + Focus</a>",
  ],

  "oracle-star-result": [
    "Smoldering Red Star",
    "Smoldering Red Star",
    "Smoldering Red Star",
    "Glowing Orange Star",
    "Glowing Orange Star",
    "Glowing Orange Star",
    "Glowing Orange Star",
    "Glowing Orange Star",
    "Glowing Orange Star",
    "Glowing Orange Star",
    "Glowing Orange Star",
    "Burning yellow star",
    "Burning yellow star",
    "Burning yellow star",
    "Burning yellow star",
    "Burning yellow star",
    "Burning yellow star",
    "Blazing blue star",
    "Blazing blue star",
    "Blazing blue star",
    "White dwarf shining with spectral light",
    "White dwarf shining with spectral light",
    "White dwarf shining with spectral light",
    "Two Red Stars orbiting far from each other",
    "Two Red Stars orbiting far from each other",
    "Two stars in close orbit connected by fiery tendrils of energy",
    "Two stars in close orbit connected by fiery tendrils of energy",
    "Young star incubating in a molecular cloud",
    "Corrupted star radiating with unnatural light",
    "Neutron star surrounded by intense magnetic fields",
    "Hypergiant star generating turbulent solar winds",
    "Artificial star constructed by a long-dead civilization",
    "Unstable star showing signs of impending supernova",

  ],

  "oracle-celestial-phenomena-result": [
    "<i>Large Rogue Asteroid</i>. A massive asteroid drifting through space, potentially rich in minerals.",
    "<i>Comet with a Tail of Ionized Gas</i>. A comet composed of ice and dust, emitting a bright tail as it approaches a star.",
    "<i>Fiery Energy Storm</i>. A violent storm of plasma and radiation, posing a threat to nearby spacecraft.",
    "<i>Chaotic Meteoroid Storm</i>. A dense field of meteoroids, making navigation treacherous.",
    "<i>Turbulent Gravitational Wave</i>. A ripple in spacetime caused by massive celestial events, affecting nearby objects.",
    "<i>Dense Nebula Cloud</i>. A thick cloud of gas and dust, obscuring visibility and navigation.",
    "<i>Small Black Hole</i>. A region of spacetime exhibiting gravitational acceleration so strong that nothing can escape from it.",
    "<i>Supermassive Black Hole</i>. A black hole with a mass equivalent to millions or billions of suns.",
    "<i>Emission Nebula</i>. A cloud of ionized gas that emits light of various colors.",
    "<i>Reflection Nebula</i>. A dust cloud that reflects the light of nearby stars.",
    "<i>Dark Nebula</i>. A dense cloud of gas and dust that obscures the light from stars and background objects, creating dark patches that may interfere with navigation.",
    "<i>Planetary Nebula</i>. A shell of gas and dust ejected by a dying star in its red giant phase.",
    "<i>Supernova Remnant</i>. An expanding shell of gas and debris left behind after a supernova.",
    "<i>Pulsar</i>. A highly magnetized rotating neutron star that emits beams of electromagnetic radiation.",
    "<i>Ionic Nebula</i>. A region of ionized hydrogen gas, notable for its vibrant colors.",
    "<i>Protoplanetary Nebula</i>. A short-lived phase in the evolution of a star where a dusty envelope surrounds it, potentially giving birth to planets.",
    "<i>Astrophage Nebula</i>. A nebula of enigmatic organisms that feed on cosmic radiation.",
    "<i>Giant Molecular Cloud</i>. A large, dense region of gas and dust where new stars form, often containing multiple nebulae.",
    "<i>Supergiant Shell Nebula</i>. A vast shell of gas and dust created by the explosions of massive stars, shaping the surroundings.",
  ],

  "oracle-debris-field-result": [
    "Rocky Asteroids",
    "Frozen Asteroids (water ice)",
    "Resource-rich Asteroids (rare metals)",
    "Resource-rich Asteroids (exotic minerals)",
    "Resource-rich Asteroids (rare elements)",
    "Hollowed-out Asteroids",
    "Creature Boneyard",
    "Metallic Wreckage",
  ],

  "oracle-sector-name-result": [
    [
      "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", 
      "Alpha",
      "Beta",
      "Gamma",
      "Ceti",
      "Picon",
      "Delta",
      "Epsilon",
      "Theta",
      "Zeta",
      "Omega",
      "Tau",
      "Nebulon",
      "Far",
      "Deep",
      "Omicron",
      "Sigma",
      "Kappa",
      "Rho",
      "Minor",
      "Major",
      "Greater",
      Math.floor(Math.random() * 300),
    ],
    [
      "Arfell",
      "Aeron",
      "Andromeda",
      "Apius",
      "Aquarius",
      "Ara",
      "Alcor",
      "Algol",
      "Antares",
      "Basri",
      "Behram",
      "Picoris",
      "Boötes",
      "Cancri",
      "Canes Venatici",
      "Canis",
      "Capricorn",
      "Cassiopeia",
      "Castor",
      "Cebus",
      "Centaurus",
      "Ceti",
      "Cetus",
      "Coma Berenices",
      "Corona Borealis",
      "Corot",
      "Cygnus",
      "Cygni",
      "Draco",
      "Eridanus",
      "Eridanus",
      "Fiken",
      "Fornax",
      "Fomalhaut",
      "Gilese",
      "Goddard",
      "Hercules",
      "Herculis",
      "Horologium",
      "Holbrook",
      "Hydra",
      "Hydrus",
      "Leo",
      "Leonis",
      "Libra",
      "Librae",
      "Lupus",
      "Luyten",
      "Lyra",
      "Mensa",
      "Mensae",
      "Monocerus",
      "Orion",
      "Pavol",
      "Pi Mensae",
      "Pictor",
      "Puppis",
      "Raleigh",
      "Reticulum",
      "Regulus",
      "Rho",
      "Rose",
      "Rouse",
      "Sagittarius",
      "Scorpius",
      "Serpens",
      "Sextan",
      "Spica",
      "Tau Geminorum",
      "Triangulum",
      "Tucana",
      "Tyson",
      "Upsilon",
      "Andromedae",
      "Ursa",
      "Ursae Majoris",
      "Vela",
      "Virgo",
      "Wasp",
      "Procyon",
      "Vorach",
      "Vorash",
      "Tobin",
      "Adara",
      "Doranda",
      "Herschel",
      "Huygens",
      "Canonis",
      "Samos",
      "Laplace",
      "Bell",
      "Penzias",
      "Payne",
      "Rees",
      "Burbidge",
      "Flamsteed",
      "Couper",
      "Marsden",
      "Gill",
      "Chandra",
      "Chanis",
      "Chung",
      "Narlikar",
      "Gupta",
      "Somayaji",
      "Bappu",
      "Ball",
      "Saha",
      "Das Gupta",
      "Lalla",
      "Jani",
      "Natarajan",
      "Fairall",
      "Knox",
      "Weiss",
      "Wilker",
      "Evans",
      "Dilhan",
      "Eryurt",
    ],
    [
      "Expanse",
      "Expanse",
      "Expanse",
      "Nebula",
      "Nebula",
      "Stellar Cumulus",
      "Passage",
      "Pass",
      "Space",
      "Sector",
      "Sector",
      "Sector",
      "Zone",
      "Zone",
      "Region",
      "Region",
      "Quadrant",
      "Quadrant",
      "Territory",
      "Belt",
      "Field",
      "Section",
      "Vicinity",
      "Proximity",
      "Cluster",
      "Cluster",
      "Spiral",
      "Halo Zone",
      "Coronal Stream",
      "Pulsar System",
      "Cloud Node",
      "Supercluster",
      "Vortex",
      "Star System",
      "Cluster System",
      Math.floor(Math.random() * 350) + " System",
    ],
  ],
  "oracle-sector-details-result": [
    [
      "Settled Sector with ",
      "Settled Sector with ",
      "Settled Sector with ",
      "Isolated Sector with ",
      "Isolated Sector with ",
      "Isolated Sector with ",
      "Populated Sector with ",
      "Deserted Sector with ",
      "Uninhabited Sector with ",
    ],
    [
      "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15",
    ],
    [
      "Star systems and ",
    ],
    [
      "no Hyperspace-lanes close-by",
      "no Hyperspace-lanes close-by",
      "no Hyperspace-lanes close-by",
      "1 Hyperspace-lane close-by",
      "1 Hyperspace-lane close-by",
      "1 Hyperspace-lane close-by",
      "1 Hyperspace-lane close-by",
      "1 Hyperspace-lane close-by",
      "2 Hyperspace-lanes close-by",
      "2 Hyperspace-lanes close-by",
      "3 Hyperspace-lanes close-by",
    ],
  ],

  "oracle-starsystem-details-result": [
    [
      "Single Star System,",
      "Single Star System,",
      "Single Star System,",
      "Single Star System,",
      "Single Star System,",
      "Single Star System,",
      "Binary Star System,",
      "Binary Star System,",
      "Binary Star System,",
      "Trinary Star System,",
    ],
    [
      "2", "3", "4", "5", "6", "7", "8", "9",
    ],
    [
      "Rocky <a href=\"/oracles/planet-oracles\">Planets</a>, ",
    ],
    [
      "2", "3", "4", "5",
    ],
    [
      "<a href=\"/oracles/planet-oracles#jovian-world\">Gas Giants</a> and",
    ],
    [
      "an Asteroid Belt",
      "an Asteroid Belt",
      "an Asteroid Belt",
      "an Asteroid Belt",
      "an Asteroid Belt",
      "an Asteroid Belt",
      "a Nebula-like gas cloud",
      "a Nebula-like gas cloud",
      "a Nebula-like gas cloud",
      "a Deep-space station",
      "a Deep-space station",
      "a cluster of space-habitats",
    ],
  ],

  "oracle-settlement-name-result": [
    "Aegis",
    "Altair",
    "Altura",
    "Amity",
    "Apex",
    "Apogee",
    "Argosy",
    "Astra",
    "Aurora",
    "Beacon",
    "Brink",
    "Bulwark",
    "Burnell",
    "Burrow",
    "Concord",
    "Crux",
    "Deadrock",
    "Deception",
    "Elysium",
    "Enigma",
    "Erebus",
    "Eris",
    "Evenfall",
    "Eventide",
    "Farpoint",
    "Felicity",
    "Florin",
    "Forlorn",
    "Forsaken",
    "Freya",
    "Glimmer",
    "Gloam",
    "Hearth",
    "Helia",
    "Hypatia",
    "Hyperion",
    "Janus",
    "Karma",
    "Kepler",
    "Koshiba",
    "Lagrange",
    "Larissa",
    "Lasthope",
    "Lastport",
    "Legacy",
    "Lodestar",
    "Luminus",
    "Lyra",
    "Marrow",
    "Meridian",
    "Moirai",
    "Mudd",
    "Neoma",
    "Nerio",
    "Nova",
    "Nyx",
    "Osseus",
    "Paradox",
    "Paragon",
    "Paxton",
    "Perchance",
    "Pinnacle",
    "Polaris",
    "Portent",
    "Prism",
    "Providence",
    "Purgatory",
    "Rampart",
    "Ramshackle",
    "Redemption",
    "Redhaven",
    "Relic",
    "Reprise",
    "Reverie",
    "Rhiannon",
    "Rockhome",
    "Rust",
    "Sagan",
    "Sanctity",
    "Selena",
    "Sepulcher",
    "Sigil",
    "Silvana",
    "Sirius",
    "Sisyphus",
    "Solitude",
    "Spire",
    "Starfall",
    "Summit",
    "Tranquility",
    "Tyson",
    "Unity",
    "Utopia",
    "Vega",
    "Vesper",
    "Wayward",
    "Welkin",
    "Wellspring",
    "Weyland",
    "Wreck",
    "Miasmis", 
    "Dredge", 
    "Rikajima", 
    "Nautisgrad", 
    "Kakoyama", 
    "The Singularity", 
    "Kikkidon", 
    "Harmonil", 
    "Bolham", 
    "Discori", 
    "The Pulpit", 
    "Kōjōta", 
    "Nebula", 
    "Honorsgrad", 
    "Sensōtani", 
    "The Hermitage", 
    "Harmonil", 
    "Icestadt", 
    "Surpril", 
    "Nautilus", 
    "Shintengoku", 
    "Ravenstein", 
    "Primos", 
    "Urutorashi", 
    "Arastok", 
    "Generos", 
    "Arender", 
    "Honpidor", 
    "Iodeen", 
    "Angellis", 
    "Curclick", 
    "Hikmouth", 
    "Shinteng", 
    "The Depths", 
    "Ventios", 
    "Arca", 
    "Materbourne", 
  ],

  "oracle-settlement-type-result": [
    "<i>Artificial Habitat</i>. A self-contained environment with a rather small population.",
    "<i>Artificial Habitat</i>. A self-contained environment with a rather small population.",
    "<i>Artificial Habitat</i>. A self-contained environment with a rather big population.",
    "<i>Artificial Habitat</i>. A self-contained environment with a rather big population.",
    "<i>Transit Spaceport</i>. A hub for interstellar travel, with a focus on transportation and logistics.",
    "<i>Transit Spaceport</i>. A hub for interstellar travel, with a focus on transportation and logistics.",
    "<i>Transit Spaceport</i>. A hub for interstellar travel, with a focus on transportation and logistics.",
    "<i>Space Shipyard</i>. A facility dedicated to the construction and maintenance of starships.",
    "<i>Space Shipyard</i>. A facility dedicated to the construction and maintenance of starships.",
    "<i>Beacon Network</i>. Provides essential navigational information for interstellar traffic.", 
    "<i>Communications Relay</i>. Augments and maintains intra-system communications.", 
    "<i>Observation Post</i>. Monitors celestial phenomena, planetary activity, and space traffic.", 
    "<i>Solar Farm Array</i>. Captures stellar radiation for the benefit of local civilization.", 
    "<i>Defense Platform</i>. Equipped with weaponry to protect against external threats.", 
    "<i>Distribution Drones</i>. Provide constant cargo transport between ports and stations.", 
    "<i>Mirror Array</i>. Swarms of mirrors positioned to reflect and focus the star's energy, concentrating illumination and power at specific areas.", 
    "<i>Celestial Observatory</i>. Telescopes and sensor arrays positioned to observe distant cosmic phenomena, enabling advanced research and exploration.", 
    "<i>Spy Network</i>. Covertly collects information about other factions.", 
    "<i>Transport Relay</i>. Facilitates travel with some technological advancement.", 
  ],

  "oracle-settlement-firstlook-result": [
    "Beautiful architecture",
    "Built from organic materials",
    "Built from random scrap",
    "Built within repurposed ship",
    "Built within terrain or asteroid",
    "Defensible location",
    "Elevated or multi-level construction",
    "Hidden or subsurface location",
    "High-tech construction",
    "Industrial architecture",
    "Intimidating defenses",
    "Moving or transforming",
    "Obvious social stratification",
    "Precarious location",
    "Rustic architecture",
    "Significant structural damage",
    "Sprawling or dispersed structures",
    "Temporary or seasonal location",
    "Toxic or polluted habitat",
    "<a href=\"/oracles/core-oracles#descriptor\">Descriptor + Focus</a>",
  ],

  "oracle-settlement-initialattitude-result": [
    "Welcoming",
    "Welcoming",
    "Welcoming",
    "Neutral / automated",
    "Neutral / automated",
    "Neutral / automated",
    "Neutral / automated",
    "Wary",
    "Wary",
    "Wary",
    "Uncooperative",
    "Hostile",
    "Asking for help",
    "Asking for help",
    "Asking for help",
    "Asking for help",
    "In battle",
    "Captured",
    "Unresponsive",
    "Destroyed",
  ],

  "oracle-settlement-authority-result": [
    "None / lawless",
    "None / lawless",
    "None / lawless",
    "None / lawless",
    "Ineffectual",
    "Tolerant",
    "Tolerant",
    "Tolerant",
    "Fair",
    "Fair",
    "Fair",
    "Unyielding",
    "Corrupt",
    "Oppressive",
    "Oppressive",
  ],

  "oracle-settlement-projects-result": [
    "Agriculture",
    "Archeology",
    "Automation",
    "Black market",
    "Command",
    "Defense",
    "Energy",
    "Engineering",
    "Entertainment",
    "Environmentalism",
    "Evacuation",
    "Expansion",
    "Exploration",
    "Festival",
    "History",
    "Hunting",
    "Manufacturing",
    "Medical",
    "Migration",
    "Mining",
    "Pacifism",
    "Raiding",
    "Research",
    "Salvage",
    "Secrecy",
    "Shipbuilding",
    "Spirituality",
    "Subsistence",
    "Surveillance",
    "Terraforming",
    "Trade",
    "Warfare",
    "<a href=\"/oracles/core-oracles#action\">Action + Theme</a>",
  ],

  "oracle-settlement-trouble-result": [
    "Battle for leadership",
    "Betrayal from within",
    "Caught in the crossfire",
    "Changing environment",
    "Clash of cultures",
    "Dangerous discovery",
    "Depleted supplies",
    "Deprived of a resource",
    "Failing technology",
    "Feuding factions",
    "Ghostly visitations",
    "Hazardous environment",
    "Hostile lifeforms",
    "Impassable route",
    "Impending attack",
    "Impending natural disaster",
    "Invasive organisms",
    "Mounting debt",
    "Mysterious deaths",
    "Overdue delivery",
    "Plagued by sickness",
    "Preyed upon by raiders",
    "Revolt against leadership",
    "Sabotaged technology",
    "Shunned by others",
    "Social strife",
    "Someone is ill or injured",
    "Someone is missing",
    "Stolen technology or object",
    "Strange phenomenon",
    "Toxic waste or pollution",
    "Volatile energy source",
    "Vulnerable lifeforms",
    "<a href=\"/oracles/core-oracles#action\">Action + Theme</a>",
  ],

  "oracle-spaceborne-peril-result": [
    "Artificial gravity generator malfunctions",
    "Automated defenses or mines protect this area",
    "Compartment catches fire or is breached",
    "Contagion or illness threatens to take hold",
    "Dust clouds imperil navigation or conceal foes",
    "Energy storm looms",
    "Familiar foe appears or sends an ominous message",
    "Gravity well or vortex takes hold",
    "Imperiled ship calls for help",
    "Important device fails or malfunctions",
    "Infestation is revealed",
    "Intruder or stowaway creates trouble",
    "Isolation or fear presses in",
    "Life support system malfunctions",
    "Meteoroid storm fills the sky",
    "Mysterious wreckage portends a new threat",
    "Nearby settlement calls for help",
    "Old repair or patch fails",
    "Onboard dispute or inner turmoil causes a disruption",
    "Others obstruct your path or form a blockade",
    "Phantom signals suggest a lurking foe",
    "Pirates hunt for prey",
    "Power fails",
    "Primary drive or generator malfunctions",
    "Sabotage is revealed",
    "Shockwave or gravity wave approaches",
    "Someone questions your presence here",
    "Stellar anomaly emits hazardous energies",
    "Threatening lifeform draws near",
    "Troubling visions or apparitions",
    "True nature of a cargo, occupant, or passenger is revealed",
    "Unsettling sounds or disturbances",
  ],

  "oracle-spaceborne-opportunity-result": [
    "Advance warning of an environmental threat",
    "Automated signal offers a helpful message or warning",
    "Cache of cargo or supplies",
    "Chance for fellowship or a moment of inner peace",
    "Clear path through otherwise perilous space",
    "Clue offers insight into a current quest or mystery",
    "Clue to a lifeform's nature or vulnerabilities",
    "Derelict ripe for the picking",
    "Foe inadvertently reveals themselves or tips their hand",
    "Friendly interaction with a benign lifeform",
    "Friendly settlement in range",
    "Friendly spacers at work here",
    "Friendly starship crosses your path",
    "Helpful or encouraging message from an acquaintance",
    "Impressive vista offers comfort or inspiration",
    "Interesting site offers opportunities for exploration",
    "Mineral or energy resource detected",
    "Navigational or environmental hazard is left behind",
    "Opening to escape or avoid foes",
    "Plea for help from a potential benefactor",
    "Probe or beacon with useful data",
    "Refuge offers a place to hide, plan, or recover",
    "Sensors pinpoint a lurking foe",
    "Sensors reveal helpful or interesting environmental data",
    "Vehicle or equipment performs beyond expectations",
  ],

  "oracle-settlement-location-result": [
    "<i>Orbital</i>. Very close to its parent celestial body.",
    "<i>Orbital</i>. Very close to its parent celestial body.",
    "<i>Orbital</i>. Somewhat close to its parent celestial body, in synchronous orbit.",
    "<i>Orbital</i>. Somewhat close to its parent celestial body, in synchronous orbit.",
    "<i>Orbital</i>. Somewhat far from its parent celestial body, in a Lagrangian point.",
    "<i>Orbital</i>. Somewhat far from its parent celestial body, in a Lagrangian point.",
    "<i>Deep Space</i>. A self-contained community dedicated to a specific task or function in an isolated location, far removed from well-traveled spacelanes.",
    "<i>Deep Space</i>. A self-contained community dedicated to a specific task or function in an isolated location, far removed from well-traveled spacelanes.",
    "<i>Deep Space</i>. A self-contained community dedicated to a specific task or function in an isolated location, far removed from well-traveled spacelanes.",
    "<i>Deep Space</i>. A self-contained community dedicated to a specific task or function in a deep space location, but close to one or more well-traveled spacelanes.",
    "<i>Deep Space</i>. A self-contained community dedicated to a specific task or function in a deep space location, but close to one or more well-traveled spacelanes.",
    "Attached to other structure (asteroid, Wreckage clump, etc).",
  ],

  "oracle-fleet-type-result": [
    "Local security forces",
    "Local security forces",
    "Local security forces",
    "Local security forces",
    "Battle fleet",
    "Battle fleet",
    "Pirate wing",
    "Pirate wing",
    "Pirate wing",
    "Pirate wing",
    "Raider horde",
    "Raider horde",
    "Salvager hive",
    "Salvager hive",
    "Salvager hive",
    "Settler caravan",
    "Settler caravan",
    "Settler caravan",
    "Trade caravan",
    "Trade caravan",
    "Trade caravan",
    "Trade caravan",
    "Trade caravan",
    "Transport and escorts",
    "Transport and escorts",
    "Transport and escorts",
  ],

  "oracle-starship-type-result": [
    "Carrier (Launches fighters)",
    "Corvette (Light attack ship)",
    "Courier (Fast transport)",
    "Courier (Fast transport)",
    "Courier (Fast transport)",
    "Courier (Fast transport)",
    "Cruiser (Medium attack ship)",
    "Cruiser (Medium attack ship)",
    "Cruiser (Medium attack ship)",
    "Dreadnought (Heavy attack ship)",
    "Dreadnought (Heavy attack ship)",
    "Escape pod (Survival craft)",
    "Foundry (Mobile construction platform)",
    "Harvester (Fuel or energy excavator)",
    "Harvester (Fuel or energy excavator)",
    "Hauler (Heavy transport)",
    "Hauler (Heavy transport)",
    "Hauler (Heavy transport)",
    "Hauler (Heavy transport)",
    "Hauler (Heavy transport)",
    "Hunter (Stealthy attack ship)",
    "Habitat (Mobile dwelling vessel)",
    "Mender (Utility or repair)",
    "Mender (Utility or repair)",
    "Outbounder (Remote survey or research)",
    "Outbounder (Remote survey or research)",
    "Capital ship (Command flagship)",
    "Capital ship (Command flagship)",
    "Battlecruiser (warship)",
    "Battlecruiser (warship)",
    "Prospector (Mineral excavator)",
    "Prospector (Mineral excavator)",
    "Reclaimer (Salvage or rescue)",
    "Reclaimer (Salvage or rescue)",
    "Shuttle (Short-range transport)",
    "Shuttle (Short-range transport)",
    "Shuttle (Short-range transport)",
    "Snub fighter (Small attack craft)",
    "Snub fighter (Small attack craft)",
    "Snub fighter (Small attack craft)",
  ],

  "oracle-starship-name-result": [
    "Umber Bustard",
    "Quiescent",
    "Quicksilver",
    "Shear Razor",
    "Spirit of Normandy",
    "Dark Hurricane",
    "Silent Watcher",
    "Black Death",
    "New Beginning",
    "Condor",
    "Raven",
    "Falcon",
    "Star Eagle",
    "Black Viper",
    "Behemoth",
    "Berserker",
    "Avalanche",
    "Jellyfish",
    "Colossus",
    "Star Talon",
    "Far Star",
    "Lancaster",
    "Wildcat",
    "Tranquility",
    "Arclight",
    "Argent Arrow",
    "Artemis",
    "Astral Explorer",
    "Atlas",
    "Aurora",
    "Avari’s Wake",
    "Banshee’s Cry",
    "Beowulf",
    "Bloody Jaw",
    "Broken Sword",
    "Buccaneer",
    "Cerelis Nine",
    "Clarion Call",
    "Dawn’s Herald",
    "Dead Reckoning",
    "Drift Runner",
    "Eclipse",
    "Elara Five",
    "Enchantress",
    "Endurance",
    "Excalibur",
    "Eye of the Void",
    "Fall of Icarus",
    "Fallen Light",
    "False Hope",
    "Firebreak",
    "First Light",
    "Forge Flier",
    "Fortune’s Favor",
    "Freya’s Wrath",
    "Ghost",
    "Guiding Star",
    "Hand of Fate",
    "Herald of Doom",
    "Implacable",
    "Implicit",
    "Inferno",
    "Invictus",
    "Iron Cairn",
    "Karena’s Reverie",
    "Kraken",
    "Kuno’s Hammer",
    "Lightline",
    "Lodestar",
    "Long Haul",
    "Lost Fortune",
    "Luminous Sorrow",
    "Manta",
    "Mercy",
    "Mutara",
    "Nebula Prowler",
    "Newton’s Folly",
    "Nightfall",
    "Nomad",
    "Obsidian Trident",
    "Onslaught",
    "Orca",
    "Outward Bound",
    "Phantom",
    "Photon",
    "Poltergeist",
    "Profit Margin",
    "Raven’s Call",
    "Raya’s Promise",
    "Reaper",
    "Reforged Hope",
    "Relentless",
    "Royal Signet",
    "Rubicon",
    "Sareea’s Tribute",
    "Second Chance",
    "Shard of the Sun",
    "Shattered Siege",
    "Shattered Star",
    "Silver Talon",
    "Smoldering Flame",
    "Sovereign Skies",
    "Sparrowhawk",
    "Stardust",
    "Starfall",
    "Stellar Hawk",
    "Stormswept",
    "Sundered Aegis",
    "Sundown",
    "Sureshot",
    "Terminus Clipper",
    "Terrapin",
    "Timber Wolf",
    "Tip of the Spear",
    "Titan",
    "Tormentor",
    "Trithia Six",
    "Ultraviolet",
    "Valora’s Comet",
    "Vengeance",
    "Venture",
    "Vigilant",
    "Voidtreader",
    "Vulture",
  ],

  "oracle-starship-manufacturer-result": [
    [
      "INCOM",
      "Sinear",
      "Cygnus",
      "Niridian",
      "Talivar",
      "Vanguard",
      "Kaliban",
      "Aegis",
      "Anvil",
      "Anubis",
      "Bastion",
      "Bering",
      "Carthage",
      "Ceres",
      "Core",
      "Aglax",
      "Algol",
      "Horizon",
      "Omicron",
      "OmniConsumer",
      "Omni",
      "Asimov",
      "Krueger",
      "Weyland",
      "Masashi",
      "Shirow",
      "Shinra",
      "Clarke",
      "Heinlein",
      "Sagan",
      "Verne",
      "Von Braun",
      "Von Neumann",
    ],
    [
      "Corporation",
      "Corp",
      "Design Systems",
      "Spaceworks",
      "Designs",
      "Engineering",
      "Industries",
      "Engineering Corporation",
      "Systems",
      "Co",
      "Aerospace",
      "Dynamics",
      "LTD.",
    ],
  ],

  "oracle-starship-initialattitude-result": [
    "Familiar",
    "Friendly",
    "Friendly",
    "Neutral / automated",
    "Neutral / automated",
    "Neutral / automated",
    "Neutral / automated",
    "Wary",
    "Wary",
    "Wary",
    "Wary",
    "Wary",
    "Wary",
    "Dismissive",
    "Dismissive",
    "Uncooperative",
    "Uncooperative",
    "Hostile",
    "Hostile",
    "Hostile",
    "Hostile",
    "Asking for help",
    "Asking for help",
    "Asking for help",
    "In battle",
    "Unresponsive",
    "Destroyed",
  ],

  "oracle-starship-firstlook-result": [
    "Abnormal sensor readings",
    "Brightly painted",
    "Bristling with weapons",
    "Dark or stealthy",
    "Heavy armor",
    "Immobile",
    "Intimidating profile",
    "Large sensor arrays",
    "Leaking radiation",
    "Low-profile or disguised",
    "Modern or advanced design",
    "Obsolete design",
    "Obvious damage",
    "Biological components",
    "Ornate markings",
    "Oversized engines",
    "Prominent guild emblem",
    "Refitted or repurposed hull",
    "Scarred hull",
    "Built from scrap",
    "Towing or linked",
  ],

  "oracle-starship-mission-result": [
    "Blockade a location",
    "Break a blockade",
    "Collect a resource",
    "Command others",
    "Conduct diplomacy",
    "Conduct espionage",
    "Conduct piracy",
    "Conduct research",
    "Defend against an attack",
    "Deliver messages or data",
    "Establish a settlement",
    "Evacuate a location",
    "Explore a region",
    "Hold prisoners",
    "Hunt down another ship",
    "Launch an attack",
    "Patrol an area",
    "Provide medical aid",
    "Provide repairs",
    "Provide shelter",
    "Quarantine a danger",
    "Raid a settlement",
    "Resupply a settlement",
    "Retrieve salvage",
    "Search and rescue",
    "Smuggle cargo",
    "Survey a site",
    "Test a technology",
    "Transport cargo",
    "Transport passengers",
  ],

  "oracle-derelict-location-result": [
    "Planetside",
    "Orbital",
    "Deep Space",
  ],

  "oracle-derelict-type-result": [
    "Spaceship (adrift or crashed)",
    "Settlement (or space station)",
  ],

  "oracle-derelict-condition-result": [
    "Functional",
    "Limited power",
    "Cold and dark",
    "Damaged or breached",
    "Heavily damaged",
    "Impending destruction",
  ],

  "oracle-derelict-outer-first-look-result": [
    "Blocked access",
    "Corpses",
    "Hazardous readings",
    "Mutated structure",
    "Odd orientation",
    "Overgrown or entangled",
    "Sending a signal or message",
    "Signs that others are here",
    "Stripped exterior",
    "Time or reality distortions",
  ],

  "oracle-derelict-inner-first-look-result": [
    "Abnormal gravity",
    "Active bots",
    "Archaic equipment",
    "Automated announcements",
    "Biological infestation",
    "Charred surfaces",
    "Claw marks",
    "Cluttered with debris",
    "Corroded surfaces",
    "Cramped spaces",
    "Creaking hull",
    "Esoteric writing or symbols",
    "Evidence of new inhabitants",
    "Exposed wiring or conduits",
    "Flashing strobe lights",
    "Fluctuating power",
    "Haunting visions of the dead",
    "Hazardous temperature",
    "Heavy steam or moisture",
    "Littered with corpses",
    "Nesting or feeding creatures",
    "Ornate furnishings",
    "Scarred by gunfire",
    "Sealed against intruders",
    "Signs of looting or scavenging",
    "Smell of decay",
    "Splattered with blood",
    "Temporal distortions",
    "Thick haze or smoke",
    "Unstable energy surges",
    "Watchful AI",
  ],

  "oracle-derelict-zone-type-result": [
    "<a href=\"/oracles/space-oracles#derelict-zone-access\">Access</a>",
    "<a href=\"/oracles/space-oracles#derelict-zone-community\">Community</a>",
    "<a href=\"/oracles/space-oracles#derelict-zone-engineering\">Engineering</a>",
    "<a href=\"/oracles/space-oracles#derelict-zone-living\">Living</a>",
    "<a href=\"/oracles/space-oracles#derelict-zone-medical\">Medical</a>",
    "<a href=\"/oracles/space-oracles#derelict-zone-operations\">Operations</a>",
    "<a href=\"/oracles/space-oracles#derelict-zone-production\">Production</a>",
    "<a href=\"/oracles/space-oracles#derelict-zone-research\">Research</a>",
  ],

  "oracle-derelict-zone-access-area-result": [
    "Corridor",
    "Stairs",
    "Lift or elevator",
    "Catwalk or bridge",
    "Vertical shaft or ladder",
    "Hub or intersection",
    "Crawl space or duct",
    "Airlock or external",
  ],
  "oracle-derelict-zone-access-feature-result": [
    "Abandoned gear", 
    "Blood trail", 
    "Breached door or hatch", 
    "Control or terminal station", 
    "Corpse", 
    "Dismantled equipment", 
    "Flashing strobes", 
    "Leaking pipes", 
    "Makeshift barricade", 
    "Opened or missing panels", 
    "Organic growths", 
    "Ruined bot", 
    "Scrawled warning", 
    "Sealed breach", 
    "Sounds of movement", 
    "Steam or smoke", 
    "Wandering bot", 
    "Windows or viewports", 
    "Wrecked passage or debris", 
  ],
  "oracle-derelict-zone-access-peril-result": [
    "Alarm or failsafe is triggered", 
    "Automated defenses", 
    "Blocked or sealed path", 
    "Dreadful scene of death or violence", 
    "Foe closes in", 
    "Gear is failing or broken", 
    "Hazardous environmental change", 
    "Path is trapped", 
    "Unsettling sound or disturbance", 
  ],
  "oracle-derelict-zone-access-opportunity-result": [
    "Directions, shortcut, or alternate path", 
    "Encounter with a friendly survivor, explorer, or denizen", 
    "Hopeful signs of life", 
    "Opening to outmaneuver or escape a threat or foe", 
    "Useful equipment", 
  ],

  "oracle-derelict-zone-community-area-result": [
    "Bar or club", 
    "Classroom or education", 
    "Concourse or hub", 
    "Entertainment", 
    "Gym or fitness", 
    "Market or trade", 
    "Park or garden", 
    "Promenade or overlook", 
    "Restaurant or dining", 
    "Temple or chapel", 
    "Transition into <a href=\"/oracles/space-oracles#derelict-zone-type\">New Zone</a>", 
  ],
  "oracle-derelict-zone-community-feature-result": [
    "Ad-hoc memorials", 
    "Art depicting historic event", 
    "Artificial environment", 
    "Automated announcements", 
    "Barricaded area", 
    "Gaming devices or interfaces", 
    "Graffiti or vandalization", 
    "Guard post or surveillance", 
    "Mass grave or corpses", 
    "Panoramic viewport", 
    "Rubble or debris", 
  ],
  "oracle-derelict-zone-community-peril-result": [
    "Biological infestation", 
    "Breached or broken structure", 
    "Distressing signs of mass violence or death", 
    "Flooded environment", 
    "Foe lurks within concealment", 
    "Fragile structural integrity", 
    "Haunting vision of life here before the fall", 
    "Hazardous environmental change", 
    "Heartbreaking memento of lost lives", 
  ],
  "oracle-derelict-zone-community-opportunity-result": [
    "Culturally significant object or artifact", 
    "Salvageable goods or resources", 
    "Secure area offers a moment of peace", 
    "Terminal with access to site details", 
    "Valuable item", 
  ],

  "oracle-derelict-zone-engineering-area-result": [
    "Control room", 
    "Engine room or power core", 
    "Engineering offices", 
    "Equipment storage", 
    "Fuel or coolant tanks", 
    "Life support", 
    "Maintenance tube", 
    "Vehicle bay or garage", 
    "Water processing", 
    "Workshop", 
    "Transition into <a href=\"/oracles/space-oracles#derelict-zone-type\">New Zone</a>", 
  ],
  "oracle-derelict-zone-engineering-feature-result": [
    "Cluttered workbench", 
    "Control terminal", 
    "Crane or lift", 
    "Disassembled equipment", 
    "Flickering status monitors", 
    "Jury-rigged equipment", 
    "Multilevel layout", 
    "Pipes and valves", 
    "Sharp ozone smell", 
    "Unfinished project", 
    "Utility bots", 
  ],
  "oracle-derelict-zone-engineering-peril-result": [
    "Corrosive leak", 
    "Erratic utility bots", 
    "Failing equipment requires a specific part or skill", 
    "Fire or energy surge", 
    "Precarious or broken path", 
    "Radioactive hotspot", 
    "Sabotaged equipment", 
    "Shrouded atmosphere conceals a lurking foe", 
    "Unstable or failing power core", 
  ],
  "oracle-derelict-zone-engineering-opportunity-result": [
    "Advanced or experimental equipment", 
    "Chance to restore power or function", 
    "Helpful plans or schematics", 
    "Helpful utility bot", 
    "Useful tool or device", 
  ],

  "oracle-derelict-zone-living-area-result": [
    "Food storage", 
    "Galley or kitchen", 
    "Laundry", 
    "Locker room or storage", 
    "Mess hall or dining", 
    "Observation lounge", 
    "Quarters (communal)", 
    "Quarters (individual)", 
    "Restroom or showers", 
    "Sleeping pods", 
    "Transition into <a href=\"/oracles/space-oracles#derelict-zone-type\">New Zone</a>", 
  ],
  "oracle-derelict-zone-living-feature-result": [
    "Abandoned pet", 
    "Audible music", 
    "Cherished personal item", 
    "Failed barricade", 
    "Half-eaten food", 
    "Messages from loved ones", 
    "Ransacked belongings", 
    "Remains of the dead", 
    "Scuttling vermin", 
    "Shrine or altar", 
    "Unusual art", 
  ],
  "oracle-derelict-zone-living-peril-result": [
    "Booby trap", 
    "Distressing written message", 
    "Disturbing evidence of exploitive living conditions", 
    "Dreadful scene of death or violence", 
    "Lured into danger by signs of life", 
    "Recorded message reveals a threat or complication", 
    "Sealed door or hatch blocks access", 
    "Signs of unwelcome invaders", 
    "Unsettling sound or disturbance", 
  ],
  "oracle-derelict-zone-living-opportunity-result": [
    "Culturally significant object or artifact", 
    "Hidden stash of valuable contraband", 
    "Intact barricade or protected area", 
    "Recorded message reveals helpful aspects of this site", 
    "Useful personal gear", 
  ],

  "oracle-derelict-zone-medical-area-result": [
    "Crematorium", 
    "Emergency or triage", 
    "Isolation or containment", 
    "Medical lab", 
    "Medical offices", 
    "Morgue", 
    "Operating room", 
    "Pharmacy or drug locker", 
    "Prosthetics workshop", 
    "Ward or clinic", 
    "Transition into <a href=\"/oracles/space-oracles#derelict-zone-type\">New Zone</a>", 
  ],
  "oracle-derelict-zone-medical-feature-result": [
    "Autopsied corpse", 
    "Biological specimens", 
    "Blood spatter or pools", 
    "Bloody medical supplies", 
    "Broken prosthetics", 
    "Corpse of a healer", 
    "Dissected specimen", 
    "Improvised overflow beds", 
    "Medical monitors", 
    "Medical records or scans", 
    "Stacks of body bags", 
  ],
  "oracle-derelict-zone-medical-peril-result": [
    "Disgusting sight / smell", 
    "Disturbing evidence of medical misconduct", 
    "Erratic medical bots", 
    "Evidence of a virulent disease", 
    "Malfunctioning medical equipment", 
    "Repercussions of a medical experiment", 
    "Restless dead", 
    "Signs of a horrific death", 
    "Signs of broken quarantine", 
  ],
  "oracle-derelict-zone-medical-opportunity-result": [
    "Cache of medicine", 
    "Clues to a medical mystery", 
    "Helpful medical bot", 
    "Unusual or rare specimen", 
    "Useful medical equipment", 
  ],

  "oracle-derelict-zone-operations-area-result": [
    "Admin or command offices", 
    "Armory", 
    "Bridge or command center", 
    "Brig or cells", 
    "Comms center", 
    "Computer core", 
    "Conference or briefing room", 
    "Landing bay or hangar", 
    "Lounge", 
    "Security", 
    "Transition into <a href=\"/oracles/space-oracles#derelict-zone-type\">New Zone</a>", 
  ],
  "oracle-derelict-zone-operations-feature-result": [
    "Automated warning", 
    "Buckled blast doors", 
    "Control terminal", 
    "Emergency lighting", 
    "EV suit storage", 
    "Hissing comms channel", 
    "Intricate control panels", 
    "Map of the site", 
    "Recorded message", 
    "Video surveillance monitors", 
    "Written logs", 
  ],
  "oracle-derelict-zone-operations-peril-result": [
    "Automated defenses target you", 
    "Broken equipment limits control", 
    "Coded message or puzzling security device", 
    "Discouraging evidence of failed plans or defenses", 
    "Displays reveal a new threat elsewhere in this site", 
    "Failing power", 
    "Hostile AI", 
    "Sealed blast doors block access", 
    "Sensors indicate the arrival of an external threat", 
  ],
  "oracle-derelict-zone-operations-opportunity-result": [
    "Cache of weapons or ammo", 
    "Helpful AI", 
    "Keycard or access code", 
    "Log offers insight into this site's downfall", 
    "Secure area offers a moment of peace", 
  ],

  "oracle-derelict-zone-production-area-result": [
    "Airlock or staging area", 
    "Assembly or processing", 
    "Cargo bay", 
    "Equipment storage", 
    "Exosuit bay", 
    "Harvesting or mining platform", 
    "Monitoring or control room", 
    "Processed goods storage", 
    "Raw materials storage", 
    "Scrapyard", 
    "Transition into <a href=\"/oracles/space-oracles#derelict-zone-type\">New Zone</a>", 
  ],
  "oracle-derelict-zone-production-feature-result": [
    "Cargo lifts", 
    "Control panels", 
    "Disassembled machinery", 
    "Elevated walkways", 
    "Environment suits", 
    "Ill-fated workers", 
    "Immense machinery", 
    "Sealed or locked containers", 
    "Tools", 
    "Vats of chemicals or gas", 
    "Written manifest", 
  ],
  "oracle-derelict-zone-production-peril-result": [
    "Claustrophobic spaces", 
    "Dangerous machinery", 
    "Disturbing evidence of exploited labor", 
    "Extreme temperatures", 
    "Hazardous materials", 
    "Impending industrial disaster", 
    "Malfunctioning automation", 
    "Rivals seek to secure these resources", 
    "Signs of an unearthed or manufactured threat", 
  ],
  "oracle-derelict-zone-production-opportunity-result": [
    "Helpful vehicle or transport", 
    "Rare or valuable resource", 
    "Salvageable materials", 
    "Useful equipment", 
    "Valuable cargo", 
  ],

  "oracle-derelict-zone-research-area-result": [
    "Clean room", 
    "Cold storage", 
    "Creature or animal pens", 
    "Decontamination room", 
    "Hazardous material storage", 
    "Hydroponics or agriculture", 
    "Isolation or containment", 
    "Lab", 
    "Library or records", 
    "Secure vault", 
    "Transition into <a href=\"/oracles/space-oracles#derelict-zone-type\">New Zone</a>", 
  ],
  "oracle-derelict-zone-research-feature-result": [
    "Aquarium or tank", 
    "Biological specimens", 
    "Bones or fossils", 
    "Broken equipment", 
    "Cryptic research notes", 
    "Hastily destroyed data", 
    "Hazmat suits", 
    "Inscrutable artifact", 
    "Invasive plant growth", 
    "Recorded research log", 
    "Spilled chemicals", 
  ],
  "oracle-derelict-zone-research-peril-result": [
    "Automated containment protocols are activated", 
    "Biological infestation", 
    "Dangerous specimen", 
    "Disturbing outcome of a failed experiment", 
    "Evidence of sinister experiments", 
    "Fragile vault holds a dire threat", 
    "Signs of broken containment", 
    "Toxic environment", 
    "Unstable technology", 
  ],
  "oracle-derelict-zone-research-opportunity-result": [
    "Helpful research data", 
    "Records of a notable discovery", 
    "Specialized research tools", 
    "Unique prototype", 
    "Useful navigational data", 
  ],
};
export default spaceOracleResults;