const characterOracleResults = {
    "oracle-character-name-male-result": [
        "Akihiko",
        "Akira",
        "Aoki",
        "Asa",
        "Benjiro",
        "Botan",
        "Chibi",
        "Chiharu",
        "Chiko",
        "Daiki",
        "Daisuke",
        "Goro",
        "Habiki",
        "Hachi",
        "Hachiro",
        "Hakaku",
        "Hansuke",
        "Hideo",
        "Hiroshi",
        "Hiroto",
        "Hotaru",
        "Ichiro",
        "Itachi",
        "Jiro",
        "Junichiro",
        "Junpei",
        "Kaede",
        "Kage",
        "Kaiyo",
        "Kame",
        "Kazumi",
        "Keiji",
        "Keisuke",
        "Keitaro",
        "Ken",
        "Kenji",
        "Kiyoshi",
        "Koji",
        "Mako",
        "Masashi",
        "Miyoko",
        "Noboru",
        "Orochi",
        "Reiji",
        "Takato",
        "Takaya",
        "Tamaki",
        "Yamato",
        "Yoshio",
        "Aaron",
        "Abel",
        "Abraham",
        "Abram",
        "Ace",
        "Adam",
        "Adan",
        "Adin",
        "Adonis",
        "Adrian",
        "Adriel",
        "Afonso",
        "Ahmed",
        "Ahmet",
        "Aidan",
        "Aiden",
        "Aimar",
        "Aksel",
        "Alan",
        "Albert",
        "Alejandro",
        "Aleksandar",
        "Alen",
        "Alessandro",
        "Alex",
        "Alexander",
        "Alexandru",
        "Alexey",
        "Alexis",
        "Alfie",
        "Alfred",
        "Ali",
        "Alijah",
        "Allen",
        "Alonzo",
        "Álvaro",
        "Amar",
        "Amari",
        "Amir",
        "Anar",
        "Anas",
        "Ander",
        "Anderson",
        "Andre",
        "Andreas",
        "Andrej",
        "Andres",
        "Andrew",
        "Andrey",
        "Andria",
        "Andriy",
        "Andy",
        "Angel",
        "Angelo",
        "Anthony",
        "Anton",
        "Antoni",
        "Antonio",
        "Aputsiaq",
        "Archer",
        "Ari",
        "Arjun",
        "Arlo",
        "Arman",
        "Armando",
        "Armani",
        "Aron",
        "Artem",
        "Arthur",
        "Artiom",
        "Artsiom",
        "Arturs",
        "Artyom",
        "Asher",
        "Ashton",
        "Athanasios",
        "Atlas",
        "Atticus",
        "August",
        "Augustus",
        "Austin",
        "Avery",
        "Axel",
        "Ayden",
        "Aykhan",
        "Balázs",
        "Barrett",
        "Beau",
        "Beckett",
        "Beckham",
        "Bence",
        "Benedikt",
        "Benjamin",
        "Bennett",
        "Benson",
        "Bentley",
        "Berat",
        "Biel",
        "Blake",
        "Bodhi",
        "Bogdan",
        "Bowen",
        "Bradley",
        "Brady",
        "Brandon",
        "Brantley",
        "Braxton",
        "Brayden",
        "Braylen",
        "Brian",
        "Brody",
        "Brooks",
        "Bruce",
        "Bryan",
        "Bryce",
        "Bryson",
        "Cade",
        "Caden",
        "Caiden",
        "Caleb",
        "Calvin",
        "Camden",
        "Cameron",
        "Carl",
        "Carlos",
        "Carson",
        "Carter",
        "Cash",
        "Cayden",
        "Cesar",
        "Chance",
        "Charles",
        "Charlie",
        "Chase",
        "Christian",
        "Christopher",
        "Christos",
        "Clark",
        "Clayton",
        "Cody",
        "Cohen",
        "Cole",
        "Colin",
        "Collin",
        "Colt",
        "Colton",
        "Conner",
        "Connor",
        "Conor",
        "Cooper",
        "Corbin",
        "Corey",
        "Cristian",
        "Cruz",
        "Cyrus",
        "Daan",
        "Dakota",
        "Dallas",
        "Dalton",
        "Damian",
        "Damien",
        "Damon",
        "Daniel",
        "Dante",
        "Danyl",
        "Daris",
        "Darius",
        "David",
        "Davit",
        "Davud",
        "Dawson",
        "Dax",
        "Daxton",
        "Deacon",
        "Dean",
        "Declan",
        "Dejan",
        "Denys",
        "Derek",
        "Derrick",
        "Desmond",
        "Devin",
        "Dexter",
        "Diego",
        "Dimitar",
        "Dimitrios",
        "Dmitry",
        "Dmytro",
        "Dominic",
        "Dominick",
        "Dominik",
        "Dominykas",
        "Donovan",
        "Dovydas",
        "Dragan",
        "Drake",
        "Drew",
        "Dušan",
        "Dylan",
        "Easton",
        "Eden",
        "Edgar",
        "Edoardo",
        "Eduardo",
        "Edward",
        "Edwin",
        "Eetu",
        "Eino",
        "Elchin",
        "Eli",
        "Elian",
        "Elias",
        "Elias",
        "Elijah",
        "Elliot",
        "Elliott",
        "Ellis",
        "Elnur",
        "Elshan",
        "Emanuel",
        "Emerson",
        "Emil",
        "Emiliano",
        "Emilio",
        "Emilis",
        "Emir",
        "Emirhan",
        "Emmanuel",
        "Emmett",
        "Enrique",
        "Enzo",
        "Enzo",
        "Ergi",
        "Eric",
        "Erick",
        "Erik",
        "Esteban",
        "Ethan",
        "Evan",
        "Everett",
        "Evgeny",
        "Eymen",
        "Ezekiel",
        "Ezequiel",
        "Ezra",
        "Fabian",
        "Felix",
        "Fernando",
        "Filip",
        "Finley",
        "Finn",
        "Finnegan",
        "Francis",
        "Francisco",
        "Franciszek",
        "Frank",
        "Franklin",
        "Frederick",
        "Gabriel",
        "Gabrielius",
        "Gael",
        "Gage",
        "Garrett",
        "Gavin",
        "George",
        "Georgios",
        "Gianni",
        "Gideon",
        "Giorgi",
        "Giovanni",
        "Gor",
        "Goran",
        "Grady",
        "Graham",
        "Grant",
        "Grayson",
        "Gregory",
        "Greyson",
        "Griffin",
        "Guðmundur",
        "Guilherme",
        "Gunnar",
        "Gunner",
        "Gustavs",
        "Hamza",
        "Hank",
        "Hans",
        "Harrison",
        "Harun",
        "Harvey",
        "Hasan",
        "Hayden",
        "Hayes",
        "Hayk",
        "Hector",
        "Hendrix",
        "Henri",
        "Henry",
        "Holden",
        "Hudson",
        "Hugo",
        "Hunter",
        "Huseyn",
        "Ian",
        "Ibai",
        "Ibrahim",
        "Igor",
        "Iker",
        "Ilgar",
        "Ilija",
        "Imran",
        "Inuk",
        "Inunnguaq",
        "Ioannis",
        "Ion",
        "Isaac",
        "Isaiah",
        "Ismael",
        "Ismail",
        "Israel",
        "Ivan",
        "Jace",
        "Jack",
        "Jackson",
        "Jacob",
        "Jaden",
        "Jaiden",
        "Jaka",
        "Jake",
        "Jakov",
        "James",
        "James",
        "Jameson",
        "Jan",
        "Jared",
        "Jase",
        "Jason",
        "Jasper",
        "Javier",
        "Jax",
        "Jaxon",
        "Jaxton",
        "Jay",
        "Jayce",
        "Jayceon",
        "Jayden",
        "Jaylen",
        "Jayson",
        "Jeffrey",
        "Jensen",
        "Jeremiah",
        "Jeremy",
        "Jesse",
        "Jesus",
        "Jett",
        "João",
        "Joaquin",
        "Joel",
        "John",
        "Johnathan",
        "Johnny",
        "Jokubas",
        "Jonah",
        "Jonas",
        "Jonathan",
        "Jordan",
        "Jordi",
        "Jorge",
        "Jose",
        "Joseph",
        "Joshua",
        "Josiah",
        "Josue",
        "Jovan",
        "Juan",
        "Judah",
        "Jude",
        "Jules",
        "Julian",
        "Julius",
        "Justin",
        "Kacper",
        "Kade",
        "Kaden",
        "Kai",
        "Kaiden",
        "Kairo",
        "Kajus",
        "Kaleb",
        "Kamden",
        "Kameron",
        "Kane",
        "Karson",
        "Karter",
        "Kasen",
        "Kash",
        "Kashton",
        "Kason",
        "Kaspar",
        "Kayden",
        "Kayson",
        "Keegan",
        "Kendrick",
        "Kenneth",
        "Kevin",
        "Khalil",
        "Kian",
        "Kieran",
        "Killian",
        "King",
        "Kingston",
        "Kirill",
        "Knox",
        "Kobe",
        "Kolton",
        "Konstantinos",
        "Kostas",
        "Kyle",
        "Kyler",
        "Kyrie",
        "Kyson",
        "Landen",
        "Landon",
        "Lane",
        "Lars",
        "Lawrence",
        "Lawson",
        "Lazar",
        "Legend",
        "Leland",
        "Lennox",
        "Leo",
        "Leon",
        "Leonardo",
        "Leonel",
        "Levente",
        "Levi",
        "Lewis",
        "Liam",
        "Lincoln",
        "Logan",
        "Lorenzo",
        "Louis",
        "Lovro",
        "Luca",
        "Luca",
        "Lucas",
        "Luciano",
        "Luis",
        "Luka",
        "Lukas",
        "Luke",
        "Luuk",
        "Maddox",
        "Major",
        "Maksim",
        "Malachi",
        "Malakai",
        "Malcolm",
        "Malik",
        "Malthe",
        "Manuel",
        "Marcell",
        "Marco",
        "Marcos",
        "Marcus",
        "Mario",
        "Marios",
        "Mark",
        "Mark",
        "Markel",
        "Marko",
        "Markus",
        "Marshall",
        "Martim",
        "Martin",
        "Mason",
        "Matas",
        "Mateo",
        "Mathias",
        "Matias",
        "Matthew",
        "Matthias",
        "Mattia",
        "Matúš",
        "Matyáš",
        "Maverick",
        "Max",
        "Maxim",
        "Maximilian",
        "Maximiliano",
        "Maximus",
        "Maxwell",
        "Mehmet",
        "Memphis",
        "Messiah",
        "Micah",
        "Michael",
        "Michalis",
        "Miguel",
        "Mihail",
        "Mihajlo",
        "Mikel",
        "Mikhail",
        "Milan",
        "Miles",
        "Milo",
        "Miloš",
        "Minik",
        "Mohamed",
        "Moises",
        "Muhammed",
        "Murad",
        "Mustafa",
        "Myles",
        "Narek",
        "Nasir",
        "Nathan",
        "Nathaniel",
        "Nazar",
        "Nehemiah",
        "Nemanja",
        "Nicholas",
        "Nico",
        "Nicolas",
        "Niilo",
        "Nikita",
        "Nikola",
        "Nikolai",
        "Nikolaos",
        "Nikolay",
        "Nikoloz",
        "Nil",
        "Noah",
        "Noel",
        "Nojus",
        "Nolan",
        "Nuka",
        "Oakley",
        "Odin",
        "Oier",
        "Oleksandr",
        "Oliver",
        "Omar",
        "Omari",
        "Ondrej",
        "Onni",
        "Orion",
        "Oscar",
        "Osman",
        "Otto",
        "Owen",
        "Pablo",
        "Panagiotis",
        "Parker",
        "Patrick",
        "Pau",
        "Paul",
        "Pavle",
        "Paxton",
        "Pedro",
        "Peter",
        "Peyton",
        "Philip",
        "Phillip",
        "Phoenix",
        "Pierce",
        "Pol",
        "Porter",
        "Preston",
        "Prince",
        "Princeton",
        "Quinn",
        "Rafael",
        "Raiden",
        "Ralfs",
        "Raphael",
        "Rashad",
        "Rasmus",
        "Raul",
        "Rayan",
        "Raymond",
        "Reed",
        "Reid",
        "Remington",
        "Remy",
        "Rhett",
        "Rhys",
        "Ricardo",
        "Riccardo",
        "Richard",
        "Riley",
        "River",
        "Roan",
        "Robert",
        "Roberto",
        "Robin",
        "Rocco",
        "Rodrigo",
        "Roel",
        "Roman",
        "Romeo",
        "Ronald",
        "Ronan",
        "Ronin",
        "Rory",
        "Rowan",
        "Rowen",
        "Royal",
        "Royce",
        "Ruben",
        "Russell",
        "Ryan",
        "Ryder",
        "Ryker",
        "Rylan",
        "Saba",
        "Sage",
        "Salik",
        "Samir",
        "Samuel",
        "Santiago",
        "Sawyer",
        "Sean",
        "Seán",
        "Sebastian",
        "Sem",
        "Sergei",
        "Sergio",
        "Seth",
        "Shane",
        "Shawn",
        "Silas",
        "Simon",
        "Skyler",
        "Solomon",
        "Spencer",
        "Stefan",
        "Stephen",
        "Sterling",
        "Steven",
        "Sullivan",
        "Szymon",
        "Tanner",
        "Tarik",
        "Tate",
        "Théo",
        "Theodore",
        "Thiago",
        "Thomas",
        "Tigran",
        "Timothy",
        "Titus",
        "Tobias",
        "Tobias",
        "Tommaso",
        "Travis",
        "Trevor",
        "Tristan",
        "Troy",
        "Tucker",
        "Tunar",
        "Tyler",
        "Tyson",
        "Ughur",
        "Unax",
        "Uriel",
        "Väinö",
        "Valdemar",
        "Vasileios",
        "Vasilije",
        "Vedad",
        "Victor",
        "Victor",
        "Vince",
        "Vincent",
        "Vojtech",
        "Vugar",
        "Vuk",
        "Vusal",
        "Wade",
        "Walker",
        "Walter",
        "Warren",
        "Waylon",
        "Wesley",
        "Weston",
        "William",
        "Winston",
        "Wojciech",
        "Wout",
        "Wyatt",
        "Xander",
        "Xavier",
        "Xhoel",
        "Yanis",
        "Yegor",
        "Yusif",
        "Yusuf",
        "Zachariah",
        "Zachary",
        "Zaiden",
        "Zak",
        "Žan",
        "Zander",
        "Zane",
        "Zayden",
        "Zayn",
        "Zayne",
        "Zion",
        "Zoran",
    ],
    "oracle-character-name-female-result": [
        "Aada",
        "Aaliyah",
        "Abby",
        "Abigail",
        "Ada",
        "Adaline",
        "Adalynn",
        "Addilyn",
        "Addison",
        "Adéla",
        "Adelaide",
        "Adeline",
        "Adelynn",
        "Adriana",
        "Adrianna",
        "Aikaterini",
        "Aina",
        "Aino",
        "Ainsley",
        "Aitana",
        "Ajla",
        "Alaina",
        "Alana",
        "Alani",
        "Alayna",
        "Alba",
        "Aleksandra",
        "Alesia",
        "Alessandra",
        "Alexa",
        "Alexandra",
        "Alexandria",
        "Alexis",
        "Alice",
        "Alicia",
        "Alina",
        "Alisa",
        "Alise",
        "Alison",
        "Alivia",
        "Aliyah",
        "Allie",
        "Allison",
        "Alma",
        "Alondra",
        "Alva",
        "Alyssa",
        "Amanda",
        "Amara",
        "Amari",
        "Amaya",
        "Amber",
        "Amelia",
        "Amina",
        "Amira",
        "Amiyah",
        "Amy",
        "Amy",
        "Ana",
        "Anahit",
        "Anastasia",
        "Anaya",
        "Andrea",
        "Androula",
        "Angel",
        "Angela",
        "Angeliki",
        "Angelina",
        "Aniyah",
        "Anja",
        "Anna",
        "Annabelle",
        "Annalise",
        "Anne",
        "Annie",
        "Antonella",
        "Antonia",
        "Aoife",
        "April",
        "Arabella",
        "Aria",
        "Ariah",
        "Ariana",
        "Arianna",
        "Ariel",
        "Ariella",
        "Arielle",
        "Ariyah",
        "Arya",
        "Ashley",
        "Asja",
        "Aspen",
        "Athena",
        "Aubree",
        "Aubrey",
        "Audrey",
        "Aurora",
        "Austeja",
        "Autumn",
        "Ava",
        "Avah",
        "Averie",
        "Avery",
        "Aviana",
        "Avianna",
        "Aya",
        "Aygun",
        "Ayla",
        "Aylin",
        "Ayse",
        "Aysel",
        "Azra",
        "Bailey",
        "Barbare",
        "Barbora",
        "Beatrice",
        "Belinay",
        "Bella",
        "Bethany",
        "Bianca",
        "Biljana",
        "Blair",
        "Blakely",
        "Blanca",
        "Boglárka",
        "Braelynn",
        "Brianna",
        "Briella",
        "Brielle",
        "Brinley",
        "Brooke",
        "Brooklynn",
        "Brynlee",
        "Brynn",
        "Cadence",
        "Cali",
        "Callie",
        "Camila",
        "Camilla",
        "Camille",
        "Camryn",
        "Carla",
        "Carlota",
        "Carly",
        "Carmen",
        "Carolina",
        "Caroline",
        "Carter",
        "Cassidy",
        "Cataleya",
        "Catalina",
        "Catherine",
        "Cecilia",
        "Celeste",
        "Charlee",
        "Charleigh",
        "Charlie",
        "Charlotte",
        "Chelsea",
        "Cheyenne",
        "Chloe",
        "Chloe",
        "Christiane",
        "Christina",
        "Claire",
        "Clara",
        "Cora",
        "Dahlia",
        "Daisy",
        "Daisy",
        "Dakota",
        "Daleyza",
        "Daniela",
        "Daniella",
        "Danielle",
        "Daniz",
        "Daphne",
        "Daria",
        "Darya",
        "Dayana",
        "Delaney",
        "Delilah",
        "Demi",
        "Destiny",
        "Diana",
        "Diana",
        "Dimitra",
        "Dominique",
        "Dragana",
        "Dunja",
        "Dylan",
        "Ebba",
        "Ecrin",
        "Eden",
        "Edith",
        "Eevi",
        "Ela",
        "Elaina",
        "Eleanor",
        "Elen",
        "Elena",
        "Eleni",
        "Eliana",
        "Elianna",
        "Elif",
        "Eliise",
        "Elisa",
        "Elise",
        "Eliza",
        "Elizabeth",
        "Ella",
        "Elle",
        "Ellen",
        "Elliana",
        "Ellie",
        "Eloise",
        "Elsa",
        "Elsie",
        "Ema",
        "Ember",
        "Emelia",
        "Emely",
        "Emerson",
        "Emersyn",
        "Emery",
        "Emilia",
        "Emily",
        "Emina",
        "Emine",
        "Emma",
        "Emory",
        "Erin",
        "Esma",
        "Esmeralda",
        "Estere",
        "Esther",
        "Eva",
        "Evangeline",
        "Eve",
        "Evelina",
        "Evelyn",
        "Evelynn",
        "Everleigh",
        "Everly",
        "Evi",
        "Evie",
        "Faith",
        "Fatima",
        "Fatma",
        "Felicity",
        "Fenna",
        "Fernanda",
        "Fien",
        "Finley",
        "Fiona",
        "Frances",
        "Francesca",
        "Freja",
        "Freya",
        "Gabija",
        "Gabriela",
        "Gabriella",
        "Gabrielle",
        "Gemma",
        "Genesis",
        "Genevieve",
        "Georgia",
        "Gia",
        "Gianna",
        "Ginevra",
        "Giorgia",
        "Giselle",
        "Giulia",
        "Gordana",
        "Grace",
        "Gracelyn",
        "Gracelynn",
        "Gracie",
        "Greta",
        "Gunay",
        "Gunel",
        "Gwendolyn",
        "Hadley",
        "Hailey",
        "Haley",
        "Hallie",
        "Hana",
        "Hannah",
        "Harley",
        "Harlow",
        "Harmony",
        "Harper",
        "Hatice",
        "Hattie",
        "Haven",
        "Hayden",
        "Hazel",
        "Heaven",
        "Heidi",
        "Hekla",
        "Helen",
        "Helena",
        "Helmi",
        "Holly",
        "Hope",
        "Ida",
        "Ilina",
        "Inês",
        "Ingrid",
        "Inji",
        "Ioanna",
        "Irati",
        "Irina",
        "Iris",
        "Isabel",
        "Isabella",
        "Isabelle",
        "Isla",
        "Ivaana",
        "Ivalu",
        "Ivana",
        "Ivy",
        "Izabella",
        "Izaro",
        "Jacqueline",
        "Jada",
        "Jade",
        "Jana",
        "Jane",
        "Jasmine",
        "Jayla",
        "Jazlyn",
        "Jázmin",
        "Jelena",
        "Jenna",
        "Jennifer",
        "Jessica",
        "Jessica",
        "Jimena",
        "Joanna",
        "Jocelyn",
        "Jolene",
        "Jordan",
        "Jordyn",
        "Josefine",
        "Josephine",
        "Josie",
        "Journee",
        "Journey",
        "Jovana",
        "Joy",
        "Julia",
        "Julia",
        "Juliana",
        "Julianna",
        "Julie",
        "Juliet",
        "Juliette",
        "June",
        "Juniper",
        "Kaia",
        "Kailani",
        "Kaitlyn",
        "Kali",
        "Kamila",
        "Kamile",
        "Kamryn",
        "Kara",
        "Karla",
        "Karolína",
        "Katarina",
        "Kate",
        "Katherine",
        "Kathryn",
        "Katie",
        "Kayla",
        "Kaylani",
        "Kaylee",
        "Kayleigh",
        "Kehlani",
        "Keira",
        "Kejsi",
        "Kelsey",
        "Kendall",
        "Kendra",
        "Kennedi",
        "Kennedy",
        "Kensley",
        "Kenzie",
        "Khloe",
        "Kiara",
        "Kimberly",
        "Kimmernaq",
        "Kinley",
        "Kinsley",
        "Kira",
        "Klea",
        "Konstantina",
        "Konul",
        "Kristina",
        "Kristýna",
        "Kseniya",
        "Kyla",
        "Kylee",
        "Kylie",
        "Kyriaki",
        "Laia",
        "Laila",
        "Lainey",
        "Lamija",
        "Lana",
        "Lara",
        "Laura",
        "Lauren",
        "Layla",
        "Leah",
        "Leah",
        "Leandra",
        "Leia",
        "Leighton",
        "Leila",
        "Leilani",
        "Leja",
        "Lejla",
        "Lena",
        "Lenna",
        "Lennon",
        "Leonor",
        "Lexi",
        "Leyla",
        "Lia",
        "Liana",
        "Liepa",
        "Liisa",
        "Lila",
        "Lilah",
        "Liliana",
        "Lillian",
        "Lilly",
        "Lina",
        "Ljiljana",
        "Lola",
        "Londyn",
        "Lorelei",
        "Lotte",
        "Louise",
        "Luca",
        "Lucia",
        "Luciana",
        "Lucie",
        "Lucille",
        "Lucy",
        "Luna",
        "Lydia",
        "Lyla",
        "Lyric",
        "Mabel",
        "Maci",
        "Mackenzie",
        "Maddison",
        "Madeleine",
        "Madeline",
        "Madelynn",
        "Madilyn",
        "Madison",
        "Maeve",
        "Maggie",
        "Magnolia",
        "Maisie",
        "Maja",
        "Makayla",
        "Makenna",
        "Makenzie",
        "Malak",
        "Malaysia",
        "Malen",
        "Malia",
        "Maliyah",
        "Maneh",
        "Manon",
        "Margaret",
        "Margarida",
        "Margot",
        "Margrét",
        "Mari",
        "Maria",
        "Maria",
        "Mariah",
        "Mariam",
        "Mariami",
        "Mariana",
        "Mariana",
        "Marie",
        "Marija",
        "Mariya",
        "Marlee",
        "Marley",
        "Marta",
        "Martina",
        "Martine",
        "Mary",
        "Marya",
        "Maryam",
        "Maša",
        "Matilda",
        "Matilde",
        "Maya",
        "Mckenna",
        "Mckenzie",
        "Mckinley",
        "Melanie",
        "Melisa",
        "Melissa",
        "Melody",
        "Merjem",
        "Meryem",
        "Mia",
        "Mia",
        "Michaela",
        "Michelle",
        "Mikayla",
        "Mila",
        "Milana",
        "Milani",
        "Milica",
        "Millie",
        "Mira",
        "Miracle",
        "Miranda",
        "Miriam",
        "Mirjana",
        "Molly",
        "Molly",
        "Mya",
        "Myla",
        "Myra",
        "Naasunnguaq",
        "Nadia",
        "Nahia",
        "Naomi",
        "Nareh",
        "Natalia",
        "Natálie",
        "Nathalie",
        "Nayeli",
        "Nehir",
        "Nela",
        "Nevaeh",
        "Neža",
        "Nia",
        "Nia",
        "Nicole",
        "Nika",
        "Nikol",
        "Nilay",
        "Nina",
        "Nina",
        "Nisanur",
        "Nivi",
        "Noa",
        "Noelle",
        "Noemi",
        "Noor",
        "Nora",
        "Norah",
        "Nova",
        "Nuray",
        "Nyla",
        "Nylah",
        "Oakley",
        "Oaklyn",
        "Octavia",
        "Olga",
        "Olive",
        "Olivia",
        "Ophelia",
        "Paige",
        "Paislee",
        "Paisley",
        "Panagiota",
        "Paninnguaq",
        "Paraskevi",
        "Paula",
        "Payton",
        "Penelope",
        "Petra",
        "Peyton",
        "Phoebe",
        "Phoenix",
        "Pihla",
        "Pipaluk",
        "Piper",
        "Polina",
        "Presley",
        "Quinn",
        "Rachel",
        "Radmila",
        "Raegan",
        "Raelyn",
        "Raelynn",
        "Raven",
        "Raya",
        "Reagan",
        "Rebecca",
        "Reese",
        "Regina",
        "Remi",
        "Riley",
        "Rita",
        "River",
        "Ronja",
        "Rosalie",
        "Rose",
        "Rose",
        "Rosemary",
        "Rowan",
        "Ruby",
        "Ruth",
        "Rylee",
        "Ryleigh",
        "Rylie",
        "Sabrina",
        "Sadie",
        "Samantha",
        "Samara",
        "Sandra",
        "Sara",
        "Sarah",
        "Sarah",
        "Sarai",
        "Savannah",
        "Saylor",
        "Scarlet",
        "Scarlett",
        "Selah",
        "Selena",
        "Serena",
        "Serenity",
        "Serife",
        "Sevda",
        "Sevinj",
        "Shelby",
        "Sienna",
        "Sierra",
        "Simona",
        "Skye",
        "Skylar",
        "Skyler",
        "Sloane",
        "Snezana",
        "Sofia",
        "Sofie",
        "Sofiya",
        "Sophia",
        "Sophie",
        "Stella",
        "Stephanie",
        "Summer",
        "Suzana",
        "Sydney",
        "Sylvia",
        "Talia",
        "Tarana",
        "Tatiana",
        "Tatum",
        "Taylor",
        "Teagan",
        "Teodora",
        "Tereza",
        "Tessa",
        "Tetyana",
        "Thea",
        "Trinity",
        "Ugne",
        "Urte",
        "Uxue",
        "Valentina",
        "Valeria",
        "Valerie",
        "Vanessa",
        "Vasiliki",
        "Venla",
        "Vera",
        "Veronica",
        "Vesna",
        "Victoria",
        "Vilte",
        "Violet",
        "Violeta",
        "Vivian",
        "Viviana",
        "Vivienne",
        "Vusala",
        "Willa",
        "Willow",
        "Wilma",
        "Winter",
        "Ximena",
        "Yagmur",
        "Yaretzi",
        "Yasmine",
        "Yekaterina",
        "Yelena",
        "Yelyzaveta",
        "Yoana",
        "Yulia",
        "Zahra",
        "Zala",
        "Zara",
        "Zariah",
        "Zehra",
        "Zeynep",
        "Zoë",
        "Zoey",
        "Zoja",
        "Zuri",
        "Zuzanna",
        "Akari",
        "Asahi",
        "Haru",
        "Himari",
        "Hina",
        "Ichika",
        "Misato",
        "Niki",
        "Rei",
        "Ren",
        "Riku",
        "Sakura",
        "Sara",
        "Sora",
        "Yua",
        "Yui",
        "Yuma",
    ],
    "oracle-character-name-lastname-result": [
        "Adams",
        "Alexander",
        "Allen",
        "Allen",
        "Anderson",
        "Bailey",
        "Baker",
        "Barnes",
        "Bell",
        "Bennett",
        "Brooks",
        "Brown",
        "Bryant",
        "Butler",
        "Campbell",
        "Carter",
        "Clark",
        "Coleman",
        "Collins",
        "Cook",
        "Cooper",
        "Cox",
        "Davis",
        "Diaz",
        "Edwards",
        "Evans",
        "Flores",
        "Foster",
        "Garcia",
        "Gonzales",
        "Gonzalez",
        "Gray",
        "Green",
        "Griffin",
        "Hall",
        "Harris",
        "Hayes",
        "Henderson",
        "Hernandez",
        "Hill",
        "Howard",
        "Hughes",
        "Jackson",
        "James",
        "Jenkins",
        "Johnson",
        "Jones",
        "Kelly",
        "King",
        "Lee",
        "Lewis",
        "Long",
        "Lopez",
        "Martin",
        "Martinez",
        "Miller",
        "Mitchell",
        "Moore",
        "Morgan",
        "Morris",
        "Murphy",
        "Nelson",
        "Nguyen",
        "Parker",
        "Patterson",
        "Perez",
        "Perry",
        "Peterson",
        "Phillips",
        "Powell",
        "Price",
        "Ramirez",
        "Reed",
        "Richardson",
        "Rivera",
        "Roberts",
        "Robinson",
        "Rodriguez",
        "Rogers",
        "Ross",
        "Russell",
        "Sanchez",
        "Sanders",
        "Scott",
        "Simmons",
        "Smith",
        "Stewart",
        "Taylor",
        "Thomas",
        "Thompson",
        "Torres",
        "Turner",
        "Walker",
        "Ward",
        "Washington",
        "Watson",
        "White",
        "Williams",
        "Wilson",
        "Wood",
        "Wright",
        "Young",
        "Chiba",
        "Endō",
        "Fujii",
        "Fujita",
        "Fujiwara",
        "Fukuda",
        "Hasegawa",
        "Hashimoto",
        "Hayashi",
        "Hirano",
        "Ikeda",
        "Inoue",
        "Ishida",
        "Ishii",
        "Ishikawa",
        "Itō",
        "Iwasaki",
        "Kaneko",
        "Katō",
        "Kimura",
        "Kobayashi",
        "Kojima",
        "Kondō",
        "Maeda",
        "Masuda",
        "Matsuda",
        "Matsui",
        "Matsumoto",
        "Miura",
        "Miyamoto",
        "Miyazaki",
        "Morita",
        "Murakami",
        "Nakagawa",
        "Nakamura",
        "Nakano",
        "Nakashima",
        "Nakayama",
        "Nishimura",
        "Noguchi",
        "Okada",
        "Okamoto",
        "Ono",
        "Saitō",
        "Sakai",
        "Sakamoto",
        "Sasaki",
        "Satō",
        "Shibata",
        "Shimada",
        "Shimizu",
        "Suzuki",
        "Takagi",
        "Takahashi",
        "Takeda",
        "Takeuchi",
        "Tamura",
        "Tanaka",
        "Watabe",
        "Watanabe",
        "Yamada",
        "Yamaguchi",
        "Yamamoto",
        "Yamashita",
        "Yamazaki",
        "Yokoyama",
        "Yoshida",
    ],
    "oracle-character-look-result": [
        "Accented",
        "Accompanied",
        "Adorned",
        "Aged",
        "Alluring",
        "Armed",
        "Armored",
        "Athletic",
        "Attractive",
        "Augmented",
        "Concealed",
        "Distracted",
        "Eccentric",
        "Energetic",
        "Flashy",
        "Graceful",
        "Grim",
        "Haggard",
        "Ill-equipped",
        "Imposing",
        "Large",
        "Mutated",
        "Plain",
        "Poised",
        "Scarred",
        "Scruffy",
        "Shifty",
        "Sickly",
        "Slight",
        "Swaggering",
        "Tattooed",
        "Threatened",
        "Uncanny",
        "Visibly disabled",
        "Weathered",
        "Well-equipped",
        "Wiry",
        "Wounded",
        "Youthful",
    ],
    "oracle-character-disposition-result": [
        "Helpful",
        "Friendly",
        "Cooperative",
        "Curious",
        "Indifferent",
        "Suspicious",
        "Wanting",
        "Desperate",
        "Demanding",
        "Unfriendly",
        "Threatening",
        "Hostile",
    ],
    "oracle-character-first-impressions-result": [
        "Painfully thin, chain smokes",
        "Athletic and wiry, huffing fast food",
        "Bulky, obsolete cyberaudio 'domes'",
        "Bleeding gums, bloodshot eyes",
        "Sad looking, distracted by cell phone",
        "Many interface plugs, tattooed labels",
        "Doughy and unhealthy looking",
        "Confident, highly polished, vinyl coat",
        "Sophisticated, manipulative",
        "Cold and predatory demeanour",
        "Pale and sullen, pleasingly stylish",
        "Business like, gum chewer, sniffs",
        "Square face, with small, darting eyes",
        "Ill fitting clothes and bad teeth",
        "Pair of skinny plastic cyber arms",
        "Garish pink jaw, yellow acrylic teeth",
        "rugged, practical and outdoorsy",
        "Substandard gender reassignment",
        "Prominent implant branding",
        "Dreadlocks, worn leather coat",
        "Seems eerily artificial, very attractive",
        "unintelligent, aggressive, pock marks",
        "Mismatched optics, black turtle neck",
        "Overweight and dirty, layered cloths",
        "engorged musculature due to grafts",
        "Furtive and on edge, unkempt, tattoos",
        "Misshapen by heavy augmentation",
        "Narcotic haze, fidgety hands, shabby",
        "loud, camp, and showy, anaemic",
        "Weary, apathetic, animated clothing",
        "Acts deaf but isn't, knows people",
        "Boxy e-cig, coat/hoodie, mirrorshades",
        "Shy and apologetic, rubber raincoat",
        "Oily skin, constantly checks watch",
        "Oddball dress sense, way too literal",
        "long hair, metal fan in downtime",
        "Trashy, overtly sexual, self-loathing",
        "Overclocked nervous system, sweats",
        "Conservative, business-like",
        "Toned, adjusts latest style clothes",
        "Obvious cosmetic surgeries",
        "White enamel cyberlimb; expensive",
        "Gangsta bling, lisps, friendly",
        "Permanent plastic rictus grin",
        "highly strung, with overly long fingers",
        "Pushed for time, bulky backpack",
        "Poorly groomed, with a raspy voice",
        "Focused on AR, poor listener",
        "Workwear under overcoat, nods sagely",
        "Thick foreign accent, glowing optics",
    ],
    "oracle-character-profession-background-result": [
        "lounge or Bar Manager",
        "Bouncer or Private Security",
        "Aero Pilot",
        "researcher or Data Analyst",
        "Street <a href=\"/oracles/faction-oracles#street-gangs\">Gang</a> Thug",
        "lab Worker",
        "Street Kid(s)",
        "Gambler or Con Artist",
        "uber or limo Driver",
        "<a href=\"/oracles/character-oracles#fixer\">Fixer</a>",
        "Designer",
        "Pimp",
        "Corporate Worker / Sarariman",
        "<a href=\"/oracles/character-oracles#corporate-aristocrat\">Corporate Aristocrat</a>",
        "<a href=\"/oracles/character-oracles#street-walker\">Sex Worker</a> or Puppet",
        "Celeb",
        "<a href=\"/oracles/character-oracles#law-enforcement\">City Beat Cop</a>",
        "Company exec",
        "Drone Wrangler or remote Operator",
        "Service Staff or Store Worker",
        "Freelance Media",
        "Thief or Fence",
        "<a href=\"/oracles/character-oracles#hacker\">hacker</a>",
        "<a href=\"/oracles/character-oracles#merc\">Military Veteran</a>",
        "Syndicate Footsoldier",
        "Smuggler",
        "Bounty hunter",
        "<a href=\"/oracles/character-oracles#hacker\">Cabbie</a>",
        "homeless Person",
        "Drug Dealer",
        "<a href=\"/oracles/character-oracles#gangbanger\">Gangbanger</a>",
        "City Inspector or Auditor",
        "Syndicate Boss",
        "Techie",
        "unemployed (Increased leisure Citizen)",
        "Corporate Soldier",
        "Bioware Tech",
        "Factory Worker",
        "Scavenger",
        "Corporate Agent",
        "Doctor or Street Medic",
        "Detective",
        "Online Business Person",
        "Store Manager",
        "<a href=\"/oracles/character-oracles#merc\">Solo or Mercenary</a>",
        "Killer or Psycho",
        "Transport Worker",
        "Aristocrat or Independently Wealthy",
        "refuse or recyc Worker",
        "Psych evaluator",
        "emergency Worker (EMT, nurse, paramedic, fire fighter)",
        "Government Agent",
        "Scientist",
    ],
    "oracle-character-revealed-aspect-result": [
        "Addicted",
        "Adventurous",
        "Afflicted",
        "Aggressive",
        "Ambitious",
        "Angry",
        "Anxious",
        "Apathetic",
        "Bitter",
        "Boastful",
        "Boisterous",
        "Bold",
        "Brave",
        "Careless",
        "Cautious",
        "Charismatic",
        "Clever",
        "Conceited",
        "Confident",
        "Confused",
        "Connected",
        "Corrupted",
        "Cowardly",
        "Creative",
        "Critical",
        "Cruel",
        "Cunning",
        "Dangerous",
        "Deceitful",
        "Defiant",
        "Determined",
        "Disabled",
        "Doomed",
        "Driven",
        "Dying",
        "Envious",
        "Experienced",
        "Faithful",
        "Generous",
        "Gifted",
        "Greedy",
        "Grief-stricken",
        "Handy",
        "Hardhearted",
        "Haunted",
        "Honorable",
        "Hot-tempered",
        "Impulsive",
        "Incompetent",
        "Independent",
        "Infamous",
        "Influential",
        "Insensitive",
        "Insightful",
        "Intelligent",
        "Intolerant",
        "Ironsworn",
        "Kind",
        "Law-abiding",
        "Lonely",
        "Loving",
        "Loyal",
        "Manipulative",
        "Oblivious",
        "Obsessed",
        "Oppressed",
        "Passive",
        "Powerful",
        "Proud",
        "Quiet",
        "Quirky",
        "Rebellious",
        "Reclusive",
        "Relaxed",
        "Remorseful",
        "Resourceful",
        "Secretive",
        "Selfish",
        "Sociable",
        "Stealthy",
        "Stern",
        "Stingy",
        "Stoic",
        "Strong",
        "Stubborn",
        "Successful",
        "Suspicious",
        "Talented",
        "Technical",
        "Timid",
        "Tolerant",
        "Tough",
        "Vengeful",
        "Violent",
        "Wary",
        "Watchful",
        "Weak",
        "Weary",
        "Wild",
        "Wise",
    ],
    "oracle-character-vice-addiction-type-result": [
        "Child-like Sex Dolls or Synthetics",
        "Prohibited Designer Narcotics",
        "Street-legal Substance, But harmful - Alcohol / Caffeine / Nicotine",
        "SimStim / SimSense / VR Gaming",
        "Atrocity / Snuff / Gore Images or Footage",
        "Prostitutes",
        "Pornographic Material (Particular Acts or Fetish?)",
        "Bizarre Fetish Wear or Activity",
        "Pain/Sexual Violence (Towards Self or Others)",
        "Abuses Synthetic (or real) Animals",
        "Shoplifting",
        "Pyromania / Arson",
        "Compulsive shopping",
    ],
    "oracle-character-vice-addiction-level-result": [
        "Take It Or leave It",
        "light Interest",
        "Ghoulish Fascination",
        "If The Opportunity Arises",
        "regular routine user",
        "Intrinsic To Personality",
        "Only To Destress",
        "Needed To Function",
        "unhealthy Obsession",
        "All Consuming",
    ],
    "oracle-character-tattoo-design-result": [
        "Skulls/Bones",
        "roses/Flowers",
        "Crossed Guns/Blades",
        "Snake/reptile",
        "Dragon/Mythical Beast",
        "Animal/Predator",
        "Nautical",
        "Script/Message/Numbers",
        "Geometric/Abstract",
        "Technology/Circuitry",
    ],
    "oracle-character-tattoo-style-result": [
        "Mexican/Aztec",
        "Pixilated/Computerised",
        "Photorealistic Colour/Grey",
        "Migratory/Animated",
        "Oriental",
        "Tribal",
        "rockabilly Punk",
        "Solid Monotone Graphics",
        "Neon Glow",
        "Old School Blue Ink",
        "Glow in the Dark / UV Reactive",
    ],
    "oracle-character-tattoo-location-result": [
        "Back/Shoulders",
        "Bicep/Forearm",
        "hip/Groin",
        "Face/Scalp",
        "Stomach",
        "lower leg/Calf",
        "Thigh",
        "ribs/Chest",
        "Neck/Collar Bone",
        "Buttock(s)",
        "Lower back",
        "Hand(s)",
    ],
    "oracle-character-sexual-orientation-result": [
        "Homosexual",
        "Heterosexual",
        "Asexual",
        "Adaptable (cybernetics)",
        "Bisexual",
        "Pansexual",
    ],
    "oracle-character-gender-result": [
        "Male",
        "Male",
        "Male",
        "Male",
        "Female",
        "Female",
        "Female",
        "Female",
        "Androgyne",
        "Androgyne",
        "Agender",
    ],
    "oracle-flashy-cyberware-type-result": [
        "Inconspicuous; They Look natural or unaugmented",
        "Fashionable; all of their upgrades are top-shelf brands and put aesthetics over function",
        "Practical; all of their cyberware looks to have a very usable function",
        "Mishmash of different brands and styles. Fashion is not their priority.",
        "Battle-worn: Military grade, scratched, camo-paint, etc.",
        "Brand-new: Shiny and Chrome; latest models.",
        "Old; many gens ago, some are visibly malfunctioning.",
        "Badly maintained; rusty, unclean, servos doing screeching noises.",
        "Aesthetically pleasing; colors combined with outfit and hairdo.",
        "Obviously heavy-modded but with discrete paintjobs (carbon fiber or matte-black).",
    ],
    "oracle-flashy-cyberware-cybereyes-result": [
        "Chromed gold with no visible iris or pupil",
        "Glows in a neon color (pink, purple) with no visible iris or pupil",
        "Has a projection system on the front showing a short animated image (waterfall, nuclear explosion, adult film) instead of the expected reflection in the cornea",
        "Has baseball-sized cybereyes that make them look like a dark future animated character; either bought pre-2015 era eyes or wanted the look when biosculpting.",
        "Cybereye has a micro-video camera mounted on an arm above the surface of the eye which tracks separately from the eye itself",
        "Cybereye's multiple visual options are configured as a row of thin vertical slits in the center of a totally robotic-looking eye",
        "Cybereye's multiple options are small round lenses in the center of a rotating robotic \"iris\"; as the owner changes views, the iris spins to the appropriate lens with an audible click",
        "Multi-optic mount with biosculpting that looks like two eyes stacked in the eye sockets and a forehead-mounted third eye with sideways eyelid.",
        "Normal-looking eye except, with careful inspection, one can see the distinctive reflection of a microvideo camera sensor behind the pupil",
        "Center of eye literally extends out beyond the surface of the eye for telescopic zoom or microoptic examination",
    ],
    "oracle-flashy-cyberware-cyberarms-result": [
        "Chipped clear plastic over steel, in the style of Central American War-era prosthetics",
        "Old Soviet model: blued steel, no myomer, all hydraulics",
        "Hand, wrist, and forearm unnaturally peel apart with a cascade of mechanic ticking noises to reveal the cyberarm's tools or weapons",
        "Nomad special: beat up cyberarm with patches of multiple types of scrap steel, and at least one forearm and/or bicep hydraulic (replaced with a cleverly jury-rigged component meant for a vehicle or construction equipment).",
        "Cyberarm's coating has a lovingly airbrushed rendition of an attractive cowgirl in hat, skimpy buckskin top and bikini bottom, and cowboy boots lying seductively across a background of a waving \"Free State of Texas\" flag",
        "Cyberarm is covered in translucent white silicone, that looks like it would feel tacky and uncomfortable to the touch. Underneath the covering, bright pastel LEDs blink in a pattern to reveal the metal skeleton underneath.",
        "You wouldnt't know it is a cyberarm until the hidden pop-up submachine gun bursts out of it, spraying shredded fake skin everywhere",
        "Has a custom cyberhand: It splits the hand all the way down the forearm into two independent half-hands on their own forearm \"stalks\".",
        "Exterior is metal polished; shiny with dozens of lines of engraved classical Chinese",
        "A lightly, sea-salt corroded model, common among sea nomads with an obvious grapple hand and pop-up flaregun",
    ],
    "oracle-flashy-cyberware-cyberlegs-result": [
        "Have a pair of integral, stiletto-heeled cyberfeet, that don't seem to impair walking at all.",
        "Pants can't quite conceal the bulging hydraulics for jump boosters.",
        "One leg is meat, the other is a faux, ivory-looking cyberleg with gold accents; they're wearing a skirt or have cut the leg off their pants to show it off.",
        "A modified Realskinn covering that doesn't make the leg look real, with metal and flesh looping in on themselves.",
        "Foot looks like the end of a stabilizing leg for industrial machinery.",
        "Nonmoving surfaces are covered with cartoon stickers.",
        "Legs contain clamps to lock onto posts of a custom smartbike for better grip during street racing.",
        "Casing on calf contains scabbard for combat knife; scabbard is smart-controlled and unlocks the blade and pops it up on mental command",
        "Instead of traditional skate feet, a triangular cluster of three rolling balls are on each foot. They can lock to walk.",
    ],
    "oracle-flashy-cyberware-blades-result": [
        "Razorblades pop out from under fake, long fingernails.",
        "Thin blades pop out three inches from knuckles when fist is closed.",
        "Blades uncurl from heretofore unseen slots on the back of each finger when the person makes a fist.",
        "Two curved blades pop from each side of the palm when the NPC closes their fist, making a rough \"taurus symbol\" shape with the fist in the center and the blades as horns.",
        "Tiger-like claws extend from between the fingers.",
        "Steel, talon-like claws pop over two pairs of fingers and the thumb, giving them a hand that looks like a predatory bird's foot.",
        "A three-inch wide, two-and-a-half-foot long sword pops out of the cyberarm.",
        "The cyberhand extends slightly on its wrist and two large blades pop out the sides, turning the arm into a cyber-axe.",
        "A curved, serrated blade pops out of the side of their arm, making the entire forearm a bladed surface.",
        "Small \"mantis blades\" extend from the elbow.",
    ],
    "oracle-flashy-cyberware-plugs-result": [
        "Paired ornate plugs on the temple.",
        "An almost invisible pair of plugs just below the jawline, covered with Realskinn flaps.",
        "Heavy duty wrist plugs with screw-to-tighten clamps, to secure the connection and prevent the cables from getting ripped out.",
        "Plugs have little soft plastic covers with a mascot character on them.",
        "Plugs in the back of the neck have a small (4\") retractable spool of integral interface cable so the plug can be taken to the front of the face to plug in.",
        "Jack-in integrated into face tattoos and implanted silver linings.",
    ],
    "oracle-character-corporate-aristocrat-personality-quirk-result": [
        "Buys endangered species, and mutilates them",
        "Drowns orphans in private swimming pool",
        "Androids of dead loved ones, used as servants",
        "Collects and catalogues DNA samples of rivals",
        "Lacks confidence and is extremely paranoid",
        "Compulsively records others while they sleep",
        "Hurts herself under stress",
        "Addicted to expensive synthetic opioids",
        "Enjoys watching people die",
        "Has a fondness for injured/disabled people",
        "Desires the top job at all costs",
        "Personal hacker collective headed by wayward nephew",
        "Likes their partners completely devoid of hair",
        "Once a spy for an ecoterrorist commune",
        "Literally afraid of being at street level",
        "Enjoys the sound of people crying",
        "Has a private army of desperate down-and-outs",
        "Worships the net, as if it were a divine entity",
        "Despises the voices of all those around him",
        "Derives pleasure from the fear of others",
        "has a paralyzing fear of the Biotech Division",
        "Believes the board are hostile to them, afraid to leave",
        "under the influence of a rogue AI",
        "requires nutrient baths several times a day",
        "Serial adulterer; compelled by faulty sex implant",
        "Always tells the truth",
        "Wants revenge on the CEO for unknown reasons",
        "Overly reliant on complex prediction algorithms",
        "Wants to die, but afraid of the afterlife",
        "Seeks to dominate fixer networks for own ends",
        "haunted by digital ghosts of those they've had killed",
        "A cosmetically altered double, living the dream",
        "Born 150 years ago, but looks only 25 years old",
        "hates their implants; they make them feel sick",
        "Blackmailed into submission by orbital clade",
        "Secret second life as a high class camgirl/boy",
        "Wants to kill their twin sibling and main rival",
        "Surprisingly normal",
        "has ‘precognitive’ dreams manipulated by a hacker",
        "Despises both daylight and bright artificial lighting",
        "Only wears clothes made by the indentured poor",
        "Closely monitors the children of business rivals",
        "Desires the utter destruction of the city",
        "A downlinked AI masquerading as human",
        "Obsessed with obscure, expensive fashion",
        "Believes the corporate elite are slaves to AIs",
        "Blackmailing corporates for money and favours",
        "Powerful intrusion software, but can’t work it",
        "Was in love with someone the PCs killed",
    ],
    "oracle-character-corporate-aristocrat-position-assets-result": [
        "Controls black tech imports",
        "Bribes the staff of their rivals",
        "Breeds biogenetic horrors",
        "Finest art collection in city",
        "hoards ‘occult’ objects",
        "Collector of antique technology",
        "Owns swathes of farmplexes",
        "Breeds & trains combat clones",
        "Owns & operates sex resorts",
        "Well regarded psychotherapist",
        "Security extremely loyal to them",
        "Owns assemblery districts",
        "expert in corporate law",
        "head of International retail",
        "Old money aristocratic family",
        "health & Safety executive",
        "exceptionally skilled hacker",
        "head of Administration",
        "head of BioDivision R&D",
        "Media Operations liaison",
        "Monitors company AI stable",
        "Current Chief executive Officer",
        "Wife/Husband of; controls access to CEO",
        "Popular decadent socialite",
        "Famous society tastemaker",
        "highly cosmetically enhanced",
        "Importer of pharmaceuticals",
        "employs the finest chefs",
        "Internal Security Director",
        "Poached from major rival",
        "Black Operations executive",
        "Decorated combat veteran",
        "Skilled investigator",
        "handsome economist",
        "ward winning marketeer",
        "CEO’s Physician",
        "Public relations executive",
        "human resources executive",
        "Company Security operative",
        "Oversees sales divisions",
        "Funniest company employee",
        "uniformed Security Manager",
        "CEO’s Personal Assistant",
        "Digital Security executive",
        "lovely child; society darling",
        "expert in cybernetic systems",
        "undervalued and overlooked",
        "universally feared",
        "resource management",
        "enhanced killer of some renown",
    ],
    "oracle-character-corporate-aristocrat-mannerisms-looks-result": [
        "Wears silk, furs and a monocle",
        "Black eyes, red trouser suits",
        "Short, bald, gruff, distracted",
        "Alcoholic, odd yet attractive",
        "Scarlett-haired, spiteful",
        "One-eyed, uses an assist frame",
        "Intense, passionate, green eyes",
        "Crude, jocular, artificial jaw",
        "rotund, elegant, sarcastic",
        "Obsequious, sharp intellect",
        "Proud, pitiless, pale blue eyes",
        "Mincing, meek, ruthless",
        "hairless, eager and awkward",
        "Plodding, multi-lingual, talkative",
        "limp, opulent, over privileged",
        "Furtive, argumentative, cynical",
        "Old, decrepit, almost immobile",
        "Chubby, ruddy, bespectacled",
        "Tedious, wheedling, androgynous",
        "light, frivolous, ironic hipster",
        "Dark haired, wears body armour",
        "Weak voice, thin-fingered, cold",
        "highly strung, middle-aged, pale",
        "Gracious, intelligent, seems kind",
        "Touchy, easily riled, sharp style",
        "Sentimental, fragile, wears white",
        "recounts outrageous stories",
        "Nervous, sweaty, sloppy",
        "Open, friendly, business-like",
        "Brusque, aging, cunning, twisted",
        "loyal to CEO, quiet, unassuming",
        "Grim, warlike, unbending, PTSD",
        "Somber, patient, sympathetic",
        "Greedy, lusty, barbaric and blunt",
        "understated, wears gloves, OCD",
        "Bulging eyes, veiny, creepy",
        "Jewel-covered fashionista, vain",
        "Abrupt, impatient, germ phobia",
        "Suspicious, excitable, hot temper",
        "Wary, detached, thin, aged",
        "universally liked, fat, generous",
        "energetic, black humour, bored",
        "Thin, wiry, long-nosed, stylish",
        "White-haired, speaks in whispers",
        "radiant, innocent, foolish",
        "Frivolous, envious, insecure",
        "Bitter, scarred, suspicious",
        "exposes/frames enemies, fearless",
        "Arrogant, devious, patronising",
        "Dark-eyed, clever, religious",
    ],
    "oracle-character-gangbanger-result": [
        "Gang leader/Boss",
        "Gang elder",
        "Gang Juve/Noob",
        "Gang Champion",
        "Gang Scout",
        "Gang leader’s Main Squeeze",
        "Gang leader’s leftenant",
        "Gang leader’s Main rival In Gang",
        "Gang’s loose Cannon",
        "Gang expert (steers gang’s main biz)",
        "Kid Wannabe",
        "loyal Gunman (ex-member)",
        "Sheltered Fugitive",
        "Gang Member’s Kid",
        "Former Gang Boss, Now Disgraced",
        "Gang leader’s Secret Concubine",
        "Gang’s Techie or ripperdoc",
        "Invalided or exiled Gang Member",
        "Gang’s Fixer",
        "Gang’s Idiot (the liability)",
    ],
    "oracle-character-law-enforcement-type-result": [
        "Plainclothes Detectives",
        "Uniformed Officers",
        "Tactical response unit",
        "Agents with clearly marked POLICE vests, flashing their ID badges",
        "Basic beat cops",
        "City cops wearing riot gear",
        "Special operations/SWAT team - milspec load out",
        "Private security force",
        "Corp security with heavy loadouts",
    ],
    "oracle-character-law-enforcement-activity-result": [
        "Approaching  suspect(s), or have just arrested suspect(s)",
        "Performing a street patrol, area or building search or conducting vehicle search",
        "Conducting an operation - raid, stake out, goods seizure",
        "Dealing with an apparent hostage situation or a suspect device",
        "Stopping citizens for questioning or performing stop-and-search operation",
        "In pursuit of suspect(s), either on foot or in vehicles",
        "Cordoning off the area (searching for suspect/securing a crime scene)",
    ],
    "oracle-character-law-enforcement-backup-result": [
        "Support Drones with Cameras, Tasers, Flechette Weapons",
        "Patrol Cars, Armoured Officers, SMGs/Shotguns",
        "SWAT Team; heavy/hard Armour, Combat rifles, Augmented",
        "heavy Support Mech;Teleoperated Walker, HMG and/or Missiles",
        "Powered Armour Suit; heavy Weapon, ECM, Grenade launchers",
        "Patrol hovercar with turret HMGs",
        "Small buzzdrones with cameras and flashers",
    ],
    "oracle-character-fixer-known-callsign-result": [
        "Olivia Chain",
        "Rob ‘Infidel’ Castro",
        "Gemini Benedict",
        "The Mask Maker",
        "Bradley Darrow",
        "Usman ‘Emir’ Kasim",
        "Mr Blank",
        "Alison Wonderland",
        "Ingenuity Jones",
        "The Chemist",
        "Darius November",
        "Mondo Hernandez",
        "Leon ‘The Tsar’ Arkov",
        "Sister Mercy",
        "Wise Melon",
        "The Babel-Mother",
        "Miguelito Fernandez",
        "Able Kane",
        "Desmond Crisis",
        "Slick Franklin",
        "Wendel Goldberg",
        "Pappa Midnight",
        "Reality Black",
        "Mr Skin",
        "‘Viper’ Joe Demarco",
        "Tanglegenes",
        "Charisma Valentine",
        "The Spider Sisters",
        "Veracity Solomon",
        "General Grabber",
        "Henry Jericho",
        "Warsaw",
        "Lucius Warbaby",
        "Jacob Smolensky",
        "Simon Church",
        "Octavius Ballinger",
        "Dr Ishimura",
        "Friday Dias",
        "Friday Dias",
        "Oni Tokugawa",
        "Zero Ballard",
        "The Shaper",
        "Ferdinand Kingston",
        "Harry-san",
        "Rico Eisendüller",
        "October Talisi",
        "Mickey The roach",
        "The Somalian",
        "Dr Fassbinder",
    ],
    "oracle-character-fixer-personality-quirk-result": [
        "Despises being based out of the local Consumertopia™",
        "Once an indentured child, tends to sympathise too much",
        "Many implants, diminished empathy, they're not afraid to kill",
        "records all business conversations covertly, just in case",
        "lives an opulent lifestyle well beyond their means",
        "head of the so-called Flesh Cartel, self-styled King of Pimps",
        "Into cheap sex dolls, leaving scars due to latex allergies",
        "hormone-locked ‘teen’ (actually 30); outrageous flirt",
        "Some-time stripper and camgirl/boy, lover taught them to shoot",
        "relishes the power their tailored drugs give them over others",
        "Struggles with a debilitating narcotic dependency",
        "Desperate to keep their children a secret from their enemies",
        "Being blackmailed by corporate aristocrat Fatima Rasheed",
        "Cold, soulless narcissist, proud of their migrating glo-tatts",
        "Chubby, jovial and a from registered independent nation-state",
        "Just one AI of a distributed identinet, with shared awareness",
        "Deep cover cop, losing themselves to their current alternate life",
        "Surprisingly conservative, suburban, family-centric lifestyle",
        "unassuming ex-ganger, ex-Catholic priest/nun, ex-porn actor/actress",
        "Determined to make enough money to leave city behind",
        "Trying hard to care for elderly father permalinked to porn sims",
        "Well connected across the Pacific Prosperity Sphere",
        "extremely ambitious, with an obvious superiority complex",
        "Must painfully inject nanites hourly due to congenital illness",
        "Paranoid, wears spiderweave body-glove under clothing",
        "Obsessively collects snakes, liking them more than people",
        "Secretly employed by corporation, follows their instructions",
        "Twin clones, supermodel hot, operate Orbital Mafia franchise",
        "Back doors for Cambodian data-havens, but fears reprisals",
        "hypochondriac; terrified their cheap organ implants will fail",
        "Can only be reached by using a particular hacked pay phone",
        "Over-confident emancipated juvenile; sexual deviant",
        "Walking the line between worlds exacerbates heart problem",
        "Goods traceable by cops to avoid brainwipe sentence",
        "Believes they are a synthetic controlled by corporations",
        "Finances a stable of Freak Fighters, all of whom they despise",
        "Disgusted by the work they do, drinks to block it out",
        "Financed by the Binh Xuyen, but looking for a way out",
        "Aggressive vigilance suite protects tiered neural processors",
        "Overly enthusiastic and extremely sadistic; loves <a href=\"/oracles/misc-oracles#music-genre--subculture-style\">niche-genre music</a>",
        "loaded with enough intelligent bioplastic that they can’t die",
        "The strippers at their club are all biomodded clones of themselves",
        "Stressed due to several secret families with different concubines",
        "has the best of intentions, but is deeply unreliable",
        "Self-doubt, but wants to be head-hunted by a corporation",
        "No self worth, always high, easily distracted",
        "Suffers from PTSD, nightmares, has poorly timed flashbacks",
        "Struck off, operates a failing back street clinic, depressed",
    ],
    "oracle-character-fixer-profession-result": [
        "Talent Agent",
        "repoman",
        "Black Marketeer",
        "Identities Broker",
        "Transporter/Mover",
        "Skin Trader/Pimp",
        "Personality Smuggler",
        "Tech Dealer",
        "Secrets hunter",
        "Drug Designer",
        "Wheelman",
        "Talent Scout",
        "Syndicate Diplomat",
        "Drug Pusher",
        "Go-Between",
        "Leader of a Hacker Stable",
        "Tech Fence",
        "Prowler/Thief",
        "Smuggler",
        "Squealer",
        "Bookie",
        "Gun runner",
        "Procurement",
        "Electronics handler",
        "Blackmailer",
        "Data Crypt Owner",
        "Nanotech Dealer",
        "Mediator",
        "Loanshark",
        "Information Broker",
        "Weapon Fence",
        "Ghost Accountant",
        "Gang liaison",
        "Finder",
        "Bent lawyer",
        "Vehicle Dealer",
        "Contract Facilitator",
        "Bioware Fence",
        "Digital Manipulator",
        "Madam",
        "Troubleshooter",
        "Persuader",
        "Bioware handler",
        "Club Owner",
        "Landlord",
        "Med Tech Dealer",
        "Negotiator",
        "Synth Pimp",
        "Cleaner",
        "Implant Dealer",
    ],
    "oracle-character-fixer-mannerisms-looks-result": [
        "Boxy, plain, emotion suppression chips",
        "Skinny jeans, vinyl bomber jacket, joker",
        "Elfin, humourless, pale duster, blue hair",
        "Muscular, balding, sophisticated, diligent",
        "Well groomed, youthful, boastful, snob",
        "Ostentatious, traditional, bearded, careful",
        "Blistered, strong cologne, shiny blue suit",
        "Willowy, hauntingly beautiful, kimonos",
        "Tall, lithe and busty, probing, determined",
        "Oily, obsequious, formal and spiteful",
        "Pale, shaky, numerous vehicle link plugs",
        "Approachable, guarded, sharp dresser",
        "Shaven head, grey suit, bulky, sombre",
        "exhibitionist, tease, clear vinyl raincoat",
        "Fat, confident, well-mannered, Mao suits",
        "Geisha-chic, teenage fashion, dark eyed, cold",
        "Deep turquoise leather coat, friendly",
        "Impeccably dressed, punctual, vindictive",
        "Neo-romantic floppy fringe, tux, relaxed",
        "Nervous, cautious, trenchcoat, greasy hair",
        "Tired and frazzled, thinning curly hair, fat",
        "Tech-savvy, confident, ebony skinned",
        "Arrogant, condescending, casual dress",
        "Small, unwashed, world weary, tired",
        "Black suits & shirts, gold tie, aggressive",
        "limps, thin-limbed, pastey, loose silks",
        "Conservative trouser suits, on edge, delays",
        "Seductive, elegant, hot tempered, black",
        "easily pleased, layered hoodies, shades",
        "Middle-aged, dark denim, big revolvers",
        "Flamboyant, mincing, fidgets, gloved",
        "Grubby punk, pumped, baritone voice",
        "Oversized army jacket, cigars, big gun",
        "Chunky, crumpled suit, sweaty, balding",
        "Sergio Tacchini track suits, anxious, tag",
        "expensive shirts, gold rings, robotic",
        "Smoker, inscrutable, leisure suits, clean",
        "reeks of booze, dirty jeans, serious",
        "Soft face, scarlett bobbed hair, ruthless",
        "Monovisor, suit, raincoat, katana, calm",
        "Turtle necks, chrome hands, wild eyed",
        "Old, emaciated, bitter and suicidal",
        "hawaiian shirts, cargo pants, gregarious",
        "Squat, solid, stubbled chin, dark vinyl coat",
        "enthusiastic, knitwear, sandals, ponytail",
        "Coffee-skinned, afro weave, violet lipstick",
        "Coverall, micro tools, air hypo, giddy",
        "Tall, lean, narrow-faced, red suit, dreads",
        "long black hair, goatee, lethargic, cynical",
    ],
    "oracle-character-merc-personality-quirk-result": [
        "Maddeningly faulty cyberaudio feeds them your comms",
        "elite spec-ops in the Polar War, tired of fighting, sociopath",
        "Camp, flirtatious, enjoys intimidating straights, brutal brawler",
        "engaged in messy affair with unstable corporate aristocrat",
        "rogue vat-grown killer, protects paralysed gene-tech they love",
        "Gaijin with minor yakuza gumi, despised, mole for russians",
        "unapologetic hipster, support from Armenian hacker clade",
        "lives in exquisite houseboat, requires seclusion to stay sane",
        "Overweight hawaiian, raised in foster homes, big drinker",
        "Vagrant combat veteran with augmentation sickness",
        "hounded by AI telemarketers, doesn't know why",
        "Just one last job and the luxury beach house in Goa is theirs",
        "Anti-depressants laced with nanites control their decisions",
        "underage and overclocked, way too eager to prove themselves",
        "Thinks they're a major player, has a lot of cousins called Spiros",
        "Argentine marine, autonomous defense net rebels against them",
        "heavily invested in Vornheim VR game, won't risk losing levels",
        "Frustrated surrealist artist, single parent, skilled killer",
        "Crippled as child, skeleton rebuilt, in constant pain, tough",
        "linear-frame-enhanced kick boxer, listens to K-Pop pre-op",
        "Cyborg veteran of Kashmir emergency, won’t leave witnesses",
        "late stage immunodeficiency infection, needs immunoboosters, nothing to lose",
        "Post-combat cleansing ritual using sage and Bible verse",
        "Mutilated in Freak Fight bout, suspects crime syndicate boss",
        "Former VDV paratrooper, Moldova veteran on war crimes list",
        "rumoured junkie, actually diabetic, saving for neo-pancreas",
        "Convert to Islam, featureless gunmetal face, six red optics",
        "Devout, worships the Papal AI as a god",
        "ex-Saudi GID, thermoptic camo, synthetic endorphin addict",
        "Cyberoptics feed their view to media brother who's using them",
        "Former head of security, killed execs family; they're guilt-ridden",
        "Doesn’t listen, tends to hit wrong targets, cannot drive",
        "KGB driver, Olympic skier and hunted whistleblower",
        "Former airport cleaner, conned into job by crime syndicate",
        "Can't reconcile job with married life, excellent danger sense",
        "Svetlana-Series-9 sex synthetic, fights severe violent urges",
        "Cares for crippled mentor, finds obligation a tiresome burden",
        "Indentured to fixer handler, treated as property",
        "Orbital assassin, amphetamine user, bright neon-green eyes",
        "Conflicted Buddhist, connoisseur of classic Blues artists",
        "Writes pithy anonymous diary blog, plans to write book",
        "Classically-trained pianist, combat medic, lives in their car",
        "Yogic guru, clean living, obsidian cyberarms",
        "Wealthy with an impressive property portfolio, soldiers for fun",
        "Western fan, feels most alive post-kill",
        "Wants to be master of own destiny, denies they're trapped",
        "No regard for collateral damage, keeps tropical fish",
        "lost entire family to wasting plague, inconsolable, suicidal",
        "Glitchy GPS, no direction sense, trackable, argumentative",
    ],
    "oracle-character-merc-tools-result": [
        "Flechette pistols",
        "Teleoperated drones",
        "hydraulic fists, bites",
        "Aware weapons LAN",
        "Spider venom rounds",
        "Ornate monokatana",
        "hunter-seeker rounds",
        "Pearl handled Glock",
        "Bulky laser rifle",
        "Scoped needle-rifle",
        "Monowire mines",
        "Implanted zhi dao",
        "exploding munitions",
        "Nerve-burner bombs",
        "3D printed QBZ-95",
        "railgun sniper",
        "Compound bow",
        "Sleek microwavers",
        "Dissolving Nanorounds",
        "Martial art techniques",
        "Antique UZI, SOPMODs",
        "Auto grenade launcher",
        "Drum-fed AK74",
        "Self-destructing gun",
        "Twin compact SMGs",
        "Charm-covered Steyr",
        "liquid nitrogen rounds",
        "Camo autoshotgun",
        "Ornate bladed fingers",
        "Incendiary rounds",
        "Flechette adapted M4",
        "Screamer grenades",
        "Big polymer revolvers",
        "hands-free trigger",
        "rifle with chatty AI",
        "Cortex bomb",
        "Bright Plastic SMG",
        "Chinese SMG clone",
        "Caseless KRISS Vector",
        "Brace of small pistols",
        "Scanner shielded gun",
        "Inbuilt Scorpion SMGs",
        "Crippler rounds",
        "Taser, monoknives",
        "Compact stutter-laser",
        "Disposable pistols",
        "Toxin-loaded needlers",
        "underslung blinder",
        "Full spectrum targeter",
        "Belt-fed chaingun",
    ],
    "oracle-character-merc-mannerisms-looks-result": [
        "Big, black, worn leather duster, irritable",
        "Sadistic, tattooed smart-armour link points",
        "Full body cyborg, crudely sprayed in neon colors",
        "likeable pothead, buff, always wears black",
        "Chips different personalities, sharp suits",
        "Suited, armour skin, afraid of dark, IR eyes",
        "Quiff, beard, tattoo sleeves, ear spacers",
        "Wears purple, plays sax, mood swings",
        "Pragmatic, funny, wears black duster",
        "hobo-chic, beanie hat, beard, tenacious",
        "Bleached spikes, wraparounds, agitated",
        "Brushed aluminium body armour, focused",
        "Sensitive to strong smells, heavy armour",
        "Teen, skinny jeans, army boots, hoodies",
        "Outmoded implants, retro-70s fashion",
        "Daddy issues, wears figure-hugging black",
        "Distracted, fantasist, wears black denim",
        "Motocross leathers, cyberbike, feminist",
        "Grey camo armour vest, always angry",
        "Scarred, dented, guarded, loose jumpsuit",
        "Cynical, risk taker, sickly, wears layers",
        "Theatrical, serious, black Ts, shades",
        "Wheezing, scarred, sportswear, gold chains",
        "Vicious, VR-trained clone, tight leathers",
        "Bald, goatee, utility vest, superstitious",
        "Slim cyborg, conservative, chaste, classy",
        "red leather jacket, corn rows, obsessive",
        "Athletic, hijab, full mirrored smart-visor",
        "Short mohawk, long coat, trusting",
        "nsanely ruthless, stylish, hunted",
        "Defensive, literal, squat, padded jackets",
        "Furtive, physically fit, chic, intimidating",
        "Sloppy, unprofessional, cheap casuals",
        "hen pecked, camos, buzz cut, rational",
        "Callous, irrational, needy, loose clothes",
        "Wirey, short, girlish, harajuku style, tired",
        "uneducated, easily manipulated, tagged",
        "Super-model looks, cat like grace, cold",
        "Shaved head, fame seeker, baggy combats",
        "Designer stubble, camo armoured jacket",
        "Muscular, tall, casuals, do-rags",
        "Self absorbed, baggy flight suits, sneakers",
        "Biker jacket, fingerless gloves, prude",
        "Well groomed, expensive clothes, open",
        "Plaid flannel, denim, cracked brown leather",
        "long, lank, black hair, chrome eyes, gaunt",
        "effeminate, black silks, raincoat, quick",
        "Carries photos, depressed, bulky flak vest",
        "Gum chewer, olive drab armour, moustache",
    ],
    "oracle-character-hacker-callsign-result": [
        "Moonshine",
        "Baby",
        "Memento",
        "Quirk",
        "Iron",
        "Monitor",
        "Tactic",
        "Stalker",
        "Agent Orange",
        "Akuma",
        "Aqua Kitty",
        "Ash Whirl",
        "Atom Five",
        "Autonomous",
        "Avatar Dragon",
        "Battle201",
        "Beast Mode",
        "Beemo",
        "Berserker",
        "Billy Headcrash",
        "Bit Rat",
        "Black Noise",
        "Blau Fish",
        "Bloodsport",
        "Blut Goll",
        "Brann",
        "Bright Loss",
        "Broke Owl",
        "Bullet Smack",
        "Bullfrog Chill",
        "Burn Zoo",
        "Cap Jaw",
        "Captain Sick",
        "Card Sage",
        "Cashbox",
        "Chaos Theory",
        "Chip Boy",
        "Circuit Lynk",
        "Claw Frog",
        "CloudGirl",
        "Combustible",
        "ComplexDream",
        "Cortical Mafia",
        "Crack Nobody",
        "Crank Wasp",
        "Credit Boy",
        "Crimson Hatch",
        "Crypto Warrior",
        "Cryptonic",
        "Daddy V",
        "Daemonbot",
        "Damu Bullseye",
        "Dancer",
        "Dark Blink",
        "Datamancer",
        "Death V00D00",
        "Deathwatch",
        "Demon Hex",
        "Devo Virtual",
        "Devoid",
        "Diablo 77",
        "DigiKasai",
        "DJ Capacitor",
        "Dogtooth",
        "Dre Smooth",
        "Eis",
        "Elf Soldier",
        "Encryptz",
        "End Trash",
        "Feedfetcher",
        "Flame Chief",
        "Flip Interface",
        "Fractal Artifice",
        "Fuzzy logic",
        "Gaijin Torpedo",
        "Ghost Lick",
        "Ghoul Dog",
        "Go Neurosis",
        "Gul Fire Dip",
        "Ha Crank",
        "Hachi Memory",
        "Happer",
        "Happy Panda",
        "Heatseeker",
        "Heise Feather",
        "Hilarious",
        "Hinata",
        "Hogwash",
        "Hongse Zero",
        "Hostile Zone",
        "Hound Switch",
        "Huffy M",
        "Hungry Ghost",
        "Huoyan G",
        "HyperTears",
        "Ibis Four",
        "Ice Analog",
        "Ichi Falsify",
        "Infobahn",
        "Inu Bolt",
        "Javier Script",
        "Joost Ranch",
        "Juice",
        "Juju Wine",
        "Kage",
        "Kami Amplitude",
        "Ketsueki Flow",
        "Kid Terminal",
        "Kijani",
        "Kori Jump",
        "Krov",
        "Kuma Ruby",
        "Kusa Network",
        "Kyuu Charm",
        "L Murky",
        "lady Probability",
        "Lan se Monkey",
        "Lazy Shock",
        "Leaf Drive",
        "Lexicon Bandit",
        "Lim Top",
        "Lion Trip",
        "Login Wish",
        "Maji",
        "Mall Face",
        "Mao 4",
        "Masu Net",
        "MC Vord",
        "Mirror Jack",
        "Mizu",
        "Mod.Net",
        "Modal Fraction",
        "Mongoose 8",
        "Mook Tube",
        "Mother Me",
        "Mother_Bored",
        "Moto Zion",
        "Mr ∞",
        "Mr Peepers",
        "Mutagen Roku",
        "Neko",
        "Nemo Yellow",
        "Nero Girl",
        "Nesti Jr.",
        "Neurocide",
        "Ni Reptile",
        "Nyekundu",
        "Oblivia 404",
        "Okami 7",
        "OneDubGod",
        "Onyx Choke",
        "Orthodox Kill",
        "Override Fire",
        "Paradox Lox",
        "Patient Zero",
        "Phantom Paradigm",
        "Phase Shiro",
        "Phat Chip 13",
        "Phreakworm",
        "Pipe Alien",
        "Pixelgeist",
        "PlugAwe",
        "Poltergeist",
        "Prankster Kat",
        "Quake XXX",
        "Quantum Clan",
        "Queen DumDum",
        "Reaper 9",
        "Rebel Day",
        "Red Plague",
        "RGB Lost",
        "RiddleRiddle",
        "Riku",
        "RipTiger",
        "Riss",
        "Robotnik",
        "Rogue San",
        "ROMinatrix",
        "Rune Force",
        "Ryuu Gutter",
        "Sabertooth",
        "Sakana",
        "Samizdat",
        "Sarge Bleak",
        "Seraphim",
        "Seven Wolf",
        "Shame Sorrow",
        "Shark Blue",
        "Sharp Cowboy",
        "Shi Cafe",
        "Shichi",
        "Shimo Fusion",
        "Sho Slim",
        "Shuang Fo",
        "Sickle Boi",
        "Sin Viper",
        "Sister Jynx",
        "Six Bummer",
        "Snowblind",
        "Softwhere",
        "Solid State",
        "Sora Prime",
        "Soulhead",
        "Spiderhead",
        "Splinter Cat",
        "Spoof Dizz",
        "SSL Son",
        "Steel Penny",
        "Step Huo",
        "Stick Drone",
        "Stripe Protocol",
        "Synaptica",
        "TeaCup",
        "Terror Rex",
        "The havoc",
        "The Invisible hand",
        "The Shadow Sphere",
        "The Venomous Pao",
        "Thermal Raven",
        "Tremor",
        "Tsuki Fragment",
        "Twelve Circuit",
        "Two Shell",
        "Ujasiri",
        "Underscourge",
        "Unicode Vault",
        "Uzi Lightning",
        "Verve",
        "Vo Spike",
        "Volk",
        "Wardroid",
        "Wasser",
        "White Distortion",
        "White Knight",
        "Winner Red",
        "Winst0n!",
        "X",
        "Yuki",
        "Yurei Blu",
        "Zauberer",
        "ZBot",
        "ZeroGuru",
        "Zigzag",
        "Zver",
    ],
    "oracle-character-hacker-personality-quirk-result": [
        "undermines elections in Third World countries, because they can",
        "Creates netsites for several street gangs, can muster help fast",
        "Turing Authority agent, under cover, working on major sting",
        "escaped from latvian data harvesters, has price on their head",
        "Collective formed by ex-Transmission Felonies cop",
        "Works for the bank they hacked, now targeted for assassination",
        "Confined to ghetto-built mobility walker run on laptop batteries",
        "runs collective for corporate uncle, who thinks they're an idiot",
        "Guarded by a pair of tactically enhanced German Shepherds",
        "Functionally a human server, sitting on millions",
        "high aptitude, actually result of drugs tests in orphanarium",
        "Appears to be a script kiddie, successful exploit royalty farmer",
        "Clinically dead 3 times, wears a defib rig, surprisingly chipper",
        "Spends all their time in sensory deprivation tank",
        "Blinded as a child, navigates entire life via net overlays",
        "Maintains clones in exowombs, in hidden cold storage facility",
        "Adept at cracking people's neural interface networks",
        "Tanzanian ‘sorcerer’, skims identities to sell to the syndicates",
        "Apparently in a coma, mercenary accomplices cover for them",
        "Wrote a dementia triggering software routine, afraid to sell it",
        "No clue their entire life is monitored by company handlers",
        "exceptional programmer, builds in exploits, fears discovery",
        "uplifted chimpanzee, fiercely protected by militant ecoclade",
        "Child prodigy, invalid son/daughter of experimental neuroscientist",
        "experienced darknet scout, haunted by malicious dataforms",
        "Synthetic, used as meatspace ‘avatar’ of another hacker",
        "rogue marketing AI, curates online Museum of Dangerous Art",
        "Targeted for extraction by several major transnationals",
        "Ousted darling VRchitect, sells access to hidden labyrinths",
        "Former forensic system analyst, partial mindwipe",
        "Squeals to corporation if hired, well paid, makes excuses",
        "unremarkable 15 year old student, secret genius",
        "Rewired neural pathways push their intelligence beyond normal",
        "Intelligent hotel system, trades in guests' secrets, very wealthy",
        "Middle-aged housewife/husband, was in debt, continues for the rush",
        "linkjacker specialising in compromising interfaced gear",
        "rogue nanite hive-mind, hiding in a hab stack's vent system",
        "Self-righteous ethical hacktivist, has to make political statement",
        "Information hygiene specialist, excels at covering any tracks",
        "Notorious LOLtroll, gleefully puts others in real danger",
        "Deals in downloadable skill apps and customised software",
        "Suffers Amazon War flashbacks, agoraphobic hoarder",
        "Runs distribution of dark servers, launders data and bitcoin",
        "Planning data heist, network map tattooed on missing person",
        "uses amphetamines to gain edge, just fucking them up",
        "Compelled to swat soft targets, knows they shouldn't",
        "South Korean professional gamer, transition to big time net crime",
        "Drug addicted Net regulator, knows systems’ weak points",
        "Manipulated by AIs, believes aliens have chosen them",
        "Traffic control AI, masquerades as a human teen with ASD",
    ],
    "oracle-character-hacker-obscure-fact-result": [
        "Wanted by African union",
        "Degree educated anarchist",
        "Tracking emergent intelligences",
        "Thick accent, security conscious",
        "Never, ever seen in meatspace",
        "exhausted, caffeine addicted",
        "Strategic genius, well connected",
        "used by collective for his money",
        "Brilliant cryptographer",
        "living black banking node",
        "Wanted by biotech company",
        "Buys back doors, rents them out",
        "reroutes courier drones for fixer",
        "Teleoperates spiderform shells",
        "Travels in secure AI-driven car",
        "Secreting own ‘ghost’ across net",
        "Subverts implants for own use",
        "Superstitious sakawa devotee",
        "Situation awareness for solos",
        "Several fixers aware of their work",
        "reconfigures obsolete software",
        "Considering finally going legit",
        "refurbishes obsolete hardware",
        "Sought-after security consultant",
        "Supports rebel insurgency",
        "Vindictively alters enemies’ IDs",
        "3D printing an army of drones",
        "Successful online drug dealer",
        "Telemetric sniper",
        "Courted by syndicate bosses",
        "Conflict averse by State design",
        "Covertly records everything",
        "remote vehicle-jackers",
        "Sideline in pirate hunting",
        "Stolen Mossad virus adaptation",
        "Infamous node saboteur",
        "Virtual cosplayer club president",
        "Financing transhuman revolt",
        "Sub-par AR ‘street artist’",
        "Mines archeosystems for data",
        "engineers violent flash mobs",
        "lives in decommissioned sub",
        "expert MOUT co-ordinator",
        "hostile and deadly black ICE",
        "tagging and tracking homeless",
        "recon via subverted appliances",
        "Ghost-hacked by desperate cop",
        "Being used by corrupt manager",
        "under Turing investigation",
        "hosts popular VR sex dungeon",
        "Intimately knows the city streets",
    ],
    "oracle-character-hacker-mannerisms-looks-result": [
        "Army fatigues, manipulative",
        "Short red mohawk, bondage pants",
        "reliable, obsessive, clean cut",
        "Thin, bald, wild eyed, submissive",
        "Translucent, shadowy avatars",
        "Cheap suit, unkempt, nervous",
        "Grubby, dishevelled, paraplegic",
        "Wears labelled casuals, arrogant",
        "Cosmonaut suit, catheter, bright",
        "Slick hair, sharp suit, confident",
        "humourless, kawaii-punk, tomboy",
        "late 20s, sophisticated, ruthless",
        "Spiritual, hippy, infosocialist",
        "Malnourished, pastey, dank",
        "African, child soldier, gregarious",
        "Wealthy, suave, fatalist, drinker",
        "untrusting, baggy clothes, caps",
        "Skeletal, tribal scars, chrome teeth",
        "Sterile stasis tank, philosophical",
        "T-shirts, jeans, sneakers, torn",
        "Slight, scruffy, shuffling, weak",
        "hyperactive, 3/4 pants, paranoid",
        "hairy, smelly, tasteful aesthete",
        "Bed-ridden, trapped, unloved",
        "leather coat, skin cut, bruiser",
        "Serene, tidy, meticulous, plastic",
        "Presents as gaunt Victorian gent",
        "Young, serious, severe short bob",
        "Slacks, loafers, tailored shirts",
        "Stuttering, intelligent, frustrated",
        "Sly, overweight, pork pie hat",
        "long hair, beanies, Ts, juvenile",
        "Distant, fidgety, emaciated",
        "Only hear a smooth, baritone voice",
        "Pear-shaped, leather jacket, boots",
        "semi-transparent garments, talks too fast",
        "Scattering of slightly silvered dust",
        "Pale, bleached dreads, patronising",
        "Cuban exile, tech coveralls, cigar",
        "Obese, curly hair, spots, obnoxious",
        "Toned, vest, lounge pants, stares",
        "Sweats, unwashed, gruff, afraid",
        "Tall, imposing, Slavic, smart coat",
        "Driven, chain smokes, agitated",
        "Tremors, vacant eyes, bad teeth",
        "Frumpy, short hair, kaftan, twitch",
        "Sportswear, greasy hair, twitchy",
        "Stained shirt, tie, shakes, furtive",
        "Mannish, scarlet curls, vest tops",
        "Floppy hair, sullen (vidchat only)",
    ],
    "oracle-character-street-walker-result": [
        "Elegant Full Body Conversion, Aesthetically Pleasing",
        "Augmented genitalia and tactile sensory upgrades",
        "Lean, attractive, loaded with hallucinatory pheromones",
        "Battered synthetic, needs repairs, garish vinyl clothing",
        "All limbs replaced with double-jointed cybernetics",
        "Illegally young, brash, dead eyed - nearby junkie pimp",
        "Disabled exotic bioform, assisted by linear frame",
        "Overweight, excessive make up, narcotic dependency",
        "Old, has local knowledge, skilled, clean medical record",
        "Neural cutouts, detached, implanted recorder suite",
    ],
    "oracle-character-cabbie-appearance-result": [
        "Armored up",
        "unwashed",
        "Chain smoker",
        "Goggles & tech",
        "Fat, eating junk",
        "looks exhausted",
        "Sick & shaking",
        "Fresh implant(s)",
        "Well groomed",
        "Way too young",
        "Pock-marked",
        "half-starved",
        "heavily tattooed",
        "Charms & symbols",
        "Army fatigues",
        "Fully cyborged",
        "hardwired in",
        "Shiny fetishwear",
        "Tribal scarring",
        "Oversized optics",
        "Chromed teeth",
        "Slick with sweat",
        "Atrophied limb",
        "Twitches",
        "Polythene coverall",
        "layered T-shirts",
        "Four handguns",
        "excessive vaping",
        "Filthy baseball cap",
        "Scruffy looking",
        "Facial burn scars",
        "Constant texting",
        "Designer coat",
        "HUD Visor",
        "respirator",
        "Mirrorshades",
        "Slab-headed",
        "Surplus flight suit",
        "Geriatric",
        "Creaking leathers",
        "Jury-rigged IV drip",
        "Bright blue hair",
        "Bullet earrings",
        "Wearable cameras",
        "Autoshotgun",
        "has no legs",
        "Alopecia",
        "Thin cyberarms",
        "Aviator glasses",
        "Pale green optics",
    ],
    "oracle-character-cabbie-nationality-result": [
        "russian",
        "Jamaican",
        "French",
        "Sikh Indian",
        "libyan",
        "Nigerian",
        "uzbek",
        "American",
        "Chinese",
        "German",
        "Dutch",
        "Mexican",
        "Scottish",
        "Irish",
        "Syrian",
        "ukrainian",
        "Thai",
        "Mongolian",
        "Somali",
        "Innuit",
        "Saudi",
        "Portuguese",
        "Spanish",
        "Turkish",
        "Danish",
        "latvian",
        "romany",
        "Greek",
        "romanian",
        "Finn",
        "Flemish",
        "Pakistani",
        "Italian",
        "Siberian",
        "Bulgarian",
        "South African",
        "Malay",
        "Kenyan",
        "Tibetan",
        "Polish",
        "Swedish",
        "hungarian",
        "Congolese",
        "Moldovan",
        "Afghan",
        "Kashmiri",
    ],
    "oracle-character-cabbie-conversation-topic-result": [
        "The state of the city",
        "Big combat sports fan",
        "Driverless vehicles",
        "Gangs in the area",
        "Their huge family",
        "extreme alt-politics",
        "Their tricked out vehicle",
        "The ecopocalypse",
        "Conspiracy theories",
        "Cod philosophy",
        "Classic rock music",
        "how connected they are",
        "The erratic weather",
        "Favourite <a href=\"/oracles/misc-oracles#vid-show\">TV shows</a>",
        "Cyberware brands",
        "The recent/ongoing war",
        "They used to be rich",
        "racist tirades",
        "Corporate gossip (fake)",
        "Kung-fu movies",
        "Was once a surgeon",
        "Their sexual conquests",
        "reality TV shows suck",
        "Their deep dislike of AR",
        "Their pet synthetic goat",
        "Global politics",
        "The spectre of terrorism",
        "hi-tech weaponry",
        "Their many ex-partners",
        "Their work on their PhD",
        "Their missing daughter",
        "rampant crime",
        "The latest VR games",
        "Their favourite eateries",
        "Info-Socialist revolution",
        "Their aggressive cancer",
        "Disdain for the police",
        "Was once a pilot",
        "Today’s youth/drugs",
        "The rich/poor divide",
        "Desire to be an actor",
        "The ethics of cloning",
        "endorses brands (paid)",
        "Making own net show",
        "The welfare system",
        "Getting out the business",
        "extreme sex SimStims",
        "State of their slum-cube",
        "how they live in the cab",
    ],
};
export default characterOracleResults;