const factionOracleResults = {
    "oracle-megacorp-name-result": [
        [
            "ACUVEA",
            "ADASTRUS",
            "ADDINGWELL",
            "AGRICULAN",
            "AINOVIQ",
            "AIRQON",
            "ALCHEMEUS",
            "ALCHEMEVO",
            "ALPHAVETA",
            "ALPTEQ",
            "ALTEGIC",
            "ALTOVEX",
            "AMPINITY",
            "AMPLEC",
            "AONOMY",
            "APTOTA",
            "AQUINIQUE",
            "AQUINNOVA",
            "ARCHETIVE",
            "ARCHITECTICA",
            "ARCHITECTIQUE",
            "ARCHITEVO",
            "ASPEXX",
            "ASTRATEQ",
            "ASTRIOL",
            "ASTRONEA",
            "ATOMIKON",
            "AUBITAL",
            "AUGMETIC",
            "AUTALOGIC",
            "AXXIMUM",
            "BIALOGUE",
            "BIOGENUIS",
            "BIONIQE",
            "BIOQEM",
            "BIOTEXUS",
            "BIOVECO",
            "BIOVUS",
            "BOXHAM",
            "BOXWISH",
            "BRIOTA",
            "BRIVONA",
            "BUILDUNO",
            "CALCUVIS",
            "CAPOVEX",
            "CAPRICOS",
            "CAPRIQORN",
            "CAREMARQUE",
            "CASCADUS",
            "CENTICUS",
            "CENTIGMA",
            "CETRENO",
            "CHEMECAL",
            "CHEMEGIC",
            "CHEMEXON",
            "CHEMIVA",
            "CHEMIXAL",
            "CHRONUVO",
            "CIRCUOS",
            "CLARIMEN",
            "CLARIWELL",
            "CLINITIAL",
            "CLINIVA",
            "CLINIVUS",
            "CLOUDEGIC",
            "CLOUDEXIS",
            "COCEPTIVE",
            "COGENTIAL",
            "COGNEGIC",
            "COGNOTA",
            "COMPUTEVO",
            "CONNEXIAL",
            "CONSTRUXIVE",
            "CONTAXIVE",
            "CONUVO",
            "CORADIUS",
            "CORBITAL",
            "CORVENTIVE",
            "COSMIQE",
            "CUBETIQ",
            "CUBEVO",
            "CURVEVO",
            "CYBACOR",
            "CYNOR",
            "CYNTEXIA",
            "CYONOMY",
            "CYQIQ",
            "CYSMIQ",
            "CYSQO",
            "DATOTA",
            "DENTAVEX",
            "DENTOTA",
            "DEQAGON",
            "DIADYN",
            "DIAMECO",
            "DIGIQAL",
            "DIGITEGRITY",
            "DIGITLEY",
            "DINETIC",
            "DIOLOGIC",
            "DOCTEVO",
            "DOCTOTA",
            "DREAMIAL",
            "DYMAXA",
            "DYNAMACTIVE",
            "DYNAMOVA",
            "ECLEXIC",
            "EDGOLOGY",
            "ELECTRECA",
            "ELECTREUS",
            "ELECTRITECT",
            "ELEMENSIS",
            "ELEVONI",
            "ELEXTRIFY",
            "ENERGENIQ",
            "ENERVETIC",
            "ENIGMIO",
            "EVERVA",
            "EVIQE",
            "EVOFINITY",
            "EXECTRIC",
            "EXELEOS",
            "EXOTERIOR",
            "EXPODIAN",
            "EXPONUS",
            "EXTRATEQ",
            "EXTRONICA",
            "FINAEGIS",
            "FINEXIC",
            "FINIVIA",
            "FINOTIVE",
            "FINTEGIC",
            "FINTEXIS",
            "FINTOTA",
            "FLARIAL",
            "FLEXELLE",
            "FLORONA",
            "FORMEXUS",
            "FORMIAL",
            "FORMONIC",
            "FORMURA",
            "FOUNTINA",
            "FROMOTA",
            "GENAEGIS",
            "GENEGIC",
            "GENNEC",
            "GENOVIQ",
            "GEOGICAL",
            "GIROVO",
            "GOMIUM",
            "GRADUEX",
            "GRAFIQE",
            "HABRICATE",
            "HABTEQ",
            "HELIXAGON",
            "HELIXIAN",
            "HERBENO",
            "HEXIQON",
            "HEYPEX",
            "HOLARA",
            "HOTELIGEN",
            "HYDRATEQ",
            "HYDREVO",
            "HYDRISE",
            "HYDROTIVE",
            "HYPNOTA",
            "IDENICO",
            "IDENTITEQ",
            "ILLUMIAL",
            "INDEXIAL",
            "INDUSTRUS",
            "INFOFINITY",
            "INGOTEX",
            "INNOVEGIC",
            "INNOVEXIQ",
            "INTERAXIC",
            "INVENTEVO",
            "IOTEGIC",
            "IOTEGRAL",
            "IOTIQUE",
            "ISOTECT",
            "KINAEGIS",
            "KINETONIC",
            "KNOMIAL",
            "KNOVATIC",
            "KNOVEO",
            "KNOVIQ",
            "LANDSMILL",
            "LIPTICAL",
            "LUMENEVO",
            "LUMETIQ",
            "LUXIMAL",
            "LYNODA",
            "LYONARDO",
            "MAEDIAN",
            "MAGNEQ",
            "MAXEOM",
            "MAXIPLE",
            "MAXUMAX",
            "MAXXIC",
            "MEDATEQ",
            "MEDIQAS",
            "MEDOCAL",
            "METRANA",
            "MIDAURA",
            "MODENTIAL",
            "MONOCAL",
            "MOTEXO",
            "MOTIQ",
            "NATURITIOUS",
            "NEOLIVA",
            "NEXTONIC",
            "NIMBOUS",
            "NUBENO",
            "NUMANTA",
            "NUMIV",
            "NUMOTA",
            "NUVONI",
            "OBSERVIAL",
            "OCTAGOS",
            "OLEOCO",
            "ONCEPTUAL",
            "OPTALOGIC",
            "OPTAQON",
            "OPTIGMA",
            "OPTRICA",
            "OQTAVE",
            "OQTEL",
            "ORBIQE",
            "ORPHOSIS",
            "OXYGENTA",
            "OYSTEO",
            "PANADIUM",
            "PAYETRIC",
            "PAYMABILITY",
            "PAYMARQUE",
            "PAYTOTA",
            "PENTEGIS",
            "PETROLEUS",
            "PETROQO",
            "PEYWEY",
            "PHARMEDIQA",
            "PHARMEGIC",
            "PHARMETRO",
            "PHARMONIS",
            "PHERICAL",
            "POWERQO",
            "PRECISTO",
            "PREMONEX",
            "PRISMAXIC",
            "PRISMOSIS",
            "PROAXIVE",
            "PROGIENCE",
            "PROJEXEN",
            "PROJEXIONS",
            "PROJECTIVE",
            "PROTELIGEN",
            "PROTEXIAL",
            "PROTIGNIS",
            "PROTOTA",
            "QATALYTIC",
            "QEMIQ",
            "QIARIS",
            "QINETICO",
            "QOBOTIC",
            "QONEXA",
            "QONTRAC",
            "QOPTA",
            "QROMOS",
            "QUADRECO",
            "QUADREUM",
            "QUALIDENTA",
            "QUANTET",
            "QUBETA",
            "RAEDIAL",
            "REACTIAL",
            "RETINIQUE",
            "RETINOR",
            "REVOLUNO",
            "REVOLUSYS",
            "RHONIUM",
            "RYTOL",
            "SCIENICO",
            "SCIENIQ",
            "SCIENUVO",
            "SCIONEO",
            "SCRBBLR",
            "SECURIQO",
            "SECURIVEX",
            "SEGMETRIQ",
            "SELEXIBLE",
            "SELEXIC",
            "SELUXA",
            "SENTRICUS",
            "SERAMOL",
            "SHOPIVATE",
            "SIGNURA",
            "SILICONST",
            "SIMPLATEC",
            "SIXONIC",
            "SOLARTIVE",
            "SONIQE",
            "SPECTEVO",
            "SPECTOTA",
            "SPECTRIQUE",
            "SPEQTRON",
            "SPEQTUS",
            "SPHEERO",
            "SPORTONI",
            "SQUAIRCLE",
            "SQUAIRLY",
            "STRATAEGIC",
            "STRATEXIC",
            "STRUCTIAL",
            "STRUCTIQUE",
            "STRUQTA",
            "SYGMOS",
            "SYGNIUS",
            "SYNAMATIC",
            "SYNAPTIAL",
            "SYNBUS",
            "SYNCEVO",
            "SYNERGEVO",
            "SYNOVATIC",
            "SYNTAXIVE",
            "SYNTHECIS",
            "SYNTHEVO",
            "SYOLO",
            "SYOLOGIC",
            "SYREOS",
            "SYSTEMAXIC",
            "SYZYGIS",
            "TANGENSIS",
            "TANGIENCE",
            "TASKIAL",
            "TECNIQA",
            "TECNOVIQ",
            "TECTEVO",
            "TECTIGON",
            "TECTIKO",
            "TECTURAL",
            "TEKNEKA",
            "TEKONIKA",
            "TELIGENTA",
            "TELIGUS",
            "TELLIGEO",
            "TEQTIS",
            "TEQTO",
            "TEQTURE",
            "TETRATEQ",
            "TETRIQUE",
            "THENWARE",
            "THEORYCYBER",
            "THERAVEX",
            "TOTALIGENT",
            "TOTIMA",
            "TOTINITY",
            "TRANSACTIAL",
            "TRANSITIAL",
            "TRIBEDA",
            "TRONOMY",
            "ULTRIPLY",
            "UNIOTEC",
            "UNITEVO",
            "UNOTEQ",
            "UTILIKO",
            "UTILIVEX",
            "VAETO",
            "VERTIQO",
            "VERTOTA",
            "VERVETIC",
            "VIAXOS",
            "VIOTONIC",
            "VIRGENCY",
            "VIRTETIC",
            "VIRTUOQO",
            "VITOLOGIC",
            "VITOTA",
            "VITRALAB",
            "VIVERVA",
            "VOLTEGIC",
            "VYORA",
            "WATERQO",
            "WATERWEY",
            "XACTON",
            "XAGONAL",
            "XEBOK",
            "XECTUS",
            "XENONO",
            "XEXAGON",
            "XOLEUM",
            "XOTEM",
            "XOVEC",
            "XYPNOTIC",
            "ZEDOLOGY",
            "ZEEFINITY",
            "ZEELOGIC",
            "ZINQE",
            "ZYLICON",
        ],
        [
            "Technologies Inc.",
            "Ltd.",
            "Pharmaceuticals",
            "Incorporated",
            "Industries",
            "Corp",
            "Corporation",
            "Energy",
            "Solutions",
            "Digital",
            "Logistics",
            "LLC.",
            "Studios",
            "GeneCo",
            "Cyber Systems",
            "Consumer Products",
            "Global",
            "Dynamics",
            "Tech ",
            "Software",
            "Limited",
            "LLHC",
            "Group",
            "GmBH",
            "Robotics",
            "Conglomerate",
            "Holdings",
            "Enterprises",
            "Electronics",
            "Orbital",
            "Entertainment",
            "Networks",
            "Security",
            "Airways",
            "Systems",
            "Motors",
            "Mechanics",
            "Microsystems",
        ],
    ],
    "oracle-megacorp-maneuvers-result": [
        "Testing New Weapons",
        "Deadly Waste Disposal",
        "Engineered Pandemic",
        "Snatching Transients",
        "Manipulating Media",
        "Bribing Politicians",
        "Financial Manipulation",
        "Land Grab",
        "Tracking Consumers",
        "Testing New Drugs",
        "Altering Consumer Law",
        "Manipulating Market",
        "Stockpiling Medicines",
        "Corrupting Technology",
        "Targeting Rivals",
        "Subliminal Advertising",
        "Eliminate Flawed Stock",
        "Rigging Safety Standards",
        "Full Blown Civil War",
        "Undermine Rival Brand",
        "Offworld Banking Scam",
        "Covering Up Insane AI",
        "Testing New Bioware",
        "Harvesting Organs",
        "Management Cull",
        "Buying Up Patents",
        "Fixing Stock Levels",
        "Interdepartment War",
        "Enforcing Copyright",
        "Creating Subsidiaries",
        "Product Flaw Cover Up",
        "New Product Launch",
        "Department Merger",
        "Brainwashing Key Figures",
        "Abducting Street Kids",
        "Adulterating The Water",
        "Marketing Surveillance",
        "Bid For Nation Status",
        "Hostile Takeover",
        "Arming Street Gangs",
        "Targeting Undesirables",
        "Collecting Biometrics",
        "Testing New Synthetics",
        "Quantum Net Launch",
        "Buy Minor Nation State",
        "Testing New Cyberware",
        "Political Assassination",
        "Blackmailing Scientists",
        "Extract Rival Employee",
        "Hire Hostile Hackers",
        "Preparing To Defect",
        "Looking For Own Cure",
        "Hidden Warehouses",
        "Channeling Funds",
        "Designing Bio-Plague",
        "Building Private Army",
        "Covert Parallel Netsite",
        "Cloning Self",
        "Damaged Brand Salvage",
        "Create False Charity",
        "Assassinate Rivals",
        "Adulterating Medicines",
        "Engineered Promotion",
        "Planning Rival’s Exile",
        "Being Head-Hunted",
        "Faking Own Death",
        "Lost Bioweapon",
        "Cover Up Of Suicides",
        "Internal Investigation",
        "Automating Jobs",
        "Creating A War",
        "Buying Law Enforcers",
        "Real-Estate Purchases",
        "Phantom Accounting",
        "Adulterating Foods",
        "Manipulating Expenses",
        "Doctoring Records",
        "Wrecking Ecosystem",
        "Targeting Employees",
        "Creates Net Exploits",
        "Purchasing Start-Ups",
        "Eliminate R&D Failure",
        "Supporting Coup",
        "Covering Up Blackmail",
        "Slashing Wages",
        "Buying Bankers",
        "Framing Rival(S)",
        "Intimidate Reviewers",
        "Undermine own CEO",
        "Bribes Oversight Group",
        "Triggering Civil War",
        "Funding Counterfeits",
        "Doctoring Judicial Ais",
        "Purchasing Hospitals",
        "Controlling Alt-Media",
        "Creating Monopoly",
        "False Advertising",
        "Cutting Job Roles",
        "Undermine Own Company",
    ],
    "oracle-megacorp-assets-result": [
        "Fixer Network",
        "Bought City Officials",
        "Naive underlings",
        "Foreign head-of-State",
        "Compromised AI",
        "Weaponised Insects",
        "Net Smear Campaign",
        "Dubious Security Team",
        "Street Gang Alliance",
        "Fringe Political Group",
        "Corporate Ninjas",
        "Compromised Comms",
        "Mercenary Contractors",
        "Surveillance Drones",
        "loyal law Firm",
        "Duped Actors",
        "Independent hit Team",
        "Whistleblowers",
        "Spiderform Cybershells",
        "Kidnapped Son(s) or Daughter(s) of rivals",
        "Covert Sales Network",
        "Monitors Computers",
        "renowned Assassin",
        "unwitting employees",
        "Double-agents in Rival Corporation",
        "Elite Agents",
        "Foreign Strike Team",
        "Pharmaceutical Company",
        "Army of Own Clones",
        "Bioweapons Division",
        "Arms Dealers",
        "Petty executive",
        "Implanted explosives",
        "Blackmailed CEO",
        "Sympathetic Media",
        "Weaponised homeless",
        "Soulless Cyborg",
        "Aggressive hacker",
        "Conned legislators",
        "Their Own lover(s)",
        "Company Audit Team",
        "Designer Toxins",
        "Sex Synthetics",
        "Scientists",
        "Security Team",
        "Mafia Money",
        "People Traffickers",
        "Memetic Warfare Team",
        "Augmented Animals",
        "Combat economists",
        "Ambitious Courtiers",
        "R&D Nanoweapons",
        "City law enforcers",
        "Company’s Black Ops",
        "Autonomous Software",
        "Adulterated Chipware",
        "Displaced War Veterans",
        "unethical Medtechs",
        "hacking Collective",
        "Celebrity Stable",
        "Criminal Syndicate",
        "Junkie relative",
        "hazardous Virtuals",
        "Internal Investigators",
        "Controlling Drug Supply",
        "Social Warfare",
        "Intimate Personal Data",
        "Army of Drug Dealers",
        "reassigned Agents",
        "ripperdoc Network",
        "Private Bodyguards",
        "Own Family Fortune",
        "Tracking Nanites",
        "SimStim users",
        "Image Consultants",
        "Private Investigators",
        "AI System Designer",
        "Child Assassin",
        "Propagandists",
        "Blackmailed hackers",
        "Pr Consultants",
        "Desperate employees",
        "Federal Investigators",
        "religious Group",
        "Synthetic Commandos",
        "Corrupt Accountants",
        "Deceived Online Fans",
        "Compromised Implants",
        "Seductive Concubine",
        "Covert Vehicle Pool",
        "Offworld Accounts",
        "hunter-Killer Drones",
        "elite Programmers",
        "Intelligence Agency",
        "Cheap Gunmen",
        "unstable remotes",
        "Creative Techies",
        "Private laboratory",
        "Deceived rival",
    ],
    "oracle-gang-name-result": [
        [
            "Cortical",
            "Subway",
            "Radical",
            "Binary",
            "Fragile",
            "Hate",
            "Electric",
            "Mobile",
            "Endgame",
            "Bubblegum",
            "Biological",
            "Shaolin",
            "Chrome",
            "Polymer",
            "Rudeboy",
            "Terminal",
            "Shadow",
            "Subsonic",
            "Chemical",
            "Chosen",
            "Toxic",
            "Steel",
            "Waffen",
            "Cannibal",
            "Panzer",
            "Gun",
            "Disposable",
            "Iron",
            "Speedball",
            "Ak",
            "Liquid",
            "Junky",
            "Instant",
            "Zone",
            "Sushi",
            "Lucifer’s",
            "Remodelled",
            "Faceless",
            "Vampire",
            "Crosstown",
            "Aryan",
            "Spirit",
            "Nomad",
            "Hydraulic",
            "Fractal",
            "Brain",
            "Screaming",
            "Lucid",
            "Napalm",
            "Happy",
        ],
        [
            "Dogs",
            "Assassins",
            "Dragons",
            "Prophets",
            "Machine",
            "Society",
            "Freaks",
            "Girls",
            "Militia",
            "Atrocity",
            "Impulse",
            "Rippers",
            "Savages",
            "Riot",
            "Apocalypse",
            "Storm",
            "Soldiers",
            "Cult",
            "Loas",
            "Kidz",
            "Ghosts",
            "Church",
            "Technicals",
            "Clowns",
            "Fists",
            "Sharks",
            "Boys",
            "Maniacs",
            "Ultimates",
            "Legends",
            "Killaz",
            "Bullets",
            "Revolvers",
            "Bosses",
            "Thugs",
            "Babies",
            "Army",
            "Fanatics",
            "Daddies",
            "Chaos",
            "Hammer",
            "Method",
            "Clan",
            "Terror",
            "State",
            "Wasters",
            "Shards",
            "Moderns",
            "Harvest",
            "Losers",
        ],
    ],
    "oracle-gang-description-result": [
        [
            "Neo-Primitive,",
            "Soft-Armoured,",
            "VR Game Playing,",
            "Neon-Punk,",
            "Drone Utilising,",
            "Patriarchal,",
            "LAN-Linked,",
            "Augment Heavy,",
            "Spike Covered,",
            "Ex-Convict,",
            "Biomodified,",
            "Blade Wielding,",
            "Body Modified,",
            "Gun Fetishist,",
            "Rastafarian,",
            "Simstim Rigged,",
            "Tech-Ninja,",
            "Mood Chipping,",
            "Voodoo Practicing,",
            "Chip-Hop Fan,",
            "Grime-Punk,",
            "Death Metal Fan,",
            "Skinhead,",
            "Blood Stained,",
            "Armour Plated,",
            "Couture Stealing,",
            "Military Surplus,",
            "WoW Inspired,",
            "Risk Taking,",
            "African-Tribal,",
            "Ultraviolent,",
            "Drug Dependent,",
            "War Painted,",
            "Rag Enshrouded,",
            "Buddha-Faced,",
            "Emo-Goth,",
            "Goggle Wearing,",
            "Blood Drinking,",
            "Road Armoured,",
            "Heavily Tattooed,",
            "Neo-Luddite,",
            "Goth-Punk,",
            "Industrial-Tech,",
            "Tech Savvy,",
            "Net Dependent,",
            "Radical,",
            "AR Manipulating,",
            "Afro-Haired,",
            "Neon-Raver,",
        ],
        [
            "Electropunk",
            "Nerve Boosted",
            "Frame Assisted",
            "Scavenger",
            "Info-Socialist",
            "Sports Fan",
            "All Female",
            "Doom Cult",
            "Cyberfetish",
            "Brain Damaged",
            "Skill Chipping",
            "Scrap Tech",
            "Dog-Faced",
            "Media Savvy",
            "Parkour",
            "Drug Cooking",
            "Political",
            "Tech-Junkie",
            "evangelical",
            "Übermensch",
            "Juggalo",
            "Cyborg",
            "Psychotic",
            "War Veteran",
            "Armour Clad",
            "rich Kid",
            "Drug enhanced",
            "home Invading",
            "Cannibal",
            "homeless",
            "Steroid using",
            "Pseudo-Satanic",
            "Militant",
            "Mask Wearing",
            "Anarchist",
            "Alt-right",
            "religious",
            "Peddle Biking",
            "eco-Socialist",
            "Philosophical",
            "Multi-optic",
            "Anti-Corporate",
        ],
        [
            "Combat Gang",
            "Skaters",
            "Martial Artists",
            "Tech-Jackers",
            "Party Artistes",
            "Street Fighters",
            "Wireheads",
            "Go-Gang",
            "Boosters",
            "Chromers",
            "Cultists",
            "Moto-Cultists",
            "Pranksters",
            "Street Kids",
            "Nihilists",
            "Guardians",
            "Policlub",
        ],
    ],
    "oracle-gang-main-trade-result": [
        "Deal in prohibited neural boosts, intellect stims, sakawa charms",
        "Operate a stash house in the old Metro system and fence goods",
        "Import, crack and distribute Vr games and hong Kong action sims",
        "hack and tap electronic infrastructure, for a price",
        "Will put on one hell of a party in exchange for hot information",
        "Trade in counterfeit sportswear, tickets and fan merchandise",
        "Supply banned pornographic SimStims and vid-chips",
        "Sell Chiba-grade imported black market implants and upgrades",
        "Prolific dumpster-divers and parts-hunters; trade and exchange",
        "Premier suppliers of street-level artificial pheremones",
        "leader hires out her most neurologically damaged boys as muscle",
        "Currently making a killing in the underground fighting scene",
        "Bargain basement prices for spectacular acts of arson",
        "Specialists in smash and grab jobs, for money and firearms",
        "Own and operate a warehouse nightclub in the factory district",
        "Digital surveillance and stalking, seamless manipulation of video",
        "happy to be hired as rooftop street guides and expert sneaks",
        "Doctor common drugs, altering their composition and legality",
        "Take protection money, cook drugs and provide bespoke curses",
        "Work protection on a number of chip-hop bars and clubs",
        "3D-print their own implanted weapons (fragile)",
        "Several members are skilled AR coders",
        "Make their money dealing in heavy weapons and stolen cars",
        "Grow synthetic opium in hydroponic blisters and sell it on",
        "Target small-fry fixers and gangers and steal their shit to sell on",
        "Sell stolen fashions, counterfeits and cloned credit cards",
        "Professional-level hits and heists, unfettered by rules of warfare",
        "Promise them in-game bitcoins and they’ll perform any ‘quest’",
        "Fat allowances and legal back-up allow extreme road race stunts",
        "Smuggle russian military hardware and protect ‘their’ hab stacks",
        "Slave traffickers and suppliers of stolen consumer electronics",
        "Suspected organ-leggers and kidnappers",
        "experts at depopulating hab stacks quickly and brutally",
        "Brew their own alcohol, trade it for SCOP; do gig work for SCOP",
        "Skin-traders and flesh peddlars, buy and sell pretty young things",
        "Find and sell corpses or parts to the body banks",
        "Self-styled free-company, market themselves as street condottieri",
        "Fence and sell black market cybernetic limbs of dubious origin",
        "Selling synthesized copies of strong, manufactured virus strain",
        "Will consider any job for new bikes or fuel; flaky, unpredictable",
        "Frighteningly good propagandists and excellent rent-a-thugs",
        "Paid to protect a number of local Christian agri-businesses",
        "No-questions-asked bike courier service, as well as ride-by hits",
        "Taken over a wrecking yard so they can just, ya know, wreck stuff",
        "Minifacture their own flechette weapons and needleguns",
        "run an angst-soaked cloud forum, behind a secure pay wall",
        "hormone-farm captive young males to sell online",
        "Blackmail and harass prominent civil servants and create fake news",
        "Carjacking and auto theft, as well as elaborate respraying",
        "Do a roaring trade in illegally downloaded, DRM-free <a href=\"/oracles/misc-oracles#music-genre--subculture-style\">music</a>",
    ],
    "oracle-gang-current-activity-result": [
        "Picking a fight with someone they don’t like - store owner, passer by, hab resident",
        "Marking the local area with gang tags - AR, spray paint, pens, animatic stickers",
        "Shaking down the locals with threats and intimidation - for money, booze, sex",
        "raving to their favourite music/propaganda, extremely loudly",
        "Getting wasted, or psyching themselves up before a fight or a raid",
        "Facing down cops/security/another gang - as far as they can get without a fight",
        "Participating in tests of skill or daring among themselves",
        "Making a deliberate attempt at being visible, strengthening presence in the area",
        "engaged in their main biz, or negotiating employment with another party",
    ],
    "oracle-gang-rumors-hooks-result": [
        "The gang is in danger of being destroyed by a more powerful rival",
        "The gang are showing symptoms of having contracted a disease",
        "The gang knows of hidden ways through the city or into a building",
        "The gang have procured (or manufactured) a dangerous narcotic or toxin",
        "The gang harbours an exile or outcast from a wealthy and powerful family",
        "The gang have discovered valuable technology lost by another powerful faction",
        "The gang has a splinter cell of powerful members, who are impossible to control",
        "The gang are grabbing runaways for corporate experiments, and getting bolder",
        "A member has fallen in love with a rival gang member and fled, knowing too much",
        "The gang has access to unusual cybernetics, and it’s drawing attention to them",
    ],
};
export default factionOracleResults;