const factionOracleResults = {
    "oracle-gang-name-result": [
        [
            "Cortical",
            "Subway",
            "Radical",
            "Binary",
            "Fragile",
            "Hate",
            "Electric",
            "Mobile",
            "Endgame",
            "Bubblegum",
            "Biological",
            "Shaolin",
            "Chrome",
            "Polymer",
            "Rudeboy",
            "Terminal",
            "Shadow",
            "Subsonic",
            "Chemical",
            "Chosen",
            "Toxic",
            "Steel",
            "Waffen",
            "Cannibal",
            "Panzer",
            "Gun",
            "Disposable",
            "Iron",
            "Speedball",
            "Ak",
            "Liquid",
            "Junky",
            "Instant",
            "Zone",
            "Sushi",
            "Lucifer’s",
            "Remodelled",
            "Faceless",
            "Vampire",
            "Crosstown",
            "Aryan",
            "Spirit",
            "Nomad",
            "Hydraulic",
            "Fractal",
            "Brain",
            "Screaming",
            "Lucid",
            "Napalm",
            "Happy",
        ],
        [
            "Dogs",
            "Assassins",
            "Dragons",
            "Prophets",
            "Machine",
            "Society",
            "Freaks",
            "Girls",
            "Militia",
            "Atrocity",
            "Impulse",
            "Rippers",
            "Savages",
            "Riot",
            "Apocalypse",
            "Storm",
            "Soldiers",
            "Cult",
            "Loas",
            "Kidz",
            "Ghosts",
            "Church",
            "Technicals",
            "Clowns",
            "Fists",
            "Sharks",
            "Boys",
            "Maniacs",
            "Ultimates",
            "Legends",
            "Killaz",
            "Bullets",
            "Revolvers",
            "Bosses",
            "Thugs",
            "Babies",
            "Army",
            "Fanatics",
            "Daddies",
            "Chaos",
            "Hammer",
            "Method",
            "Clan",
            "Terror",
            "State",
            "Wasters",
            "Shards",
            "Moderns",
            "Harvest",
            "Losers",
        ],
    ],
    "oracle-gang-description-result": [
        [
            "Neo-Primitive,",
            "Soft-Armoured,",
            "VR Game Playing,",
            "Neon-Punk,",
            "Drone Utilising,",
            "Patriarchal,",
            "LAN-Linked,",
            "Augment Heavy,",
            "Spike Covered,",
            "Ex-Convict,",
            "Biomodified,",
            "Blade Wielding,",
            "Body Modified,",
            "Gun Fetishist,",
            "Rastafarian,",
            "Simstim Rigged,",
            "Tech-Ninja,",
            "Mood Chipping,",
            "Voodoo Practicing,",
            "Chip-Hop Fan,",
            "Grime-Punk,",
            "Death Metal Fan,",
            "Skinhead,",
            "Blood Stained,",
            "Armour Plated,",
            "Couture Stealing,",
            "Military Surplus,",
            "WoW Inspired,",
            "Risk Taking,",
            "African-Tribal,",
            "Ultraviolent,",
            "Drug Dependent,",
            "War Painted,",
            "Rag Enshrouded,",
            "Buddha-Faced,",
            "Emo-Goth,",
            "Goggle Wearing,",
            "Blood Drinking,",
            "Road Armoured,",
            "Heavily Tattooed,",
            "Neo-Luddite,",
            "Goth-Punk,",
            "Industrial-Tech,",
            "Tech Savvy,",
            "Net Dependent,",
            "Radical,",
            "AR Manipulating,",
            "Afro-Haired,",
            "Neon-Raver,",
        ],
        [
            "Electropunk",
            "Nerve Boosted",
            "Frame Assisted",
            "Scavenger",
            "Info-Socialist",
            "Sports Fan",
            "All Female",
            "Doom Cult",
            "Cyberfetish",
            "Brain Damaged",
            "Skill Chipping",
            "Scrap Tech",
            "Dog-Faced",
            "Media Savvy",
            "Parkour",
            "Drug Cooking",
            "Political",
            "Tech-Junkie",
            "evangelical",
            "Übermensch",
            "Juggalo",
            "Cyborg",
            "Psychotic",
            "War Veteran",
            "Armour Clad",
            "rich Kid",
            "Drug enhanced",
            "home Invading",
            "Cannibal",
            "homeless",
            "Steroid using",
            "Pseudo-Satanic",
            "Militant",
            "Mask Wearing",
            "Anarchist",
            "Alt-right",
            "religious",
            "Peddle Biking",
            "eco-Socialist",
            "Philosophical",
            "Multi-optic",
            "Anti-Corporate",
        ],
        [
            "Combat Gang",
            "Skaters",
            "Martial Artists",
            "Tech-Jackers",
            "Party Artistes",
            "Street Fighters",
            "Wireheads",
            "Go-Gang",
            "Boosters",
            "Chromers",
            "Cultists",
            "Moto-Cultists",
            "Pranksters",
            "Street Kids",
            "Nihilists",
            "Guardians",
            "Policlub",
        ],
    ],
    "oracle-gang-main-trade-result": [
        "Deal in prohibited neural boosts, intellect stims, sakawa charms",
        "Operate a stash house in the old Metro system and fence goods",
        "Import, crack and distribute Vr games and hong Kong action sims",
        "hack and tap electronic infrastructure, for a price",
        "Will put on one hell of a party in exchange for hot information",
        "Trade in counterfeit sportswear, tickets and fan merchandise",
        "Supply banned pornographic SimStims and vid-chips",
        "Sell Chiba-grade imported black market implants and upgrades",
        "Prolific dumpster-divers and parts-hunters; trade and exchange",
        "Premier suppliers of street-level artificial pheremones",
        "leader hires out her most neurologically damaged boys as muscle",
        "Currently making a killing in the underground fighting scene",
        "Bargain basement prices for spectacular acts of arson",
        "Specialists in smash and grab jobs, for money and firearms",
        "Own and operate a warehouse nightclub in the factory district",
        "Digital surveillance and stalking, seamless manipulation of video",
        "happy to be hired as rooftop street guides and expert sneaks",
        "Doctor common drugs, altering their composition and legality",
        "Take protection money, cook drugs and provide bespoke curses",
        "Work protection on a number of chip-hop bars and clubs",
        "3D-print their own implanted weapons (fragile)",
        "Several members are skilled AR coders",
        "Make their money dealing in heavy weapons and stolen cars",
        "Grow synthetic opium in hydroponic blisters and sell it on",
        "Target small-fry fixers and gangers and steal their shit to sell on",
        "Sell stolen fashions, counterfeits and cloned credit cards",
        "Professional-level hits and heists, unfettered by rules of warfare",
        "Promise them in-game bitcoins and they’ll perform any ‘quest’",
        "Fat allowances and legal back-up allow extreme road race stunts",
        "Smuggle russian military hardware and protect ‘their’ hab stacks",
        "Slave traffickers and suppliers of stolen consumer electronics",
        "Suspected organ-leggers and kidnappers",
        "experts at depopulating hab stacks quickly and brutally",
        "Brew their own alcohol, trade it for SCOP; do gig work for SCOP",
        "Skin-traders and flesh peddlars, buy and sell pretty young things",
        "Find and sell corpses or parts to the body banks",
        "Self-styled free-company, market themselves as street condottieri",
        "Fence and sell black market cybernetic limbs of dubious origin",
        "Selling synthesized copies of strong, manufactured virus strain",
        "Will consider any job for new bikes or fuel; flaky, unpredictable",
        "Frighteningly good propagandists and excellent rent-a-thugs",
        "Paid to protect a number of local Christian agri-businesses",
        "No-questions-asked bike courier service, as well as ride-by hits",
        "Taken over a wrecking yard so they can just, ya know, wreck stuff",
        "Minifacture their own flechette weapons and needleguns",
        "run an angst-soaked cloud forum, behind a secure pay wall",
        "hormone-farm captive young males to sell online",
        "Blackmail and harass prominent civil servants and create fake news",
        "Carjacking and auto theft, as well as elaborate respraying",
        "Do a roaring trade in illegally downloaded, DRM-free music",
    ],
    "oracle-gang-current-activity-result": [
        "Picking a fight with someone they don’t like - store owner, passer by, hab resident",
        "Marking the local area with gang tags - AR, spray paint, pens, animatic stickers",
        "Shaking down the locals with threats and intimidation - for money, booze, sex",
        "raving to their favourite music/propaganda, extremely loudly",
        "Getting wasted, or psyching themselves up before a fight or a raid",
        "Facing down cops/security/another gang - as far as they can get without a fight",
        "Participating in tests of skill or daring among themselves",
        "Making a deliberate attempt at being visible, strengthening presence in the area",
        "engaged in their main biz, or negotiating employment with another party",
    ],
    "oracle-gang-rumors-hooks-result": [
        "The gang is in danger of being destroyed by a more powerful rival",
        "The gang are showing symptoms of having contracted a disease",
        "The gang knows of hidden ways through the city or into a building",
        "The gang have procured (or manufactured) a dangerous narcotic or toxin",
        "The gang harbours an exile or outcast from a wealthy and powerful family",
        "The gang have discovered valuable technology lost by powerful NPC",
        "The gang has a splinter cell of powerful members, who are impossible to control",
        "The gang are grabbing runaways for corporate experiments, and getting bolder",
        "A member has fallen in love with a rival gang member and fled, knowing too much",
        "The gang has access to unusual cybernetics, and it’s drawing attention to them",
    ],
};
export default factionOracleResults;