const miscOracleResults = {
    "oracle-combat-action-result": [
        "Block a path or cut off an objective",
        "Cause reckless damage",
        "Change weapons or tactics",
        "Compel a surrender or concession",
        "Coordinate with allies",
        "Corner, trap, or entangle",
        "Counter or reflect an attack",
        "Create a distraction",
        "Destroy something or render it useless",
        "Fall back or stand off",
        "Hide or sneak",
        "Intimidate, taunt, or frighten",
        "Leverage the advantage of a weapon or ability",
        "Leverage the terrain or surroundings",
        "Lure into a vulnerable position",
        "Make a cautious or probing attack",
        "Make a ferocious or powerful attack",
        "Make a precise or careful attack",
        "Make a sacrificial attack",
        "Make an indirect attack",
        "Move in close or grapple",
        "Nullify a system, device, or weapon",
        "Overrun a position",
        "Perform a feint or trick",
        "Press an advantage",
        "Provoke a careless response",
        "Ready a decisive action",
        "Shift the fight to a new area",
        "Summon aid or reinforcements",
        "Take cover or bolster defenses",
        "Use an unexpected weapon or ability",
        "Weaken defenses",
    ],
    "oracle-ar-display-type-result": [
        "Directions",
        "Brand Logo",
        "Assistant",
        "Political",
        "Targeted Promotion",
        "Unsolicited Advice",
        "Reality Filter",
        "Warning Sign",
        "Prohibition",
        "Virtual Graffitti",
    ],
    "oracle-ar-display-aesthetic-result": [
        "Typographic Overlays",
        "Bright And Garish Glyphs",
        "Animated Persona",
        "Advertainment",
        "Emotive Imagery",
        "Rapid Motion/Distracting",
        "Reassuring Infomemes",
        "Unobtrusive And Integrated",
        "Fantastical And Otherworldly",
        "Bold/Dramatic/Authorative",
    ],
    "oracle-ar-display-style-result": [
        "Crisp/Bright",
        "3D Animated",
        "Ultra-high Resolution",
        "Sophisticated",
        "Cheap/low resolution",
        "Clear, Yet Subtle",
        "Technical/Sci-fi",
        "Surreal/Immersive/Arty",
        "Flat Vector Graphics",
    ],
    "oracle-bug-in-the-system-result": [
        "Overzealous defensive software",
        "harbours malicious virus",
        "Being assessed by sysadmin",
        "layers of legacy programming",
        "randomly goes into standby mode",
        "Badly formatted AR plug-in",
        "Installing software upgrade",
        "hacker currently querying system",
        "ROM overloaded by surplus apps",
        "recently reset to factory defaults",
        "Inquisitive low-grade AI assistant",
        "requires biometric verification",
        "Auto-downloads to linked device",
        "Net connection keeps dropping out",
        "Incompatible operating system",
        "Pop-up pandemic",
        "Software conflicts, glitchy",
        "Processor overclocked",
        "Active ‘vigilance suite’ warns user",
        "Tendency to stall or hang",
        "Malware sifting for linked devices",
        "Missing system tools/utilities",
        "errors with user interface display",
        "Physically damaged, or faulty",
        "Non-standard reprogramming",
        "Many software subroutines triggered",
        "logs recently tampered with",
        "Overheating (heat sink failing)",
        "heavily encrypted for device type",
        "Constant security warnings",
        "Non-intuitive user interface",
        "hogging the local bandwidth",
        "Prone to system crashes",
        "uses badly patched legacy code",
        "File sharing denied",
        "Configured for periodic back-up",
        "Insufficient internal battery life",
        "reveals a scheduled exploit (short)",
        "‘Access Denied’ system file errors",
        "reboots the system at random",
        "requires admin password",
        "Can only handle minimal processes",
        "user interface in foreign language",
        "Discomforting feedback",
        "3rd party updaters need unchecking",
        "Menu options it shouldn’t have",
        "In the process of being stolen",
        "running slow, searching for updates",
        "Feeds log and data to manufacturer",
        "Tagged and monitored by rogue AI",
    ],
    "oracle-music-subculture-result": [
        "Black Ambient",
        "Photonic Wave",
        "Xhosa Trance",
        "Industrial Grind house",
        "Eurozeit Groove",
        "Chip hop",
        "Glitchcore",
        "Machine-Soul Dub",
        "Toxic Ska",
        "Anthemic NeoPunk",
        "0core",
        "Acid panda",
        "Beastie",
        "Bitcrusher",
        "Bloodsport",
        "Cadavercore",
        "Codefolk",
        "Converter",
        "Corpodrone",
        "Cosmopunk",
        "Cvlt",
        "Cybercrust",
        "CyPop",
        "Daemonista",
        "Deathbloc",
        "Doomtroop",
        "Ghoul",
        "Glitchmode",
        "Goregrinder",
        "Hexcore",
        "Hype street",
        "Kill Mode",
        "Meta",
        "Mimic",
        "Minimal",
        "Minotaur",
        "Mobwave",
        "Monsterwave",
        "Murdercore",
        "Necropop",
        "Neurotripper",
        "NuFlesh",
        "NuGoth",
        "NuPrep",
        "Oceanwave",
        "0G",
        "Old-school cyber",
        "Orbital",
        "Postlife",
        "Pyrocore",
        "Razormouth",
        "Retro metal",
        "Riot kid",
        "Robomode",
        "Roller bruiser",
        "Technoir",
        "Trad punk",
        "Wallgoth",
        "Waster",
        "K-Pop",
        "J-Pop",
        "Cyberbilly",
    ],
    "oracle-social-media-result": [
        "Impossibly dull, mainly life memes",
        "Sickening, cute, GIF-heavy, juvenile",
        "Dominated by political viewpoint",
        "Social Justice Champion",
        "Work Related Self-promotion",
        "Fan of unlikely <a href=\"/oracles/misc-oracles#music-genre--subculture-style\">musical genre</a>",
        "Lonely - desperate to make friends",
        "Mainly family and friends (lots)",
        "Sexually predatory, catfish/stalker",
        "hobby focused (gaming/making)",
        "Obvious Fake News reblog",
        "Lewd Pictures / Scantily Clad Posing",
        "Attempt at cancelling a celebrity",
        "Attempt at trolling/harrasing a celebrity",
        "Gore / Real Life accident graphic video",
    ],
    "oracle-hot-new-fad-result": [
        "Everybody loves neutraceuticals",
        "Weatherproof glowing ponchos",
        "Slacktivist angst-lit forums",
        "Smeat™ (smart meat; pick flavour)",
        "Zone dancing in public places",
        "expensive Sumo Food® kale shakes",
        "Randomiser-app-driven conversation",
        "Freak Fighter brand endorsements",
        "Info-socialism - secret-free society",
        "Fabrics change colour with mood",
        "Highly Addictive casual videogame highscore sharing",
        "Extremely divisive meme",
        "Discussion-attracting philosophical trope",
        "Potentially dangerous shared-video challenge",
    ],
    "oracle-news-feed-result": [
        "Money laundering kingpin reportedly apprehended in Bangui.",
        "An unidentified aircraft reportedly bombed an office building in Kuala Lumpur. Details are scant. However, sources on the ground claim the attack could be part of a widening corporate war.",
        "Singapore will be the next host of CyberwarCon.",
        "Recent bombing in Vientiane seemingly tied to a corporate land rights struggle.",
        "Former Argentinian president arrested in Prague on tax evasion and various corruption charges.",
        "Corporate civil war spills over into the streets of Seoul. Reports of death and injuries are coming in as people flee the chaos.",
        "Hurricane ravaged New Orleans sees historic flooding and loss of life.",
        "Monorail derailment in Mexico City causes chaos. Initial reports say it was an accident. However, investigators are still rushing to the scene.",
        "Food riots turn deadly in Seattle. Reports of gunfire and people being trampled are all the information at this time.",
        "Hackers reportedly gained access to the global satellite network for 17 minutes earlier this month before being locked out. Authorities are not confirming whether any data was stolen or not.",
        "Reports of a coup attempt in Burkina Faso have left African financial markets reeling.",
        "Paramilitary commandos seized a natural gas pipeline outside of Pretoria.",
        "As police in Madrid break up an international hacking ring four officers and more than 20 suspects are reported dead. More than four hundred arrests have been made with more to come in the following days according to officials on the ground.",
        "Miami corporate data center reportedly under attack by masked gunmen.",
        "Global markets jittery as cryptocurrencies slide.",
        "A grisly scene unfolds in Cairo today as authorities discover a warehouse containing more than 300 bodies.  At this time little is known of the victims or their murders.",
        "Turkmenistan, Uzbekistan, Kazakhstan inch closer to war as news spreads of recent arms purchases by the three nations.",
        "Mass casualties reported in Jakarta. Suicide bomber suspected.",
        "Officials in Dhaka say ceasefire talks between the Bangladeshi government and rebel fighters are close to breaking down after another attack on a port facility in Chittagong.",
        "An earthquake in Ulaanbaatar displaces thousands and damages a large part of the city. The official death toll at this time stands at 291 but is expected to soar in the coming days.",
        "Corporation convoy reported missing in rural Azerbaijan.",
        "Lisbon was the scene of more than 50 arrests today as authorities searched for the ringleaders of an international cryptocurrency scam.",
        "Recent disappearance of a Nigerian nuclear scientist now reportedly linked to a Stockholm-based terror group.",
        "Officials close to the source indicate that the city of Orlando will be placed entirely under corporation control by the end of the month. Reports also say that the current democratically elected mayor left the city last evening.",
        "An illegal arms deal gone wrong leads to a trail of death and destruction across the city of Belgrade.",
        "Tsunami pounds islands in Indonesia. Hundreds of thousands feared dead.",
        "Dow Jones plunged on eve of major corporation bankruptcy announcement.",
        "Large drone crashes into Eiffel Tower. More details to come.",
        "Renewed crackdowns on the sewer people of Bucharest spark violence and unrest in the city.",
        "For the third straight week, New York City is crippled by widespread power outages.",
        "Reports say one of the largest banks in Montevideo is currently under cyberattack.",
        "Corporate mercenary units have laid siege to the Jumgal District capital of Chaek in Kyrgyzstan. Kyrgyzstani officials report they are rushing aid to the besieged town, but fear it will have to surrender before the help arrives.",
        "Sierra Leone and Guinea have announced a ceasefire in their decade long territorial conflict.",
        "Billionaire CEO found dead in an Ashgabat alleyway. Cause of death is being withheld at this time.",
        "Officials in Panama report that an attempt to seize the Panama Canal was thwarted. The attackers are only described as mercenaries and seemed to have had air, sea, and land craft at their disposal. Officials also wish to express their gratitude for the sacrifice and bravery of the Panian army in the course of the conflict.",
        "Officials in Kathmandu issued a statement saying hackers may have drained the country’s entire treasury.",
        "Hackers demand ransom after claiming to control the entire Moscow traffic grid.",
        "High-rise fire in Mumbai feared to be terrorist attack. The death toll could reach into the thousands.",
        "Prominent official kidnapped in Guatemala City. A terrorist group is suspected.",
        "The corporate oil war intensifies as rivals struggle for control of several refineries near Tripoli.",
        "A corporate vice president was said to be the target in an attack that killed 12 in Antananarivo.",
        "New wave of violence erupts as the Brazilian brush wars ceasefire falls apart.",
        "Asian markets down after poor earnings reports.",
        "Band of data couriers believed to be hiding in Casablanca after corporate and governmental authorities alerted to illegal activities.",
        "Public outcry after video of armed gangs executing police officers in Tokyo was released.",
        "A series of explosions rocked London in the early AM today. Chaos and confusion reign as authorities search for the perpetrators and the wounded are treated and the dead are counted.",
        "Officials in Honduras report an aircraft crash near the outskirts of Tegucigalpa. No survivors are expected.",
        "The kidnapping of a high-ranking German official in Paramaribo has trade negotiations between European and South American countries on the verge of collapse.",
        "The city of Warsaw is in flames tonight as mass protests concerning corporate and police brutalities rage nearly unchecked.",
        "Cape Verde reports a data breach in the gambling servers housed in the island nation.",
        "Havana nightclub fire kills dozens.",
        "Knife-wielding attackers kill 92 and injure scores more in Beijing before being killed by security forces.",
        "Carnage in the city. San Diego’s crimewave continues with 234 murders in 24 hours.",
        "Bridge collapse in Chicago leaves dozens missing and feared dead.",
        "Alleged corporate bombmaker shot dead in Port Vila, Vanuatu.",
        "Riots in Rome have reportedly forced the mayor into hiding.",
        "Famed painting stolen from a Copenhagen museum in a daring daytime raid.",
        "Military convoy attacked near Los Angeles. A military spokesman would neither confirm nor deny if anything was stolen.",
        "Azerbaijani tanks rolled into Artsakh in the early morning hours in an apparent attempt to reclaim the breakaway republic.",
        "Iranian oil tanker vanishes seemingly without a trace in the Indian Ocean.",
        "Brazen US Treasury data thieves reportedly traced to Harare.",
        "Cargo ship explodes in the port of Douala. Dozens are feared dead. No word as yet on the identity of the vessel or its cargo.",
        "Woman blows herself up rather than be captured in Quito. Authorities say she is wanted in connection with a data-mining scheme.",
        "Mali set to issue new foreign bonds, though investors are skittish.",
        "Outbreak feared in Nouakchott. Leaders plead for corporate assistance in containing the spread of the disease.",
        "Casino heist in Monaco leaves authorities searching for suspects who may have stolen upwards of two hundred million dollars.",
        "Daring corporate raid on hacker den in Port Moresby yields petabytes of stolen information.",
        "Chemical plant explosion in Hanoi leaves a deadly cloud over the city. Residents forced to flee.",
        "Global stock markets soar as the announcement of a major corporate merger looms.",
        "Illegal arms dealer and a high-profile client believed to be trapped by corporate security forces in Asunción compound.",
        "Lesotho reportedly offered sanctuary to alleged corporate embezzler.",
        "US Congress approved a 4.8 trillion dollar corporate bailout.",
        "Explosion in Algiers leaves hundreds dead.",
        "In an early morning raid, gunmen seized control of a broadcasting tower in Addis Ababa.",
        "UN Peacekeeper convoy ambushed and slaughtered outside Mogadishu.",
        "A submarine carrying approximately 3 tons of heroin was captured off the coast of San Francisco.",
        "Office building collapsed in Maputo. Rescuers are on the scene. No word yet on casualties.",
        "Train derailment in Nairobi spills chemicals that sicken thousands.",
        "A car bomb detonated in downtown Denver killed several hundred. Authorities have locked down the city.",
        "Oslo was the scene of carnage this morning as a paramilitary group raided the main courthouse. Early reports claim the group freed a prisoner awaiting trial.",
        "Powerful storm damages buildings and brings the streets to a halt in New Delhi.",
        "The Saudi king has invited the foreign ministers of several regional powers to a conference in Riyadh.  The move could be seen as hostile by Iran.",
        "Famed corporate mercenary leader found dead in Asmara.",
        "Man shot dead in Red Square now linked to a string of bank robberies across Europe.",
        "Archeological discovery could lead to corporate war in Cambodia.",
        "Oil spill forces Sydney harbor to close.",
        "An early morning armored car convoy heist leaves the streets of Vienna awash with blood. Authorities say a corporate convoy of eight armored vehicles was assaulted and at least six of them were stolen.  Most of the dead are believed to be civilians.",
        "Cryptocurrency billionaire to hold private summit with key world leaders in Brussels.",
        "Man with ties to terror group captured after stunning chase through the streets of Niamey.",
        "Late-night gun rampage leaves 47 dead in Bangkok.",
        "Russian satellite set to crash in the Gobi desert later this week.",
        "Massive data breach at the Pentagon could put all US military activities in Africa in jeopardy.",
        "Infamous hacker arrested in Ankara this morning. The United States is said to have already asked for quick extradition.",
        "A British national was arrested in Amsterdam carrying a million dollars in cash and a case full of illegal microchips. Authorities are said to be scouring the individual’s recent travels and business dealings.",
        "Bombing in a Manila marketplace kills more than 300.",
        "Brazilian organized crime syndicate believed to be behind recent cyberware hacking incidents of high-ranking government officials.",
        "New round of vaccinations in Chad halted as security concerns grow.",
        "Rare Chinese vase auction sparks intense bidding war.",
        "Sectarian conflict erupts into violence in Baghdad. The majority of the city is now locked down.",
        "Drone attack on several vehicles in Lagos left at least 16 dead. The victims have yet to be identified.",
    ],
    "oracle-vid-show-result": [
        "Implant Fixers (reality/comedy)",
        "Simsense & Sensibility (drama)",
        "Zone Glider Xtreme (gameshow)",
        "Crash & Burn (hacking competition)",
        "My Two Clones (sitcom)",
        "Atomic Geisha Dojo (gameshow)",
        "Personality Adjustment (reality)",
        "The Clade (soap opera)",
        "Fracture Point (cop show)",
        "Alt Cult Zero (documentary)",
        "Chip In (tech reviews show)",
        "Combat Cabb (comedy/action show)",
        "Bushido (action movie franchise)",
        "Night after Night with Ziggy Q (talk show)",
        "ROLLERBALL League (extreme sports)",
        "Attuned In (talk show)",
        "Jack'd-Ass (blooper show)",
        "The Running Man (extreme game show)",
        "Death Race 2K (sports show)",
        "Corporate Wars (documentary)",
        "0G Ball (orbital sports)",
        "Zaibatsu Masters - Road to CEO (reality)",
        "Speedball: BRUTAL Playoffs (sports)",
        "NET Surfers (hacking competition)",
        "RIP: A Remix Manifesto (documentary)",
        "Body Modders (reality competition)",
        "Limbs-Off (cyberware reviews)",
        "Fleeting Fads (celebrity and meme news)",
        "Shadowrunners (action show)",
        "Idoru Spotlight (pop music news)",
    ],
};

export default miscOracleResults;