const missionOracleResults = {
    "oracle-mission-people-result": [
        [
            "a Street Gang Member",
            "a Corporate Aristocrat",
            "a Pimp",
            "a Thug",
            "a Prostitute",
            "a Fixer",
            "a Priest",
            "a Business Owner",
            "a Mercenary",
            "a hacker",
            "a Scientist",
            "a Cop",
            "a Mobster",
            "a Smuggler",
            "a Bounty hunter",
            "a Syndicate Boss",
            "a Concubine",
            "a Tech Specialist",
            "a Soldier",
            "a Scavenger",
            "a Government Agent",
            "a Doctor",
            "a Drug Dealer",
            "a Celebrity",
            "an Artificial Intelligence",
            "an Artist",
            "a Thief",
            "a Media personality",
            "a Nomad",
            "a Synthetic",
            "a Driver",
            "a Broker",
            "a Clone",
            "a Designer",
            "a People Trafficker",
            "a Forger",
            "an ex-con",
            "a Fanatic/extremist",
            "a Performer",
            "a Journalist",
            "a Drug Lord",
        ],
        [
            "wants to",
            "needs to",
            "must",
            "plans to",
            "is forced to",
            "needs someone to",
        ],
        [
            "kill",
            "maim",
            "make a delivery to",
            "protect",
            "intimidate",
            "extract",
            "escape from",
            "monitor",
            "smuggle",
            "find",
            "blackmail",
            "steal from",
            "collect something from",
            "make a payment to",
            "record",
            "threaten",
            "kidnap",
            "save",
            "con",
            "flee with",
            "employ",
            "sell out",
            "investigate",
        ],
        [
            "a Street Gang Member",
            "a Corporate Aristocrat",
            "a Pimp",
            "a Thug",
            "a Prostitute",
            "a Fixer",
            "a Priest",
            "a Business Owner",
            "a Mercenary",
            "a hacker",
            "a Scientist",
            "a Cop",
            "a Mobster",
            "a Smuggler",
            "a Bounty hunter",
            "a Syndicate Boss",
            "a Concubine",
            "a Tech Specialist",
            "a Soldier",
            "a Scavenger",
            "a Government Agent",
            "a Doctor",
            "a Drug Dealer",
            "a Celebrity",
            "an Artificial Intelligence",
            "an Artist",
            "a Thief",
            "a Media personality",
            "a Nomad",
            "a Synthetic",
            "a Driver",
            "a Broker",
            "a Clone",
            "a Designer",
            "a People Trafficker",
            "a Forger",
            "an ex-con",
            "a Fanatic/extremist",
            "a Performer",
            "a Journalist",
            "a Drug Lord",
        ],
    ],
    "oracle-mission-thing-result": [
        [
            "a Street Gang Member",
            "a Corporate Aristocrat",
            "a Pimp",
            "a Thug",
            "a Prostitute",
            "a Fixer",
            "a Priest",
            "a Business Owner",
            "a Mercenary",
            "a hacker",
            "a Scientist",
            "a Cop",
            "a Mobster",
            "a Smuggler",
            "a Bounty hunter",
            "a Syndicate Boss",
            "a Concubine",
            "a Tech Specialist",
            "a Soldier",
            "a Scavenger",
            "a Government Agent",
            "a Doctor",
            "a Drug Dealer",
            "a Celebrity",
            "an Artificial Intelligence",
            "an Artist",
            "a Thief",
            "a Media personality",
            "a Nomad",
            "a Synthetic",
            "a Driver",
            "a Broker",
            "a Clone",
            "a Designer",
            "a People Trafficker",
            "a Forger",
            "an ex-con",
            "a Fanatic/extremist",
            "a Performer",
            "a Journalist",
            "a Drug Lord",
        ],
        [
            "wants to",
            "needs to",
            "must",
            "plans to",
            "is forced to",
            "needs someone to",
        ],
        [
            "destroy",
            "clone",
            "deliver",
            "protect",
            "sell",
            "steal",
            "smuggle",
            "locate",
            "hide",
            "collect",
            "receive",
            "control/modify",
            "flee with",
            "use",
            "buy",
        ],
        [
            "a Neural Processor",
            "a Bottle of Vintage Wine",
            "a Photograph",
            "a Narcotic",
            "a Weapon",
            "an ID Card",
            "a piece of Jewellery",
            "a Software program",
            "a Security Passcard",
            "a specific target’s DNA",
            "a Cybermodem",
            "Offline Digital Files",
            "a hard Drive",
            "a Designer Virus",
            "an Attache Case",
            "a Data/Vid Chip",
            "a shipment of Drugs",
            "a Vehicle",
            "a Key Card",
            "a Computer Virus",
            "a Cybernetic limb",
            "a Synthetic Brain",
            "a Personality Module",
            "an exo-Womb",
            "a hardcopy Schematic",
            "a Military ICE Breaker",
            "a Nano Fabricator",
            "an Antique Katana",
            "a specific Antidote/Medicine",
            "an Artificial Intelligence",
            "a SimStim recording",
            "a robot",
            "a Memory Chip",
            "an Augmented Pet",
            "trafficked human Organs",
            "a Patient In a Cryo Vat",
            "a Work of Art",
            "the severed head of someone with a cortex chip",
        ],
    ],
    "oracle-rumors-street-result": [
        "A hacker group has taken control of a defense satellite.",
        "The plans for a new tank design were stolen from the government.",
        "Hackers breached the World Bank.",
        "Separatist fighters seized an oil platform in the Gulf of Mexico.",
        "A corporation has developed a new crime-fighting technology.",
        "A street food vendor needs help fending off some thugs.",
        "Pirates seized a large yacht off the coast of Spain.",
        "A reward is being offered for an arsonist working in the middle-class section of town. Seven buildings have been torched so far.",
        "A prominent cybersecurity professional has disappeared.",
        "A cybernetic implant shop was burglarized the other night. The owners are looking for help finding the thieves.",
        "A truly sentient AI is loose in the global net.",
        "A gang member asks to deliver a package to someone across town.",
        "A corporate fat cat is looking to hire a team for the acquisition of some “exotic goods.”",
        "A corporate officer angling for a promotion is looking for dirt on her rival.",
        "A terrorist group seized a historic building in London.",
        "A prototype microchip was stolen from a corporate research lab.",
        "Hackers released the offensive emails of several popular actors and actresses.",
        "A woman has been asking around nightclubs if anyone has seen her son.",
        "Several art museums have reported recent thefts of ancient Chinese artifacts.",
        "A data courier disappeared during a delivery.",
        "The government is going to forcibly clear a slum in a few days.",
        "A young solo hacker disappeared a few days ago.",
        "A corporate agent needs some government data. However, the government is not willing to share.",
        "A street doc needs help collecting a bill from a former client.",
        "A trash pickup service is actually a cover for a smuggling ring.",
        "Several high-profile celebrities were killed in a flying car crash.",
        "Police busted a large drug ring.",
        "A private detective asks to investigate a nightclub that burned down killing several dozen people.",
        "Separatist fighters seized an airport in South Korea.",
        "A hacker group is threatening to “darken” the Los Angeles Metroplex.",
        "A border dispute between South Sudan and Sudan flared up recently. Both sides are hiring fighters.",
        "A local nightclub owner claims to have a map of a corporate HQ building showing a hidden thirteenth floor.",
        "Jewel heist turned deadly in Peru and authorities are looking for several suspects who murdered three guards.",
        "A street doc is looking to hire a team for some work.",
        "Several corporate honchos were killed in a flying car crash. Word is it was no accident.",
        "A corporate agent needs a data courier to make a delivery to a safe house in another city.",
        "A terrorist group seized a governmental building in Hong Kong.",
        "A local nightclub owner found a silver pocket watch while cleaning up. It seems to have a data chip inside.",
        "A dead body was discovered in an alley. On it was a secured laptop, a butterfly knife, and a map of a city with several locations highlighted.",
        "A street vendor asks to deliver a package to a police station.",
        "A nightclub is hiring extra security for a big live show.",
        "Pirates seized a container ship off the coast of Somalia.",
        "The plans for a new aircraft design were stolen from a corporation.",
        "A brazen daylight raid on a corporate HQ resulted with the robbers making off with 100 million dollars in cash and data assets.",
        "A fired corporate exec is looking to hire a team for a job.",
        "A local nightclub’s booze shipment was hijacked.",
        "Rebel fighters seized a town in Hungary.",
        "A group of hackers has been gathering every night this month at a certain club.",
        "The president of South Africa survived an assassination attempt.",
        "A garment sweatshop with deplorable conditions is operating nearby.",
        "Two corporations are on the verge of a hot war.",
        "A prominent politician’s daughter has been reported missing.",
        "Police raided a street doc’s office.",
        "A mysterious figure asks to deliver a jumpdrive to a certain corporate office.",
        "A madman ran through the streets last night yelling, “They own us! They own us! They bought us all!” No one has seen him since.",
        "A computer programmer, now flush with cash, has dreams of building his own “consulting” company.  He’s looking to hire operators for several jobs.",
        "Container shipwreck washed up on the coast of Algeria.",
        "A corporate-trained “asset” has gone rogue.",
        "A restaurant manager asks to deliver food to a “special client.”",
        "A corporate goon is quietly hiring operators for something big.",
        "Several corporations are looking for the creator of a new virus. They want to “have a chat.”",
        "Separatist fighters seized an airship over Berlin.",
        "A casino dealer needs help finding a patron who left a gold watch at his table.",
        "A professor is looking to hire someone to deliver a book to a swanky penthouse.",
        "A new highly-addictive drug is on the street and users are not faring too well.",
        "A high-profile corporate worker wants to defect and needs to hire protection.",
        "A shadowy figure needs help getting access to a certain set of satellite images. She is paying well.",
        "Three billion euros worth of gold bullion is missing from a reserve in Paris.",
        "The police mainframe was hacked and tens of thousands of records were stolen.",
        "A high-ranking government official has been kidnapped.",
        "An armored car heist was foiled by corporate security.",
        "A new gang is shaking down small shop owners.",
        "A terrorist group seized an office building in San Francisco.",
        "Pirates seized an oil tanker off the coast of Thailand.",
        "A down-on-his-luck hacker has been bragging about a big score.",
        "Police busted a large illegal trade ring.",
        "A rogue corporate merc unit is assassinating former employers.",
        "A merc unit is searching for a corporate defector.",
        "Hackers stole information concerning a new disease.",
        "Rebel fighters seized a small city in Arizona.",
        "Rebel fighters seized a village in France.",
        "Hackers breached the security of the US Federal Reserve Bank.",
        "Weapon shop owner asks to deliver a package to a client.",
        "Rebel fighters seized a small city in Brazil.",
        "A border dispute between Croatia and Montenegro flared up recently. Both sides are hiring fighters.",
        "The Io Mining Company is hiring. A series of rigorous physical requirements must be met.",
        "A politician reaches out for “some help” with a rival.",
        "Rumor has it that the state-run lottery is rigged. Only the rich win, yet the poor play more often.",
        "A corporation is hiring guards for a special shipment of chemicals.",
        "A massive container ship disappeared in a storm in the Indian Ocean.",
        "Unions plan on staging a citywide strike in the coming days.",
        "New candy is poisoning children.",
        "A low-level hacker is trying to sell a map of the city sewers.",
        "Someone is paying high prices for Egyptian artifacts.",
        "The plans for a new spacecraft design were stolen from a design firm.",
        "A bounty has been placed on a hacker who stole data from a new startup.",
        "The street children seem to be more organized recently.",
        "Illegal arms shipment seized in Kinshasa by police was stolen by an unknown assault unit.",
        "Data breach exposed personal data of 300 million people.",
        "Corporate agents are visiting the slums looking for “volunteers.” Volunteers for what is unclear.",
    ],

    "oracle-nightclub-encounter-result": [
        "A person spits in the face of one of the characters.",
        "Police officers enter and arrest a patron.",
        "A fight breaks out right next to you.",
        "A bartender smashes a bottle over the head of a patron.",
        "A man drops a credstick near you.",
        "Someone attempts to pickpocket one of the characters.",
        "An unconscious woman near the restrooms.",
        "A heavily-tattooed man says one of the characters pushed him.",
        "A woman crying in the corner.",
        "Police raid the club.",
        "An Ex spots one of the characters.",
        "An unconscious man in the corner.",
        "Someone tries to sell a gun to a character.",
        "Someone approaches you and says you are wanted in a backroom.",
        "A gorgeous woman asks one character to play pool.",
        "Several individuals wearing gang colors tell you that you are sitting at their table.",
        "A car crashes through the front of the club causing mayhem.",
        "Someone tries to slip something a character’s drink.",
        "Gang raids the club.",
        "Someone throws a drink into a character’s face.",
        "Corporate mercenary unit raids the club.",
        "At a secluded table, a person types fanatically on a computer.",
        "A dog runs loose in the club.",
        "A person yells at one of the characters, then comes close and slips them a note before running out of the room.",
        "Someone offers one character a cigarette.",
        "The power goes out and panic ensues.",
        "DJ’s pyrotechnics malfunction starting a fire.",
        "An older man desperately trying to look young attempts to talk to every female member in your group.",
        "A woman hands a character a credstick and slips into the crowd.",
        "The DJ is having an off night. People begin to boo.",
        "The music stops as the DJ appears to be checking his email. The crowd starts becoming unruly.",
        "A man hands a microchip to a character and slips away.",
        "A man crying in the corner.",
        "A fight breaks out in the ladies room",
        "When a man is bumped into he fumbles a container and the surrounding area is treated to a shower of green pills.",
        "The DJ walks out causing the crowd to get restless.",
        "A dude just standing in the middle of the dance floor.",
        "A fight breaks out in the men’s room",
        "A celebrity holding court at a corner table.",
        "Someone mistakes a character for someone else and punches them.",
        "You witness a drug deal.",
        "Someone loudly complains about the DJ. The DJ pulls a gun.",
        "Bouncers get into a fight with some patrons.",
        "Several patrons begin to heckle the DJ.",
        "A drug deal goes bad and a gun is pulled. People panic.",
        "A bouncer asks to see one character’s ID",
        "An illegal fight club is being held in a backroom.",
        "A person passed out at a table.",
        "Bouncers are keeping people out of a certain backroom.",
        "A light bar falls, hurting several people.",
        "Fight breaks out among rival gangs.",
        "You see someone slipping something into another’s drink.",
        "The DJ motions to one of the characters and hands them a jumpdrive.",
        "Small orange pills lie on the floor.",
        "As a character sits down they notice a yellow pill on the chair.",
        "Someone mistakes a character for someone else and begins screaming at them.",
        "A bartender throws a drink in the face of one of the characters.",
        "The bartender tells you drinks are on the house.",
        "A person bumps into a character hard.",
        "The selves of alcohol behind the bar collapse causing a huge mess and injuring some people.",
        "You are given someone else's drinks.",
        "Dueling DJs get into a fight.",
        "A drug dealer offers you a variety of pills.",
        "Illegal gambling is going on in a backroom.",
        "An older woman desperately trying to look young attempts to talk to every male in your group.",
        "The crowd starts throwing bottles at the DJ.",
        "A woman asks one character to dance.",
        "A shadowy figure across the room buys you a round of drinks.",
        "A popular DJ is playing tonight and the place is packed.",
        "Bouncers tell one of the characters they have to get out.",
        "A small bomb explodes across the room from you.",
        "A man begins to flirt with one character.",
        "A bouncer says one character is not dressed appropriately and will have to leave.",
        "As a character sits down they notice a credstick on the chair.",
        "Bouncers toss out a drunk patron.",
        "Someone on the dance floor pulls a gun.",
        "A bartender pulls a gun on a patron.",
        "A bouncer approaches you and tells you that you haven’t paid for your drinks.",
        "A bouncer says that they heard you are threatening other club-goers.",
        "A jumpdrive lying on the floor.",
        "A person bumps into a character lightly.",
        "A woman hands a jumpdrive to a character and runs away.",
        "A woman asks to buy her a drink.",
        "A person hands a character a smartphone and runs away.",
        "A man asks to buy him a drink.",
        "A waitress tells you the owner would like to see you.",
        "A bouncer says other patrons think you are a group of pickpockets.",
        "One character sees an ex.",
        "A man hands one of the characters a crisp one hundred US dollar bill then disappears into the crowd.",
        "A couple making out.",
        "The bartender asks you what you are drinking.",
        "A Man asks one character dance.",
        "A punk with a mohawk asks one character to play pool.",
        "A woman begins to flirt with one character.",
        "A smartphone lying on the floor.",
        "Someone mistakes a character for someone else and begins kissing them.",
        "Someone in the crowd throws a bottle that hits a character.",
        "The music stops abruptly and someone announces the club is closed.",
        "A fight breaks out on the dance floor.",
        "A couple screams at each other causing a scene.",
    ],
};

export default missionOracleResults;